<div class="cantener">
  <div class="register-main">
      <div class="registerPage">
			<?php echo $this->Form->create("Admin",array("url"=>array("controller"=>"Home" , "action"=>"forgetpassword" ),"id"=>"forgetForm"));?>
			
			    <?php if(@$step == 2):?>
			            <?php echo $this->Form->input("step",array("type"=>"hidden","value"=>2));?>
			            
			            <p>
							<label>Code:</label>
							<span>
								<?php echo $this->Form->input("code" , array("label" => false , "div" => false,"required"))?>
							</span><font color="#0000ff">&nbsp;*</font>
						</p>
						
						<p>
							<label>Password:</label>
							<span>
								<?php echo $this->Form->input("password" , array("label" => false , "div" => false,"required","type"=>"password"))?>
							</span><font color="#0000ff">&nbsp;*</font>
						</p>
						
						<p>
							<label>Confirm Password:</label>
							<span>
								<?php echo $this->Form->input("confirm_password" , array("label" => false , "div" => false,"required","type"=>"password"))?>
							</span><font color="#0000ff">&nbsp;*</font>
						</p>
						
			    <?php else:?>
			            <?php echo $this->Form->input("step",array("type"=>"hidden","value"=>1));?>
			            
			            <p>
							<label>Enter your email:</label>
							<span>
								<?php echo $this->Form->input("email" , array("label" => false , "div" => false,"required"))?>
							</span><font color="#0000ff">&nbsp;*</font>
						</p>	
						
						<p>
                           <label>User Type:</label>
                           <span class="rdio-spac">
                               <input type="radio"  name="data[Admin][user_type]" value="Athlete" checked="checked"/>
                               <label>Athlete</label>
                               <input type="radio"  name="data[Admin][user_type]" value="HsAauCoach">
                               <label>High School / AAU Coach</label>
                               <input type="radio"  name="data[Admin][user_type]" value="CollegeCoach"/>
                               <label>College Coach</label> 
                           </span>
                        </p>
                        
                        <p>
                           <label>&nbsp;</label>
                           <span>
                              <?php echo $this->Form->submit("Submit",array("div"=>false));?>
                           </span>
                        </p>
			    <?php endif;?>    
			
			<?php echo $this->Form->end()?>
			
			<?php echo $this->Html->link(__("Back to Login",true),array("controller"=>"Home" , "action" =>"login"));?>
		</div>
	</div>
</div>					