<table width="100%" cellpadding="3" cellspacing="5">
	<tr>
		<td width="100%" align="center">
		<table width="95%" cellpadding="0" cellspacing="3">
			<tr>
				<td width="100%" class="SearchHead"><b>HS / AAU Coach Rating</b></td>
			</tr>
			<tr>
				<td width="100%" class="GeneralFont">&nbsp;</td>
			</tr>
			<tr>
				<td width="100%">
				<table width="100%" cellspacing="0" cellpadding="2">
					<tr>
						<td width="100%" valign="top">
						<table width="100%" cellspacing="0" cellpadding="3">

						<?php if(sizeof($hsAauCoachRating) > 0 && isset($hsAauCoachRating['0']['HsAauCoachRating']['college_coach_id'])){ ?>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									nowrap>How accurate was this coach in projecting the level at
								which the athlete can contribute?</td>
								<td class="normalblack_12" valign="top" nowrap><?php echo $hsAauCoachRating['0']['0']['contribute']; ?>
								with <?php echo sizeof($hsAauCoachRating);?> votes</td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									nowrap>How prompt was this coach in responding to your
								communications?</td>
								<td class="normalblack_12" valign="top" nowrap><?php echo $hsAauCoachRating['0']['0']['comunication']; ?>
								with <?php echo sizeof($hsAauCoachRating);?> votes</td>
							</tr>
														
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									nowrap>How prompt was this coach in responding to your requests
								for game tape?</td>
								<td class="normalblack_12" valign="top" nowrap><?php echo $hsAauCoachRating['0']['0']['request_game_tape']; ?>
								with <?php echo sizeof($hsAauCoachRating);?> votes</td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									nowrap>How honest was the coach in your interactions with
								him/her?</td>
								<td class="normalblack_12" valign="top" nowrap><?php echo $hsAauCoachRating['0']['0']['honest']; ?>
								with <?php echo sizeof($hsAauCoachRating);?> votes</td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									nowrap>How well does this coach prepare his/her athlete's for
								college sports?</td>
								<td class="normalblack_12" valign="top" nowrap><?php echo $hsAauCoachRating['0']['0']['prepration']; ?>
								with <?php echo sizeof($hsAauCoachRating);?> votes</td>
							</tr>

							<?php } else {?>
							<tr>
								<td class="normalblack_12" valign="top" nowrap>HS / AAU Coach
								Not Rated by College Coach</td>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									nowrap><b>&nbsp;</b></td>
							</tr>
							<?php }?>
						</table>
						</td>

						<tr>
							<td class="normalblack_12" valign="top" height="25" width="40%"
								colspan="2"><input type=button value="Close"
								onClick="javascript:window.close();"></td>
						</tr>				
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
</table>
