<table width="100%" cellpadding="3" cellspacing="5">
	<tr>
		<td width="100%" align="center">
		<table width="95%" cellpadding="0" cellspacing="3">
			<tr>
				<td width="100%" class="SearchHead"><b>Coach Details</b></td>
			</tr>
			<tr>
				<td width="100%" class="GeneralFont">&nbsp;</td>
			</tr>
			<tr>
				<td width="100%">
				<table width="100%" cellspacing="0" cellpadding="2">
					<tr>
						<td width="100%" valign="top">
						<table width="100%" cellspacing="0" cellpadding="3">
							<tr>
								<td class="normalblack_12" valign="top"><b>Name</b></td>
								<td class="normalblack_12" valign="top"><?php echo $hsAauCoach['HsAauCoach']['firstname']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Email</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $hsAauCoach['HsAauCoach']['email']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Phone</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $hsAauCoach['HsAauCoach']['phone']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Status</b>
								</td>
								<td class="normalblack_12" valign="top">
									<?php if ($hsAauCoach['HsAauCoach']['status'] == '1') { 
										echo 'ACTIVE';
									} else { 
										echo 'DE-ACTIVE';
									}?> 									
								</td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" colspan="2">&nbsp;</td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									colspan="2"><input type=button value="Close"
									onClick="javascript:window.close();"></td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td width="100%" align="center">&nbsp;</td>
	</tr>
</table>
