<div class="cantener">
	<div class="register-main">
		<div class="registerPage">
			<h1>HS / AAU Coach Listing</h1>		
		  	<table cellspacing="2" cellpadding="5" bordercolor="#808080" border="0" width="100%" class="tablePadd" style="border-collapse: collapse;">
		  		<tr>
		  	  		<td align="left" class="normalblack_12" width="25%">&nbsp;<strong>HS/AAU Coach Name</strong></td>
		  	  		<td align="left" class="normalblack_12" width="25%">&nbsp;<strong>Team</strong></td>
		  	  		<td align="left" class="normalblack_12" width="15%">&nbsp;<strong>Sport</strong></td>
		  	  		<td class="normalblack_12" width="15%" align="center"><strong>View Profile</strong></td>
		  	  	</tr>
		  	 </table>
		</div>
	</div>
</div>	  
