<div class="cantener">
   <div class="register-main">
       <div class="registerPage subscribe " style="position:relative;">
            <div style="position:absolute;top:93px;right:10px;background:#fff;border:12px solid #e4e4e4;padding:8px 15px 12px 15px;">
                <div class="listhead" style="margin-bottom:10px">Subscription Pricing:</div>

                <div class="pricing" style="margin-bottom:0px;">
                    <span class="price-large">$14.99</span><span class="duration"> / month</span>
                </div>

                <hr class="priceline" />

                <div class="pricing" style="margin-bottom:0px;">
                    <span class="price-or">or</span> <span class="price-med-black">$158.88</span><span class="duration"> / year</span><span class="savings" style="margin-left:45px;">Save $21.00</span>
                </div>

                <hr class="priceline" />
                <div class="pricing"style="margin-bottom:0px">
                    <span class="price-or">or</span> <span class="price-med-black">$359.64</span><span class="duration"> / 3-years</span><span class="savings2">Save $180.00</span>
                </div>
            </div>

			<?php echo $this->Form->create("CollegeSubscription",array("url"=>array("controller"=>"Subscribe","action"=>"edit"),"type"=>"post"));?>
                <h1>Edit Subscription </h1>

                <div id="error" style="color: #ff0000; width: 510px;">
                   <?php if(isset($errorMsg)): ?>
	                    <div class="listhead" style="color: #ff0000; margin-bottom: 10px;">There was an error processing your subscription.</div>
	                    <ul>
	                        <li style="color: #ff0000;"><?php echo $errorMsg; ?></li>
	                    </ul>
                  <?php endif; ?>
                </div>

                <p>
                   <h2>Subscription Info</h2>

                   <div style="width:510px;line-height:20px;margin-bottom:12px;">
                        A Single Subscription lets you gain access to all Athletes of the Sport
                        you select below.  If you require multiple sports, you must purchase a
                        separate Subscription for each additional sport.
                    </div>
                </p>

                <p>
                    <label>Subscription:</label>
                    <span>
                    	<?php echo $this->Form->input("subscription_id",array("label"=>false,"div"=>false,"options"=>$active_subscriptions,"empty"=>"Select One","required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>Sport:</label>
                    <input type="hidden" name="schoolid" id="schoolid" value="">

                    <span>
                    	<?php echo $this->Form->input("sport_id",array("label"=>false,"div"=>false,"options"=>$this->Register->getSports(),"empty"=>"Select One","required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p style="margin-top:20px;">
                    <h2>Billing Information</h2>
                </p>

                <p>
                    <label>First Name:</label>
                    <span>
                        <?php echo $this->Form->input("firstname",array("label"=>false,"div"=>false,"value"=>$profileDetail['CollegeCoach']['firstname'],"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>Last Name:</label>
                    <span>
                        <?php echo $this->Form->input("lastname",array("label"=>false,"div"=>false,"value"=>$profileDetail['CollegeCoach']['lastname'],"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>Address:</label>
                    <span>
                        <?php echo $this->Form->input("address",array("label"=>false,"div"=>false,"value"=>$profileDetail['CollegeCoach']['address_1'],"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>City:</label>
                    <span>
                        <?php echo $this->Form->input("city",array("label"=>false,"div"=>false,"value"=>$profileDetail['CollegeCoach']['city'],"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>State:</label>
                    <span>
                        <?php echo $this->Form->input("state",array("label"=>false,"div"=>false,"value"=>$profileDetail['CollegeCoach']['state'],"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>Zip Code:</label>
                    <span>
                        <?php echo $this->Form->input("zip",array("label"=>false,"div"=>false,"value"=>$profileDetail['CollegeCoach']['zip'],"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p style="margin-top:20px;">
                    <h2>Payment Details</h2>
                </p>

                <p>
                    <label>Credit Card Owner:</label>
                    <span>
                        <?php echo $this->Form->input("card_owner",array("label"=>false,"div"=>false,"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>Card Number:</label>
                    <span>
                        <?php echo $this->Form->input("card_number",array("label"=>false,"div"=>false,"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p>
                    <label>Card Expire Date:</label>
                    <span>
						<?php echo $this->Form->input("month",array("label"=>false,"div"=>false,"options"=>$this->Register->getSubcribeMonths(),"empty"=>"Select Month","required","style"=>"width:120px;"));?> / 
						<?php echo $this->Form->input("year",array("label"=>false,"div"=>false,"options"=>$this->Register->getSubcribeYears(),"empty"=>"Select Year","required","style"=>"width:120px;"));?>
                    </span>
                </p>
                
                <p>
                    <label>CVV:</label>
                    <span>
                        <?php echo $this->Form->input("cvv",array("label"=>false,"div"=>false,"required"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>

                <p style="margin-top:30px;">
                    <label>&nbsp;</label>

                    <?php echo $this->Form->input("email",array("label"=>false,"div"=>false,"type"=>"hidden","value"=>$profileDetail['CollegeCoach']['email']));?>

                    <span>
                        <?php echo $this->Form->submit("Update",array("type"=>"submit","div"=>false,"label"=>false));?>
						<?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"Profile","action"=>"index"))."'"));?>
                    </span>
                </p>
            <?php echo $this->Form->end();?>
        </div>
    </div>
</div>