<table align="center" border="0" align="center" width="60%">
	<tr height="20">
		<td valign="top" align="right" class="normalblack_12" width="30%">Category
		Name<font color="red"> *</font></td>
		<td valign="top" align="center" class="normalblack_12">: &nbsp;</td>
		<td valign="top" align="left" class="normalblack_12" colspan=2><input
			type="text" name="name" id="name" value="<?php echo $name?>"
			maxlength="30" style="width: 220px;" required></td>
	</tr>
	
	<tr height="20">
		<td valign="top" class="normalwhite_14" colspan=4 align="center">
		&nbsp;</td>
	</tr>
	
	<tr height="20">
		<td valign="top" align="right" class="normalblack_12" width="30%">Category
		Name(Initials)<font color="red"> *</font></td>
		<td valign="top" align="center" class="normalblack_12">: &nbsp;</td>
		<td valign="top" align="left" class="normalblack_12" colspan=2><input
			type="text" name="code" id="code"
			value="<?php echo $code?>" maxlength="30" style="width: 220px;" required></td>
	</tr>
	
	<tr height="20">
		<td valign="top" class="normalwhite_14" colspan=4 align="center">
		&nbsp;</td>
	</tr>

	<tr height="20">
		<td valign="top" align="right" class="normalblack_12" width="30%">Status<font
			color="red"></font></td>
		<td valign="top" align="center" class="normalblack_12">:</td>
		<td valign="top" align="left" class="normalblack_12"><select
			name="status" style="width: 220px; font-size: 12px;">
			<option value=1 <?php if($status==1){ echo "selected"; }?>>ACTIVE</option>
			<option value=0 <?php if($status==0){ echo "selected"; }?>>DE-ACTIVE</option>
		</select></td>
	</tr>
</table>
