<?php $s_image = "/img/spacer.gif";?>

<!--<table
	style="position: fixed; top: 0; left: 0; width: 100%; background-color: #FF0000">

	<tr>

		<td align="center"
			style="font-family: Georgia, 'Times New Roman', Times, serif; font-size: 18px; color: #FFFFFF;">Authorize.net
		payment is in test mode. <a href="make_live.php" class="test_mode">Make
		It Live</a></td>

	</tr>

</table>
-->


<table width="100%" border="0" cellpadding="1" cellspacing="0"
	bgcolor="#808080">

	<tr>

		<td>

		<table cellSpacing=0 cellPadding=0 bgColor=#CCCCCC border=0>

			<tr>

				<td width="15" align=right bgColor=#ffffff class=normalbrown>&nbsp;</td>

				<td width="180" height=22 align=left bgColor=#ffffff
					class=normalbrown><br>
				<span class="smallgrey_10"><?=date("l, jS M, Y");?></span> </strong>

				</td>

			</tr>

			<tr bgcolor="#FFFFFF">

				<td height="22" colspan="2" align=middle class=normalbrown></td>

			</tr>



			<!--MANAGE Atheletes BEGIN-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Athletes</td>

			</tr>
			
			<tr>
			
				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="/admin/Athlete/list" class="linkgrey_12"> <strong>View Athletes</strong></a>
				</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Athlete/stateList" class="linkgrey_12"><strong>View
				Athlete Stats</strong></a>
				</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Athlete/categoryAdd" class="linkgrey_12"> <strong>Add
				Stats Category</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Athlete/categoryList" class="linkgrey_12"> <strong>View
				Stats Category</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Athlete/classList" class="linkgrey_12"> <strong>View
				Class Category</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Athlete/classAdd" class="linkgrey_12"> <strong>Add Class
				Category</strong></a></td>

			</tr>

			<!--MANAGE Atheletes EMD -->

			<!--MANAGE Messageing BEGIN-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Messages System</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Mail/listMessage" class="linkgrey_12"> <strong>View Messages</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Mail/addBlockMessage" class="linkgrey_12"> <strong>Add Block
				Messages</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/Mail/listBlockMessage" class="linkgrey_12"> <strong>List
				Block Messages</strong></a></td>

			</tr>

			<!--MANAGE Sport BEGIN-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Sports</td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSportAdd.php" class="linkgrey_12"> <strong> Add Sports</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSportList.php" class="linkgrey_12"><strong>View Sports</strong></a></td>

			</tr>

			<!--MANAGE sport EMD -->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				HS / AAU Team</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSchoolAdd.php" class="linkgrey_12"> <strong> Add HS / AAU
				Team</strong></a></td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/HsAauTeam/schoolList" class="linkgrey_12"><strong>View HS / AAU
				Team</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="HsAauOtherList.php" class="linkgrey_12"><strong>View HS / AAU
				Team Other</strong></a></td>

			</tr>

			<!--MANAGE Coach BEGIN-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				HS / AAU Coach</td>

			</tr>

			



			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADCoachAdd.php" class="linkgrey_12"> <strong> Add HS / AAU
				Coach</strong></a></td>

			</tr>

			

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/HsAauCoach/coachList" class="linkgrey_12"><strong>View HS / AAU
				Coach</strong></a></td>

			</tr>

			<!--MANAGE coach EMD -->


			<!--MANAGE School BEGIN-->


			<!--MANAGE School EMD -->


			<!--MANAGE School BEGIN-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				College Coach</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/College/listCoach" class="linkgrey_12"><strong>View
				Colleges Coach</strong></a></td>

			</tr>

			<!--MANAGE School EMD -->


			<!--MANAGE TEAM BEGIN-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				College</td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/College/addCollege" class="linkgrey_12"> <strong> Add College </strong></a></td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/College/listCollege" class="linkgrey_12"><strong>View College </strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admin/College/listOther" class="linkgrey_12"><strong>View Other
				College List </strong></a></td>

			</tr>



			<!--MANAGE TEAM EMD -->

			<!--MANAGE Event BEGIN-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Event</td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADEvent.php" class="linkgrey_12"> <strong> Add Event</strong></a></td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADEventList.php" class="linkgrey_12"><strong>View Event</strong></a></td>

			</tr>

			<!-- START SPECIAL EVENT -->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Special Event</td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSpecialEvent.php" class="linkgrey_12"> <strong> Add Special
				Event</strong></a></td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSpecialEventList.php" class="linkgrey_12"><strong>View
				Special Event</strong></a></td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSpecialEventRegisterList.php" class="linkgrey_12"><strong>View
				Special Event Registration</strong></a></td>

			</tr>

			<!--transportation-->
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADTransportation.php" class="linkgrey_12"><strong>Add
				Transportation</strong></a></td>

			</tr>
		
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADTransportationManage.php" class="linkgrey_12"><strong>View
				Transportation</strong></a></td>

			</tr>

			<!--coupon-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Coupon</td>

			</tr>
	
			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADCoupon.php" class="linkgrey_12"> <strong> Add Coupon</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADCouponManage.php" class="linkgrey_12"> <strong> View Coupon</strong></a></td>

			</tr>



			<!--end coupon-->

			<!-- END SPECIAL EVENT -->



			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Subsription</td>

			</tr>


			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSubsription.php" class="linkgrey_12"> <strong> Add
				Subsription</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADSubsriptionList.php" class="linkgrey_12"><strong>View
				Subsription</strong></a></td>

			</tr>

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Static Page</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADPage.php" class="linkgrey_12"><strong>Add Static Page</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADPageList.php" class="linkgrey_12"><strong>View Static Page</strong></a></td>

				<tr>

					<td bgColor=#ffffff class="normalwhite_12" align=right><img
						src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

					<td height=22 bgColor=#ffffff class="normalwhite_12"><a
						href="ADHomeContentList.php" class="linkgrey_12"><strong>View Home
					Content</strong></a></td>

				</tr>

			</tr>

			<!--

Manage Home page Content-->

			<!--Mange Banner-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Banner</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADBanner.php" class="linkgrey_12"><strong>Add Banner</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADBannerList.php" class="linkgrey_12"><strong>View Banner</strong></a></td>

			</tr>

			<!--Mange Notes-->

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage
				Notes</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADNotes.php" class="linkgrey_12"><strong>Add Notes</strong></a></td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADNotesList.php" class="linkgrey_12"><strong>View Notes</strong></a></td>

			</tr>

			<tr>

				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Miscellaneous</td>

			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img
					src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="ADChangePassword.php" class="linkgrey_12"><strong>Change
				Password</strong></a></td>

			</tr>

			<tr bgColor=#ffffff class="normalwhite_12">
				<td>&nbsp;</td>
				<td>
				<hr size="1">
				</td>
			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12">&nbsp;</td>

				<td height=22 bgColor=#ffffff class="normalwhite_12"><a
					href="/admins/logout" class="linkgrey_12"><img src="/img/spacer.gif"
					border="0"></img><strong> Logout</strong></a></td>

			</tr>

			<!--MANAGE MICELLANEOUS EMD -->

		</table>

		</td>

	</tr>

</table>
