<TR>

    <TD 

    height=27 class="normalgrey_12">&nbsp;</TD>

  </TR>

  <tr>

    <td height="1" bgcolor="#CCCCCC"><img src="/img/spacer.gif" width="1" height="1"></td>

  </tr>

  <TR>

    <TD height=27 align="right" class="normalgrey_12"><br>Copyright &copy; <?php date("Y");?> <a href="<?echo $this->base?>" class="normalgrey_12"><?php echo ("College Prospect Network")?></a>, All Rights Reserved. &nbsp;&nbsp;<br>

      <span class="smallgrey_10">Powered By  <a href="http://www.synapse.co.in" class="smallgrey_10">Synapse Communications</a>&nbsp;&nbsp;&nbsp;</span>

    </TD>

  </TR>

  <TR>

    <TD align="right" class="normalgrey_12">&nbsp;</TD>

  </TR>

  <TR>

    <TD></TD></TR>

  <TR>

<TD></TD></TR>