<?php $s_image = $this->Html->webroot("/img/spacer.gif");?>

<table width="100%" border="0" cellpadding="1" cellspacing="0" 	bgcolor="#808080" style="width: 180px;">
	<tr>
		<td>
		  <table cellSpacing=0 cellPadding=0 bgColor=#CCCCCC border=0>
			<tr>
				<td width="15" align=right bgColor=#ffffff class=normalbrown>&nbsp;</td>

				<td width="180" height=22 align=left bgColor=#ffffff class=normalbrown><br>
						<span class="smallgrey_10"><?=date("l, jS M, Y");?></span> </strong>
				</td>
			</tr>
			<tr bgcolor="#FFFFFF">
				<td height="22" colspan="2" align=middle class=normalbrown></td>
			</tr>
			<!--MANAGE Atheletes BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Athletes</td>
			</tr>
			
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Athlete/list')?>" class="linkgrey_12"> <strong>View Athletes</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Athlete/stateList')?>" class="linkgrey_12"><strong>View Athlete Stats</strong></a>
				</td>
			</tr>

			<tr>

				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Athlete/categoryAdd')?>" class="linkgrey_12"> <strong>Add Stats Category</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Athlete/categoryList')?>" class="linkgrey_12"> <strong>View	Stats Category</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Athlete/classList')?>" class="linkgrey_12"> <strong>View Class Category</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Athlete/classAdd')?>" class="linkgrey_12"> <strong>Add Class Category</strong></a>
				</td>
			</tr>

			<!--MANAGE Atheletes EMD -->

			<!--MANAGE Messageing BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Messages System</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Mail/listMessage')?>" class="linkgrey_12"> <strong>View Messages</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Mail/addBlockMessage')?>" class="linkgrey_12"> <strong>Add Block Messages</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Mail/listBlockMessage')?>" class="linkgrey_12"> <strong>List Block Messages</strong></a>
				</td>
			</tr>

			<!--MANAGE Sport BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Sports</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Sport/addSport')?>" class="linkgrey_12"> <strong> Add Sports</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Sport/sportList')?>" class="linkgrey_12"><strong>View Sports</strong></a>
				</td>
			</tr>

			<!--MANAGE sport END -->
			
			
			<!--MANAGE Wingspan BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Wingspans</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Wingspan/addWingspan')?>" class="linkgrey_12"> <strong> Add Wingspan</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Wingspan/wingspanList')?>" class="linkgrey_12"><strong>View Wingspans</strong></a>
				</td>
			</tr>

			<!--MANAGE Wingspan END -->


                        <!--MANAGE ScoutReport BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Scout Report</td>
			</tr>

              		<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin')?>" class="linkgrey_12"> <strong> Search/Add Team ScoutReport</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/ScoutReport/addScoutreport')?>" class="linkgrey_12"> <strong> Add Scout Report</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/ScoutReport/scoutreportList')?>" class="linkgrey_12"><strong>View Scout Reports</strong></a>
				</td>
			</tr>

			<!--MANAGE Wingspan END -->


			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage HS / AAU Team</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/HsAauTeam/addSchool')?>" class="linkgrey_12"> <strong> Add HS / AAU Team</strong></a>
				</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/HsAauTeam/schoolList')?>" class="linkgrey_12"><strong>View HS / AAU Team</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/HsAauTeam/otherList')?>" class="linkgrey_12"><strong>View HS / AAU Team Other</strong></a>
				</td>
			</tr>

			<!--MANAGE Coach BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage HS / AAU Coach</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/HsAauCoach/addCoach')?>" class="linkgrey_12"> <strong> Add HS / AAU	Coach</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/HsAauCoach/coachList')?>" class="linkgrey_12"><strong>View HS / AAU Coach</strong></a>
				</td>
			</tr>

			<!--MANAGE coach EMD -->

			<!--MANAGE School BEGIN-->

			<!--MANAGE School EMD -->

			<!--MANAGE School BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage College Coach</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/College/listCoach')?>" class="linkgrey_12"><strong>View Colleges Coach</strong></a>
				</td>
			</tr>

			<!--MANAGE School EMD -->

			<!--MANAGE TEAM BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage College</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/College/addCollege')?>" class="linkgrey_12"> <strong> Add College </strong></a>
				</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a 	href="<?php echo $this->Html->url('/admin/College/listCollege')?>" class="linkgrey_12"><strong>View College </strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/College/listOther')?>" class="linkgrey_12"><strong>View Other College List </strong></a>
				</td>
			</tr>

			<!--MANAGE TEAM EMD -->

			<!--MANAGE Event BEGIN-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Event</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Event/addEvent')?>" class="linkgrey_12"> <strong> Add Event</strong></a>
				</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Event/eventList')?>" class="linkgrey_12"><strong>View Event</strong></a>
				</td>
			</tr>

			<!-- START SPECIAL EVENT -->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Special Event</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/SpecialEvent/addSpecialEvent')?>" class="linkgrey_12"> <strong> Add Special Event</strong></a>
				</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/SpecialEvent/specialEventList')?>" class="linkgrey_12"><strong>View Special Event</strong></a>
				</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/SpecialEvent/specialEventUserList')?>" class="linkgrey_12"><strong>View Special Event Registration</strong></a>
				</td>
			</tr>

			<!--transportation-->
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/TransportationDiscount/addTransportationDiscount')?>" class="linkgrey_12"><strong>Add Transportation</strong></a>
				</td>
			</tr>
		
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/TransportationDiscount/transportationDiscountList')?>" class="linkgrey_12"><strong>View Transportation</strong></a>
				</td>
			</tr>

			<!--coupon-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Coupon</td>
			</tr>
	
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Coupon/addCoupon')?>" class="linkgrey_12"> <strong> Add Coupon</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Coupon/couponList')?>" class="linkgrey_12"> <strong> View Coupon</strong></a>
				</td>
			</tr>

			<!--end coupon-->

			<!-- END SPECIAL EVENT -->
			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Subsription</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Subscription/addSubscription')?>" class="linkgrey_12"> <strong> Add Subsription</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Subscription/subscriptionList')?>" class="linkgrey_12"><strong>View Subsription</strong></a>
				</td>
			</tr>

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Static Page</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Page/addPage')?>" class="linkgrey_12"><strong>Add Static Page</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Page/pageList')?>" class="linkgrey_12"><strong>View Static Page</strong></a>
				</td>
			</tr>
			
			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a 	href="<?php echo $this->Html->url('/admin/Page/homeContentList')?>" class="linkgrey_12"><strong>View Home Content</strong></a>
				</td>
			</tr>

			<!--
				Manage Home page Content-->
			<!--Mange Banner-->

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Banner</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Banner/addBanner')?>" class="linkgrey_12"><strong>Add Banner</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Banner/bannerList')?>" class="linkgrey_12"><strong>View Banner</strong></a>
				</td>
			</tr>

			<!--Mange Notes-->
			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Manage Notes</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Note/addNote')?>" class="linkgrey_12"><strong>Add Notes</strong></a>
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admin/Note/noteList')?>" class="linkgrey_12"><strong>View Notes</strong></a>
				</td>
			</tr>

			<tr>
				<td align="center" bgColor=#808080 class=normalwhite_12>&nbsp;</td>

				<td height=22 align="left" bgColor=#808080 class=normalwhite_12>Miscellaneous</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12" align=right><img src="<?php echo $s_image?>" width="5" height="9" border="0"></img></td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admins/changePassword')?>" class="linkgrey_12"><strong>Change Password</strong></a>
				</td>
			</tr>

			<tr bgColor=#ffffff class="normalwhite_12">
				<td>&nbsp;</td>
				<td>
					<hr size="1">
				</td>
			</tr>

			<tr>
				<td bgColor=#ffffff class="normalwhite_12">&nbsp;</td>

				<td height=22 bgColor=#ffffff class="normalwhite_12">
					<a href="<?php echo $this->Html->url('/admins/logout')?>" class="linkgrey_12"><img src="<?php echo $s_image?>" border="0"></img><strong> Logout</strong></a>
				</td>
			</tr>
		</table>
	</td>
 </tr>
</table>