<table align="center" border="0" align="center" width="60%">
	<tr height="20">
		<td valign="top" align="right" class="normalblack_12" width="30%">Address
		<font color="red"> *</font></td>
		<td valign="top" align="center" class="normalblack_12">: &nbsp;</td>
		<td valign="top" align="left" class="normalblack_12" colspan=2>
			<textarea rows=5 cols=23 name="address_1" id="address_1"><?php echo $address?></textarea>
		</td>
	</tr>
	<tr height="20">
		<td valign="top" class="normalwhite_14" colspan=4 align="center">&nbsp;</td>
	</tr>
	<tr height="20">
		<td valign="top" align="right" class="normalblack_12" width="30%">City
		<font color="red"> *</font></td>
		<td valign="top" align="center" class="normalblack_12">: &nbsp;</td>
		<td valign="top" align="left" class="normalblack_12" colspan=2>
			<input type="text" name="city" id="city" value="<?php echo $city?>" style="width: 200px;">
		</td>
	</tr>
	<tr height="20">
		<td valign="top" class="normalwhite_14" colspan=4 align="center">&nbsp;</td>
	</tr>
	<tr height="20">
		<td valign="top" align="right" class="normalblack_12" width="30%">State<font color="red"> *</font></td>
		<td valign="top" align="center" class="normalblack_12">: &nbsp;</td>
		<td valign="top" align="left" class="normalblack_12" colspan=2>
			<input type="text" name="state" id="state" value="<?php echo $state?>" style="width: 200px;">
		</td>
	</tr>
	<tr height="20">
		<td valign="top" class="normalwhite_14" colspan=4 align="center">&nbsp;</td>
	</tr>
	<tr height="20">
		<td valign="top" align="right" class="normalblack_12" width="30%">Zip Code<font color="red"> *</font></td>
		<td valign="top" align="center" class="normalblack_12">: &nbsp;</td>
		<td valign="top" align="left" class="normalblack_12" colspan=2>
			<input type="text" name="zip" id="zip" value="<?php echo $zip?>" style="width: 200px;">
		</td>
	</tr>
	<tr height="20">
		<td valign="top" class="normalwhite_14" colspan=4 align="center">&nbsp;</td>
	</tr>
</table>