<div class="footer-bg">
   <div class="footer-inner">
          <a href="<?php echo $this->Html->url(array("controller"=>"Home","action"=>"index"));?>" title="Site Home">Site Home</a>&nbsp; | &nbsp;    
          <a href="<?php echo $this->Html->url(array("controller"=>"Home","action"=>"features"));?>" title="Features">Features</a>&nbsp; | &nbsp;  
          <a href="<?php echo $this->Html->url(array("controller"=>"Home","action"=>"privacyPolicy"));?>">Privacy Policy</a>&nbsp; | &nbsp; 	 
          <a href="<?php echo $this->Html->url(array("controller"=>"Home","action"=>"termsConditions"));?>" title="Terms & Conditions">Terms & Conditions</a>&nbsp; | &nbsp;   
          <a href="<?php echo $this->Html->url(array("controller"=>"Home","action"=>"refundPolicy"));?>" title="Refund Policy">Refund Policy</a> 
          
          <span style="padding-left:80px;font-size:11px;">Copyright © 2012 - College Prospect Network, Inc. All rights reserved.</span>
    </div>
</div>

<?php if($_SERVER['HTTP_HOST'] != 'localhost'):?>
	<script type="text/javascript">
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-28493822-1']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	</script>
<?php endif;?>	