<style>
 .paging-leftcol b.page a{
 	background: none repeat scroll 0 0 #eaeaea;
    color: #0061b7;
    font-size: 12px;
    font-weight: bold;
    margin: 0 1px;
    padding: 2px 5px;
    text-decoration: none;
  }
  
 .paging-leftcol b.page span {
    background: none repeat scroll 0 0 #0061b7;
    color: #fff;
    font-size: 12px;
    font-weight: bold;
    margin: 0 1px;
    padding: 2px 5px;
 }
</style>
<div class="paging">
	<span class="paging-leftcol">
		<?php echo $this->Paginator->first('First ', null, null, array('class' => 'first disabled' )); ?>
		
		<?php echo $this->Paginator->prev('« Previous ', null, null, array('class' => 'prev disabled' )); ?>
		
		<?php $defaults = array("tag" => "b", "class"=>"page" , "currentClass" => "page" , "currentTag" => "span", "separator" => "")?>
		<?php echo $this->Paginator->numbers($defaults);?>	
		
		<?php echo $this->Paginator->next(' Next »', null, null, array('class' => 'next disabled')); ?>
		<?php echo $this->Paginator->last(' Last', null, null, array('class' => 'last disabled ')); ?>
	</span>
	
	<span class="paging-rightcol">
		<?php echo "Showing Page ". $this->Paginator->counter(); ?>
	</span>
	
	<div class="clear"></div>
</div>