<div class="pagination">
	<!-- Shows the next and previous links -->
	<b class='fleft'> <?php echo $this->Paginator->prev('« Previous', null, null, array('class' => 'disabled' )); ?> </b>
	<b class='fleft'> <?php echo $this->Paginator->next(' Next »', null, null, array('class' => 'disabled ')); ?> </b>
	
	<ul class="fleft">
		<?php $defaults = array("tag" => "li" , 'separator' => '')?>
		<!-- Shows the page numbers -->
		<?php echo $this->Paginator->numbers($defaults);?>	
		<!-- prints X of Y, where X is current page and Y is number of pages -->
	</ul>
	
	<span class="fright status" > <?php echo "Showing Page ". $this->Paginator->counter(); ?> </span>
</div>