<div style="margin:50px 0 0 200px;position:absolute;">
  <table>
     <tr>
        <td>
		    <div id="fb-root"></div>
			<script>(function(d, s, id) {
			  var js, fjs = d.getElementsByTagName(s)[0];
			  if (d.getElementById(id)) return;
			  js = d.createElement(s); js.id = id;
			  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&appId=654677541293184&version=v2.0";
			  fjs.parentNode.insertBefore(js, fjs);
			}(document, 'script', 'facebook-jssdk'));</script>
			
			<div class="fb-like" data-href="" data-layout="button_count" data-action="like" data-show-faces="false" data-share="true"></div>
	    </td>
	    
	    <td>
	       <a class="twitter-share-button" width="" size="medium"  href="">Tweet</a>
		   <script type="text/javascript">
	   		  window.twttr=(function(d,s,id){var t,js,fjs=d.getElementsByTagName(s)[0];if(d.getElementById(id)){return}js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);return window.twttr||(t={_e:[],ready:function(f){t._e.push(f)}})}(document,"script","twitter-wjs"));
		   </script>
	    </td>
	
	    <td>
		   <script src="https://apis.google.com/js/platform.js" async defer></script>
		   <div class="g-plusone" data-size="medium"></div>
	
	 	   <div class="g-plus" data-action="share" data-annotation="bubble"></div>
	   </td>
	</tr>   	  
 </table>
</div>