<div class="cantener">
	<div class="register-main">
		<div class="registerPage">	  
		  	<h1>Network Requests</h1>
		  	<!-- Requests Pending My Approval -->
		  	<?php if (count($receiverRequests) > 0): ?>
		  	<div style="display: block; margin-bottom: 5px; text-align: right;"><?php echo count($receiverRequests); ?> Total Records</div>		  	
		  	<table cellpadding=2 cellspacing=1 width="100%" align="center">
				<thead>
					<tr>
						<th colspan="4" class="normalblack_12" style="text-align:center; background-color:#79B1D2; color:#FFFFFF;">Requests Pending My Approval</th>
					</tr>
					<tr style="background-color:#C9DFED;">
						<th width="38%" class="normalblack_12">User</th>
						<th width="19%" class="normalblack_12">Type</th>
						<th width="19%" class="normalblack_12">Status</th>
						<th width="24%" class="normalblack_12">Action</th>
					</tr>
				</thead>
				
				<tbody>
				<?php foreach ($receiverRequests as $receiverRequest):?>
					<tr>
						<td class="normalblack_12"><?php echo $this->Html->link($receiverRequest['Network']['username'], array('controller' => 'HsAauCoach', 'action' => 'view', $receiverRequest['Network']['sender_id'])); ?></td>				
						<td class="normalblack_12"><?php echo ucfirst(strtolower($receiverRequest['Network']['sender_type'])); ?></td>
						<td class="normalblack_12"><?php echo ucfirst(strtolower($receiverRequest['Network']['status'])); ?></td>
						<td class="normalblack_12">
						<?php if (strtolower($receiverRequest['Network']['status']) == 'pending'){?>								
									<?php if ($receiverRequest['Network']['sender_type'] == 'coach') {?>
											<?php if ('1' == '0'){?>
													<a href="javascript:rate_this_athlete('<?php echo $receiverRequest['Network']['id']; ?>',<?php echo $receiverRequest['Network']['sender_id']; ?>,'0')">Approve</a>
											<?php } else {?>													
													<?php echo $this->Html->link('Approve', array('action' => 'activeRequest', $receiverRequest['Network']['id']), array('escape' => false), "Are you sure you want to approve this user's Network Request?")?>
											<?php }?>
									<?php } else {?>											
											<?php echo $this->Html->link('Approve', array('action' => 'activeRequest', $receiverRequest['Network']['id']), array('escape' => false), "Are you sure you want to approve this user's Network Request?")?>
									<?php }?>
						<?php } ?>						
							&nbsp;/&nbsp;
							
							<?php echo $this->Html->link('Delete', array('action' => 'deleteRequest', $receiverRequest['Network']['id']), array('escape' => false), "Are you sure you want to delete this Network Request? This cannot be undone")?>
						</td>											
					</tr>
				<?php endforeach; ?>
				</tbody>			
			</table>
			<?php else:?>
				<div class="thankyoumessage">You have no pending network Requests.</div>
			<?php endif;?>
			<br>
			
			<!-- My Sent Requests -->
			<?php if (count($senderRequests) > 0): ?>
		  	<div style="display: block; margin-bottom: 5px; text-align: right;"><?php echo count($senderRequests); ?> Total Records</div>		  	
			<table cellpadding=2 cellspacing=1 width="100%" align="center">
				<thead>
					<tr>
						<th colspan="4" class="normalblack_12" style="text-align:center; background-color:#79B1D2; color:#FFFFFF;">My Sent Requests</th>
			 		</tr>			
					<tr style="background-color:#C9DFED;">
						<th width="38%" class="normalblack_12">User</th>
						<th width="19%" class="normalblack_12">Type</th>
					    <th width="19%" class="normalblack_12">Status</th>
						<th width="24%" class="normalblack_12">Action</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach ($senderRequests as $senderRequest):?>
					<tr>
						<td class="normalblack_12"><?php echo $this->Html->link($senderRequest['Network']['username'], array('controller' => 'HsAauCoach', 'action' => 'view', $senderRequest['Network']['sender_id'])); ?></td>				
						<td class="normalblack_12"><?php echo ucfirst(strtolower($senderRequest['Network']['receiver_type'])); ?></td>
						<td class="normalblack_12"><?php echo ucfirst(strtolower($senderRequest['Network']['status'])); ?></td>
						<td class="normalblack_12"><?php echo $this->Html->link('Delete', array('action' => 'deleteRequest', $senderRequest['Network']['id']), array('escape' => false), "Are you sure you want to delete this Network Request? This cannot be undone")?></td>																							
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>
			<?php else:?>
			<div class="thankyoumessage">You have not send any Requests.</div>
			<?php endif;?>	  
		</div>
	</div>
</div>	  
