<div class="cantener">
	<div class="register-main">
		<div class="registerPage">	  
		  	<h1>Network Requests</h1>
		  	<!-- Requests Pending My Approval -->
		  	<?php if (count($receivedRequests) > 0): ?>
		  	<div style="display: block; margin-bottom: 5px; text-align: right;"><?php echo count($receivedRequests); ?> Total Records</div>		  	
		  	<table cellpadding=2 cellspacing=1 width="100%" align="center">
				<thead>
					<tr>
						<th colspan="4" class="normalblack_12" style="text-align:center; background-color:#79B1D2; color:#FFFFFF;">Requests Pending My Approval</th>
					</tr>
					<tr style="background-color:#C9DFED;">
						<th width="38%" class="normalblack_12">User</th>
						<th width="19%" class="normalblack_12">Type</th>
						<th width="19%" class="normalblack_12">Status</th>
						<th width="24%" class="normalblack_12">Action</th>
					</tr>
				</thead>
				
				<tbody>
				<?php foreach ($receivedRequests as $receivedRequest):?>
					<tr>
						<?php if ($receivedRequest['Network']['sender_type'] == 'athlete') {	
								  $action = 'athleteProfile';
							  } elseif ($receivedRequest['Network']['sender_type'] == 'coach'){
							  	  $action = 'hsAauCoachProfile';							  	  							  
							  } elseif ($receivedRequest['Network']['sender_type'] == 'college'){
							  	  $action = 'collegeCoachProfile';							  	
							  } 							  
						?>
						<td class="normalblack_12"><?php echo $this->Html->link((isset($receivedRequest['Network']['username']) ? $receivedRequest['Network']['username'] : ''), array('controller' => 'Profile', 'action' => $action, $receivedRequest['Network']['sender_id'])); ?></td>				
						<td class="normalblack_12"><?php echo ucfirst(strtolower($receivedRequest['Network']['sender_type'])); ?></td>
						<td class="normalblack_12"><?php echo ucfirst(strtolower($receivedRequest['Network']['status'])); ?></td>
						<td class="normalblack_12">
						<?php if (strtolower($receivedRequest['Network']['status']) == 'pending'){?>								
									<?php if ($receivedRequest['Network']['sender_type'] == 'coach') {?>
											<?php if (isset($receivedRequest['Network']['count_rating']) && $receivedRequest['Network']['count_rating'] > 0){?>													
													<?php echo $this->Html->link('Approve', array('controller' => 'Athlete', 'action' => 'addRating', $receivedRequest['Network']['id'], $receivedRequest['Network']['sender_id'], 0))?>
											<?php } else {?>													
													<?php echo $this->Html->link('Approve', array('action' => 'activeRequest', $receivedRequest['Network']['id']), array('escape' => false), "Are you sure you want to approve this user's Network Request?")?>
											<?php }?>
									<?php } else {?>											
											<?php echo $this->Html->link('Approve', array('action' => 'activeRequest', $receivedRequest['Network']['id']), array('escape' => false), "Are you sure you want to approve this user's Network Request?")?>											
									<?php }?>
						<?php } ?>						
							&nbsp;/&nbsp;
							
							<?php echo $this->Html->link('Delete', array('action' => 'deleteRequest', $receivedRequest['Network']['id']), array('escape' => false), "Are you sure you want to delete this Network Request? This cannot be undone")?>
						</td>											
					</tr>
				<?php endforeach; ?>
				</tbody>			
			</table>
			<?php else:?>
				<div class="thankyoumessage">You have no pending network Requests.</div>
			<?php endif;?>
			<br>
			
			<!-- My Sent Requests -->
			<?php if (count($sentRequests) > 0): ?>
		  	<div style="display: block; margin-bottom: 5px; text-align: right;"><?php echo count($sentRequests); ?> Total Records</div>		  	
			<table cellpadding=2 cellspacing=1 width="100%" align="center">
				<thead>
					<tr>
						<th colspan="4" class="normalblack_12" style="text-align:center; background-color:#79B1D2; color:#FFFFFF;">My Sent Requests</th>
			 		</tr>			
					<tr style="background-color:#C9DFED;">
						<th width="38%" class="normalblack_12">User</th>
						<th width="19%" class="normalblack_12">Type</th>
					    <th width="19%" class="normalblack_12">Status</th>
						<th width="24%" class="normalblack_12">Action</th>
					</tr>
				</thead>
				<tbody>
				<?php foreach ($sentRequests as $sentRequest):?>
					<tr>
						<?php if ($sentRequest['Network']['receiver_type'] == 'athlete') {
								  $action = 'athleteProfile';	
							  } elseif ($sentRequest['Network']['receiver_type'] == 'coach'){
							  	  $action = 'hsAauCoachProfile';							  	
							  } elseif ($sentRequest['Network']['receiver_type'] == 'college'){
							  	  $action = 'collegeCoachProfile';							  	
							  } 							  
						?>
						<td class="normalblack_12"><?php echo $this->Html->link((isset($sentRequest['Network']['username']) ? $sentRequest['Network']['username'] : ''), array('controller' => 'Profile', 'action' => $action, $sentRequest['Network']['sender_id'])); ?></td>				
						<td class="normalblack_12"><?php echo ucfirst(strtolower($sentRequest['Network']['receiver_type'])); ?></td>
						<td class="normalblack_12"><?php echo ucfirst(strtolower($sentRequest['Network']['status'])); ?></td>
						<td class="normalblack_12"><?php echo $this->Html->link('Delete', array('action' => 'deleteRequest', $sentRequest['Network']['id']), array('escape' => false), "Are you sure you want to delete this Network Request? This cannot be undone")?></td>																							
					</tr>
				<?php endforeach; ?>
				</tbody>
			</table>			
			<?php else:?>
			<div class="thankyoumessage">You have not send any Requests.</div>
			<?php endif;?>
			<br />
			<p>
		       <label>&nbsp;</label>
		       <br />
		       <span>                                 
		           <input type="button" value="Back" style="width:130px;" onclick="window.location='<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"index"))?>';">				   
		       </span>
		     </p>	  
		</div>
	</div>
</div>	  
