<div class="cantener">
  <div class="register-main">
	 <div class="registerPage">
		    <h1>Add New Game Tape</h1>
		
			<?php echo $this->Form->create("AthleteVideo",array("url"=>array("controller"=>"Video","action"=>"addTape"),"type"=>"file"));?>
			
			<p>
				<label>Title:</label>
				<span>
					<?php echo $this->Form->input("title",array("div"=>false,"label"=>false,"required"));?>
				</span><font color="#0000ff">&nbsp;*</font>
			</p>
			
			<p>
				<label>Video File:</label>
				<span>
					<?php echo $this->Form->input("video_path",array("div"=>false,"label"=>false,"type"=>"file","required"));?>
				</span>
			</p>
			
			<p>
                <label>&nbsp;</label>
                <span>                                            
                    <font style="color:#777;">*Supported Video Types:</font>&nbsp; .mov .flv .avi .mp4 .wmv .mpeg .mpg<br />
                    <font style="color:#777;">*Max Filesize:</font>&nbsp; 200 MB (204,800KB)
                </span>                              
            </p>
            
			<p>
				<label>Status:</label>
				<span>
					<?php echo $this->Form->input("status",array("div"=>false,"label"=>false,"type"=>"select","options"=>array("1"=>"Active","0"=>"Inactive (hide on profile)"),"empty"=>"Select One","required"));?>
				</span>
			</p>
			
			<p>
				<label>Video Type:</label>
				<span>
					<?php echo $this->Form->input("video_type",array("div"=>false,"label"=>false,"type"=>"select","options"=>array("Original (not trimmed)"=>"Original (not trimmed)","Highlight Video"=>"Highlight Video"),"empty"=>"Select One","required"));?>
				</span>
			</p>
			
			<p>
			    <label>Agree to Terms:</label>
			    <span style="width:520px;line-height:16px;padding-top:8px;color:#666">In accordance with NCAA regulations, the video you upload may only be from a high school game. No videos from AAU, Select or Traveling team games are allowed. Posting one of these videos may result in the removal of your profile from the website.</span>
			</p>
			
			<p>
                 <label>&nbsp;</label>
                 <span style="color:#333;">
                     <input type="checkbox" required name="agree" value="agree_terms" style="width:20px;height:18px;margin-right:5px;position:relative;top:5px;border:0px;border-radius:0;padding:0;font-family:arial;"/>
                     Yes, I have read and agree to these terms.
                 </span>
            </p>
                                    
            <p class="loading" style="margin:0;padding-top:10px;padding-bottom:0px;line-height:18px;display:none;">
                  <label>&nbsp;</label>
                  <font style="font-size:12px;font-style:normal;color:#C12626;">*Upload may take several minutes depending on filesize, do not leave page until upload finishes.</font>
            </p>
                                    
			<p style="padding-top:15px;">
				<label>&nbsp;</label>
				<span>
					<?php echo $this->Form->submit("Submit",array("type"=>"submit","div"=>false,"label"=>false));?>
						
					<?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"Video","action"=>"index"))."'"));?>
				</span>
			</p>	
			
			<?php echo $this->Form->end();?>
	  </div>
  </div>
</div>