<?php echo $this->Html->script("/jwplayer/jwplayer.js");?>

<div class="cantener">
  <div class="register-main">
	 <div class="registerPage">
		<h1>Manage Game Tapes</h1>
		
		<?php if($AthleteVideos && count($AthleteVideos) > 0):?>
			  <?php foreach($AthleteVideos as $i => $AthleteVideo):?>
					<div class="videolist">
						<div class="video-container">
							<div id="jwplayer<?php echo $i;?>">Loading the Video Player ...</div>                                                            
                            <script type="text/javascript">
                                jwplayer("jwplayer<?php echo $i;?>").setup({
                                    flashplayer: "<?php echo Router::fullBaseUrl().$this->base; ?>/jwplayer/player.swf",
                                    file:  "<?php echo Router::fullBaseUrl().$this->base; ?>/video/<?php echo $AthleteVideo['AthleteVideo']['video_path'];?>",
                                    image: "<?php echo Router::fullBaseUrl().$this->base; ?>/video/<?php echo str_ireplace(".flv", ".jpg",$AthleteVideo['AthleteVideo']['video_path']);?>",
                                    skin:  "<?php echo Router::fullBaseUrl().$this->base; ?>/skins/stormtrooper/stormtrooper.zip",
                                    controlbar: "bottom",
                                    height: 300,
                                    width: 480
                                 });
                            </script>           
                        </div>
                        
						<div class="details-container">
							<div class="vidtitle"><span class="label">Title:</span><?php echo $AthleteVideo['AthleteVideo']['title'];?></div>
							
							<div class="vidtype"><span class="label">Type:</span><?php echo $AthleteVideo['AthleteVideo']['video_type'];?></div>    
							
							<div class="vidstatus">
								<span class="label">Status:</span>
								
								<?php if($AthleteVideo['AthleteVideo']['status']):?>
                                       <span style="color:#04990E;">Active - visible on profile</span>
                                <?php else:?>       
                                       <span style="color:#C40B0B;font-style:italic;">Inactive - hidden on profile</span>
                                <?php endif;?>       
                            </div>                                            
                            
                            <?php if($AthleteVideo['AthleteVideo']['video_type'] == "Highlight Video"):?>
                                     <div class="actions" style="margin-bottom:35px;">
                                         <a href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"editTape",$AthleteVideo['AthleteVideo']['id']));?>" class="editlink">
                                         	<?php echo $this->Html->image('b_edit.png',array("border"=>"0","title"=>"Edit Title & Status"));?>
                                         	Edit Title & Status
                                         </a>
                                     </div>
                                                                                   
                                     <div class="actions" style="text-align:left;">
                                     	  <a href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"deleteTape",$AthleteVideo['AthleteVideo']['id']));?>" class="deletelink">
                                         	<?php echo $this->Html->image('b_drop.png',array("border"=>"0","title"=>"Delete Video"));?>
                                         	Delete Highlight Video
                                         </a>
                                     </div>
                                                                
                            <?php else:?>
                            		 <div class="actions" style="margin-bottom:35px;">
                                         <a href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"editTape",$AthleteVideo['AthleteVideo']['id']));?>" class="editlink">
                                         	<?php echo $this->Html->image('b_edit.png',array("border"=>"0","title"=>"Edit Title & Status"));?>
                                         	Edit Title & Status
                                         </a>
                                     </div>
                                     
                                     <div class="actions" style="text-align:left;">
                                     	  <a href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"trimTape",$AthleteVideo['AthleteVideo']['id']));?>" class="deletelink">
                                         	<?php echo $this->Html->image('trim.png',array("border"=>"0","title"=>"Create Highlight"));?>
                                         	Create Highlight (trim this video)
                                         </a>
                                     </div>
                                     
                                      <div class="actions" style="text-align:left;">
                                     	  <a onclick="if(!confirm('Are you sure?')){ return false; }" href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"deleteTape",$AthleteVideo['AthleteVideo']['id']));?>" class="deletelink">
                                         	<?php echo $this->Html->image('b_drop.png',array("border"=>"0","title"=>"Delete Video"));?>
                                         	Delete this Video
                                         </a>
                                     </div>
                            <?php endif;?>
                        </div>                            
				  </div>
				  
				  <br clear="all" />
				  <br clear="all" />
		      <?php endforeach;?>
		      
		      <?php echo $this->Element('pagination');?>
		      
		<?php else:?>
				<div class="thankyoumessage" style="font-size:16px;font-weight:normal;">
					No Records Available, please &nbsp;
					<a href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"addTape"));?>" class="bluelargest">Add New Game Tape</a> 
				</div>
		<?php endif;?>
	 </div>
   </div>
</div>   	 