<script type="text/javascript">
  function updateEventDetails(resonse){
	  var resonse_arr = resonse.split("@@");
	  jQuery("#event_name").val(resonse_arr[0]);
	  jQuery("#location").html(resonse_arr[1]);
  }
</script>
<div class="cantener">
  <div class="register-main">
	 <div class="registerPage">
		<h1>Add Game / Event</h1>
		
		<?php if($this->Session->read('user_type') == 'athlete'):?>

			<?php echo $this->Form->create("Event",array("url"=>array("controller"=>"Game","action"=>"addStat"),"id"=>"addStat"));?>
				<p>
				   <label>Home Team:</label>
				   <span>
				   		<?php echo $this->Form->input("home_team",array("id"=>"home_team_id","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getHsAauSchools(),"empty"=>"Select One"));?>
				   </span>
				   <font color="#0000ff">*</font>
				</p>   
				
				<?php $this->Js->get("#home_team_id"); ?>
		    	<?php $this->Js->event('change',$this->Js->request(array('controller' => 'Game','action' => 'getEventDetails'),
		    					   array('async' => true,'data' => '$("#addStat").serialize()','dataExpression' => true ,
		    					   'complete' => "updateEventDetails(XMLHttpRequest.responseText)"
		               		 ))); 
		     	?>
		     	
		     	<p>
				   <label>Away Team:</label>
				   <span>
				   		<?php echo $this->Form->input("away_team",array("id"=>"away_team_id","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getHsAauSchools(),"empty"=>"Select One"));?>
				   </span>
				   <font color="#0000ff">*</font>
				</p>   
				
				<?php $this->Js->get("#away_team_id"); ?>
		    	<?php $this->Js->event('change',$this->Js->request(array('controller' => 'Game','action' => 'getEventDetails'),
		    					   array('async' => true,'data' => '$("#addStat").serialize()','dataExpression' => true ,
		    					   'complete' => "updateEventDetails(XMLHttpRequest.responseText)"
		               		 ))); 
		     	?>
		     	
				<p id="txtEvent">
					<label>Event Name:</label>
					<span>
						 <?php echo $this->Form->input("event_name",array("type"=>"text","div"=>false,"label"=>false,"required","id"=>"event_name"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>

				<p id="txtHint">
					<label>Location:</label>
					<span>
						<?php echo $this->Form->input("location",array("type"=>"textarea","div"=>false,"label"=>false,"required","id"=>"location"));?>
					</span>
					<font color="#0000ff">*</font>
				</p>

				<p>
				   <label>Event Details:</label>
				   <span>
				   	   <?php echo $this->Form->input("event_desc",array("type"=>"text","div"=>false,"label"=>false,"required"));?>
				   </span>
				</p>
				
				<p>
				   <label>Start Date:</label>
				   <span>
				   	   <?php echo $this->Form->input("end_date",array("type"=>"text","div"=>false,"label"=>false,"required"));?>
				   </span>
				</p>
				
				<p>
				   <label>End Date:</label>
				   <span>
				   	   <?php echo $this->Form->input("event_desc",array("type"=>"textarea","div"=>false,"label"=>false,"required"));?>
				   </span>
				</p>
									
				<p>
					<label>&nbsp;</label>
					<span>
						<?php echo $this->Form->submit("Submit",array("type"=>"submit","div"=>false,"label"=>false));?>
						
						<?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"User","action"=>"register"))."'"));?>
					</span>
				</p>
		  <?php echo $this->Form->end();?>	
		  
	  <?php else:?>
			<p><font color="#0000ff"><b>Access Denied</b></font></p>
			
	  <?php endif;?>	  	
	</div>
  </div>
</div>