<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!--Main Center Content BEGIN -->
								<table border="1" cellpadding="1" cellspacing="0" width="100%"
									bordercolor="#808080" style="border-collapse: collapse"
									class="tablePadd">
									<tr>
										<td align="center" class="normalwhite_14" colspan="11"
											bgcolor="#808080"><strong>Message Listing</strong></td>
									</tr>
									<tr>
										<td align='center' class='normalblack_12' colspan='11'
											height='30' valign='middle'><font color='red'></font></td>
									</tr>
									<tr>
										<td align='center' class='normalblack_12' colspan='11'
											height='30' valign='middle'></td>
									</tr>
									<tr>
										<td align='center' class='normalblack_12' colspan='11'
											height='30' valign='middle'>
											<form name="searchFrm" id="searchFrm" action="" method="POST"><input
												type="hidden" name="page" id="page" value="0"> <input
												type="text" name="content" id="content"
												value="<?php if(isset($content)) {echo $content;}else {?>Search By Content<?php } ?>">
												<input type="text" style="float: left; width: 200px;"
													class="input_L" id="startdate" name="startdate"
													autocomplete="off"
													value="<?php  if(isset($startdate)) {echo $startdate;}else{echo "Please Select Start Date";}?>">
												<img
													style="float: left; padding-right: 5px; margin-top: -2px;"
													alt="" src="/img/icon-calender.png" name="button2"
													id="button2"> 
													<script type="text/javascript">
														var cal = new Zapatec.Calendar.setup({			
														inputField     :    "startdate",     // id of the input field
														singleClick    :     true,     // require two clicks to submit
														ifFormat       :    '%Y-%m-%d',     // format of the input field
														showsTime      :     true,     // show time as well as date
														button         :    "button2"  // trigger button 
														});							
													</script> 
												<input type="text" style="float: left; width: 200px;"
													class="input_L" id="enddate" name="enddate"
													autocomplete="off"
													value="<?php  if(isset($enddate)) {echo $enddate;}else{echo "Please Select End Date";}?>">
		
												<img
													style="float: left; padding-right: 5px; margin-top: -2px;"
													alt="" src="/img/icon-calender.png" name="button3"
													id="button3"> 
													
													<script type="text/javascript">
														var cal = new Zapatec.Calendar.setup({
														inputField     :    "enddate",     // id of the input field
														singleClick    :     true,     // require two clicks to submit
														ifFormat       :    '%Y-%m-%d',     // format of the input field
														showsTime      :     true,     // show time as well as date
														button         :    "button3"  // trigger button 
														});
									
									
													</script> 
													
													<input type="submit" name="search" id="search"
															value="Search">
												</form>
											</td>
									</tr>
									<form name="frmListMessage" action="" method="post" onsubmit=""><?php if(sizeof($mails)>0){ ?>
									<tr>
										<td align="left" style="padding-left: 7px;" colspan="11"><input
											type="checkbox" id="check_all" name="check_all" value=""
											onclick="javascript:checkAll();"> <b>Check All</b>&nbsp;
										&nbsp;<input type="button" name="delete"
											value="Delete Selected" onclick="return deleteSelectedMessages();"></td>
									</tr>
									<tr>
										<td align="center" class="normalblack_12" width="4%">&nbsp;</td>
										<td align="left" class="normalblack_12" width="8%">&nbsp;<strong>S.No.</strong></td>
										<td align="left" class="normalblack_12" width="15%">&nbsp;<strong>UserTo</strong></td>
										<td align="left" class="normalblack_12" width="15%">&nbsp;<strong>UserFrom</strong></td>
										<td align="left" class="normalblack_12" width="15%">&nbsp;<strong>Subject</strong></td>
										<td align="left" class="normalblack_12" width="10%">&nbsp;<strong>SentDate</strong></td>
										<td class="normalblack_12" width="5%" align="center"><strong>Visible</strong></td>
										<td class="normalblack_12" width="5%" align="center"><strong>View Message</strong></td>										
									</tr>

									<?php $i = 1;?> 
									<?php foreach($mails as $mail) : ?>
										<tr>
											<td align="center" class="normalblack_12">&nbsp; <input
												type="checkbox" id="check_delete[]" name="check_delete[]"
												value="<?php echo $mail['Mail']['id']?>" onclick="return checkItSelf();"></td>
											<td align="left" class="normalblack_12">&nbsp;<?php echo ($i + $limit * ($this->Paginator->current() - 1));?></td>
											<td align="left" class="normalblack_12"><?php echo ucfirst(wordwrap($mail['Mail']['receiver'],25,"\n",true)).'&nbsp;('.$mail['Mail']['usertype_to'].')'?>
											</td>
											<td align="left" class="normalblack_12"><?php echo ucfirst(wordwrap($mail['Mail']['sender'],24,"\n",true)).'&nbsp;('.$mail['Mail']['usertype_from'].')'?>
											</td>
											<td align="left" class="normalblack_12"><?php echo wordwrap($mail['Mail']['subject'],50,"\n",true)?>
											</td>
											<td align="left" class="normalblack_12"><?php echo wordwrap($mail['Mail']['sent_date'],25,"\n",true)?>
											</td>
											<td align="center" class="normalblack_12">			
											<?php if ($mail['Mail']['visible'] == '0') {?>
											
												<?php echo $this->Html->link($this->Html->image('/img/red-point.gif'), array('controller' => 'Mail', 'action' => 'activeMessage', $mail['Mail']['id']), array('escape' => false, 'title' => 'Active'), "Are you sure to active this Message?")?>
											
											<?php } else {?>													
													<?php echo $this->Html->link($this->Html->image('/img/green-point.gif'), array('controller' => 'Mail', 'action' => 'dectiveMessage', $mail['Mail']['id']), array('escape' => false, 'title' => 'Deactive'), "Are you sure to deactive this Message?")?>
											<?php }?>
											</td>							
											<td class="normalblack_12" align="center"><a
												href="javascript:ShowDetails('<?php echo '/admin/Mail/messageDetails/'.$mail['Mail']['id'] ?>','Message Details')">View</a>
											</td>									
										</tr>
										<?php $i++;?>
									<?php endforeach;?> <?php } else { ?>
									<tr>
										<td align="center" class="normalblack_12" colspan="10"
											height="30"><font color="red">No Records Available.</font></td>
									</tr>
									<?php } ?></form>
								</table>
								<!--Main Center Content END --> <?php echo $this->element('pagination');?>

								</td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>
