<div class="cantener">
	<div class="register-main">
		<?php echo $this->Form->create("CollegeCoach",array("url"=>array("controller"=>"User","action"=>"registerCollegeCoach")));?>
		
			<h1>Athlete Registration</h1>
			<span class="msg"><font color="#0000ff">&nbsp;*</font> Fields are Mandatory.</span>
			<div class="registerPage">
				<p>
					<label>User Name:</label>
					<span>
						<?php echo $this->Form->input("username",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Password:</label>
					<span>
						<?php echo $this->Form->input("password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Confirm Password:</label>
					<span>
						<?php echo $this->Form->input("confirm_password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<hr class="line" />
				
				<p>
					<label>First Name:</label>
					<span>
						<?php echo $this->Form->input("firstname",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Last Name:</label>
					<span>
						<?php echo $this->Form->input("lastname",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Email:</label>
					<span>
						<?php echo $this->Form->input("email",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Alternate Email:</label>
					<span>
						<?php echo $this->Form->input("email2",array("div"=>false,"label"=>false));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Phone:</label>
					<span>
						<?php echo $this->Form->input("phone",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Alternate Phone:</label>
					<span>
						<?php echo $this->Form->input("phone2",array("div"=>false,"label"=>false));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<hr class="line" />
				
				<p>
				   <label>College:</label>
				   <span>
				   		<?php echo $this->Form->input("college_id",array("id"=>"college_id","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getColleges(),"empty"=>"Select One"));?>
				   </span>
				   <font color="#0000ff">*</font>
				</p>   
				<?php $this->Js->get("#college_id"); ?>
		    	<?php $this->Js->event('change',$this->Js->request(array('controller' => 'User','action' => 'getCollegeInfo'),
		    					   array('async' => true,'update' => '#school_address','data' => '$("#college_id").serialize()','dataExpression' => true
		               		 ))); 
		     	?>
		     	
		     	<div id="school_address">
		     	
		     	
		     	</div>
		     	
				<p>
					<label>Sport:</label>
					<span>
						<?php echo $this->Form->input("sport_id",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getSports(),"empty"=>"Select One"));?>
					</span>
				</p>	
				<p>
					<label>Sport Divison:</label>
					<span>
						<?php echo $this->Form->input("division",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getDivisions(),"empty"=>"Select One"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Job Position:</label>
					<span>
						<?php echo $this->Form->input("position",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				
				<hr class="line" />
				<p>
				   <label>Enter your Security Question:</label>
                   <span><?php echo $this->Form->input("question",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                   <font color="#0000ff">&nbsp;*</font>
			    </p>

				<p>
                   <label>Enter your Security Answer:</label>
                   <span><?php echo $this->Form->input("answer",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                   <font color="#0000ff">&nbsp;*</font>
			    </p>
				
				<p>
					<label>&nbsp;</label>
					<span>
						<?php echo $this->Form->submit("Register",array("type"=>"submit","div"=>false,"label"=>false));?>
						
						<?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"User","action"=>"register"))."'"));?>
					</span>
				</p>
			</div>
		
		<?php echo $this->Form->end();?>
	</div>
</div>	