<script type="text/javascript">
    jQuery(document).ready(function(){
        jQuery('#username').change(function(){
            username = jQuery('#username').val();
            username = username.toLowerCase();
            username = username.replace(/[^\w\s]/gi,"");
            jQuery('#username').val(username);

            requestUrl = '<?php echo Router::url(array("controller"=>"User","action"=>"checkUsername"))?>';
            jQuery.ajax({
                url: requestUrl+"/"+username+"/Athlete" ,
                success: function(res){
                    if(res == 'Yes'){
                        jQuery("#errorMessage").html("Username is not available.");
                    }
                    else{
                        jQuery("#errorMessage").html("Username is available.");
                    }
                }
            });
        });
    });
</script>
<div class="cantener">
    <div class="register-main">
        <?php echo $this->Form->create("Athlete",array("url"=>array("controller"=>"User","action"=>"registerAthlete")));?>

        <h1>Athlete Registration</h1>
        <span class="msg"><font color="#0000ff">&nbsp;*</font> Fields are Mandatory.</span>
        <div class="registerPage">
            <p>
                <label>User Name:</label>
                <span>
                    <?php echo $this->Form->input("username",array("div"=>false,"label"=>false,"required"=>"true",'id'=>'username'));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
                <b id="errorMessage"></b>
            </p>
            <p>
                <label>Password:</label>
                <span>
                    <?php echo $this->Form->input("password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <p>
                <label>Confirm Password:</label>
                <span>
                    <?php echo $this->Form->input("confirm_password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <hr class="line" />

            <p>
                <label>First Name:</label>
                <span>
                    <?php echo $this->Form->input("firstname",array("div"=>false,"label"=>false,"required"=>"true"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <p>
                <label>Last Name:</label>
                <span>
                    <?php echo $this->Form->input("lastname",array("div"=>false,"label"=>false,"required"=>"true"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <p>
                <label>Email:</label>
                <span>
                    <?php echo $this->Form->input("email",array("div"=>false,"label"=>false,"required"=>"true"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <p>
                <label>Height:</label>
                <span>
                    <?php echo $this->Form->input("height",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getHeights(),"empty"=>"Select One"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <p>
                <label>Weight:</label>
                <span>
                    <?php echo $this->Form->input("weight",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getWeights(),"empty"=>"Select One"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <hr class="line" />

            <p>
                <label>State (for your HS/AAU Team):</label>
                <span>
                    <?php echo $this->Form->input("state_id",array("id"=>"state_id","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getStates(),"empty"=>"Select One"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>

            <?php $this->Js->get("#state_id"); ?>
            <?php
            //                        $this->Js->event('change',$this->Js->request(array('controller' => 'User','action' => 'getHsAauSchools'),
            //		    					   array('async' => true,'update' => '#schools','data' => '$("#state_id").serialize()','dataExpression' => true
            //		               		 )));
            ?>

            <div id="schools">
                <p>
                    <label>HS School/AAU Team :</label>
                    <span>
                        <?php echo $this->Form->input("team",array("div"=>false,"label"=>false,"required"=>"true"));?>
                    </span>
                    <font color="#0000ff">&nbsp;*</font>
                </p>
            </div>

            <div id="school_address">


            </div>

            <p>
                <label>Sport:</label>
                <span>
                    <?php echo $this->Form->input("sport_id",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getSports(),"empty"=>"Select One"));?>
                </span>
            </p>
            <p>
                <label>Jersey Number:</label>
                <span>
                    <?php echo $this->Form->input("jersey_number",array("div"=>false,"label"=>false,"required"=>"true"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <p>
                <label>Graduating Class:</label>
                <span>
                    <?php echo $this->Form->input("class",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getClasses(),"empty"=>"Select One"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>
            <p>
                <label>Intended Major:</label>
                <span>
                    <?php echo $this->Form->input("intended_major",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getIntendedMajor(),"empty"=>"Select One"));?>
                </span>
                <font color="#0000ff">&nbsp;*</font>
            </p>

            <hr class="line" />
            <p>
                <label>Enter your Security Question:</label>
                <span><?php echo $this->Form->input("question",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                <font color="#0000ff">&nbsp;*</font>
            </p>

            <p>
                <label>Enter your Security Answer:</label>
                <span><?php echo $this->Form->input("answer",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                <font color="#0000ff">&nbsp;*</font>
            </p>

            <p align="center">
                <img src="<?php echo $this->Html->webroot($captcha_url); ?>" alt="captcha">
            </p>

            <p>
                <label>Code:</label>
                <span>
                    <?php echo $this->Form->input('code',array("div"=>false,'label'=>false,"required",'type'=>'text','value'=>'')); ?>
                    <font color="#0000ff">*</font>
                </span>
            </p>

            <p>
                <label>&nbsp;</label>
                <span>
                    <?php echo $this->Form->submit("Register",array("type"=>"submit","div"=>false,"label"=>false));?>

                    <?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"User","action"=>"register"))."'"));?>
                </span>
            </p>
        </div>

        <?php echo $this->Form->end();?>
    </div>
</div>
<style>
    .ui-autocomplete {
        max-height: 100px;
        overflow-y: auto;
        /* prevent horizontal scrollbar */
        overflow-x: hidden;
    }
    /* IE 6 doesn't support max-height
     * we use height instead, but this forces the menu to always be this tall
    */
    * html .ui-autocomplete {
        height: 100px;
    }
    .ui-autocomplete-loading {
        background: white url("<?php echo $this->Html->url('/img/loading.gif')?>") right center no-repeat;
    }
</style>
<script>
    $(function() {
        var url = '<?php echo $this->Html->url('autoCompleteHS'); ?>' ;
        $("#AthleteTeam").autocomplete({
            source: function( request, response ) {
                if($("#state_id").val() != ''){
                    $.ajax({
                        url: url ,
                        dataType: "json",
                        data: {
                            q: request.term ,
                            state_id : $("#state_id").val()
                        },
                        success: function( data ) {
                            response( data );
                        }
                    });
                }
            },
            minLength: 1,
            select: function( event, ui ) {
                if(ui.item){
                    var url1 = '<?php echo $this->Html->url('getAddressInfoHs'); ?>' ;
                    $.ajax({
                        url: url1 ,
                        data: {
                            schoolname: ui.item.label,
                            state_id : $("#state_id").val()
                        },
                        success: function(data) {
                            $("#school_address").html(data);
                        }
                    });
                }
            }

        });
    });
</script>