<script type="text/javascript">
   jQuery(document).ready(function(){
	   jQuery('#username').change(function(){
		     username = jQuery('#username').val();
		     username = username.toLowerCase();
		     username = username.replace(/[^\w\s]/gi,""); 
		     jQuery('#username').val(username);

		     requestUrl = '<?php echo Router::url(array("controller"=>"User","action"=>"checkUsername"))?>';
		     jQuery.ajax({
			     url: requestUrl+"/"+username+"/CollegeCoach" ,
			     success: function(res){
			    	 if(res == 'Yes'){
			     		 jQuery("#errorMessage").html("Username is not available.");
				     }
			     	 else{
				     	 jQuery("#errorMessage").html("Username is available.");
				     }
			     }
			 });
	   });
   });
</script>
<div class="cantener">
	<div class="register-main">
		<?php echo $this->Form->create("CollegeCoach",array("url"=>array("controller"=>"User","action"=>"registerCollegeCoach")));?>
		
			<h1>Athlete Registration</h1>
			<span class="msg"><font color="#0000ff">&nbsp;*</font> Fields are Mandatory.</span>
			<div class="registerPage">
				<p>
					<label>User Name:</label>
					<span>
						<?php echo $this->Form->input("username",array("div"=>false,"label"=>false,"required"=>"true",'id'=>'username'));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
					<b id="errorMessage"></b>
				</p>
				<p>
					<label>Password:</label>
					<span>
						<?php echo $this->Form->input("password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Confirm Password:</label>
					<span>
						<?php echo $this->Form->input("confirm_password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<hr class="line" />
				
				<p>
					<label>First Name:</label>
					<span>
						<?php echo $this->Form->input("firstname",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Last Name:</label>
					<span>
						<?php echo $this->Form->input("lastname",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Email:</label>
					<span>
						<?php echo $this->Form->input("email",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Alternate Email:</label>
					<span>
						<?php echo $this->Form->input("email2",array("div"=>false,"label"=>false));?>
					</span>
				</p>
				<p>
					<label>Phone:</label>
					<span>
						<?php echo $this->Form->input("phone",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Alternate Phone:</label>
					<span>
						<?php echo $this->Form->input("phone2",array("div"=>false,"label"=>false));?>
					</span>
				</p>
				<hr class="line" />
				
				<p>
					<label>State:</label>
					<span>
						<?php echo $this->Form->input("state_id",array("id"=>"state_id","div"=>false,"selected"=>@$state_id,"label"=>false,"required"=>"true","options"=>$this->Register->getStates(),"empty"=>"Select One"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				
				<?php $this->Js->get("#state_id"); ?>
		    	<?php
//                        $this->Js->event('change',$this->Js->request(array('controller' => 'User','action' => 'getColleges'),
//		    					   array('async' => true,'update' => '#schools','data' => '$("#state_id").serialize()','dataExpression' => true
//		               		 )));
		     	?>
				
				<div id="schools">
					<p>
					   <label>College:</label>
					   <span>
					   		<?php echo $this->Form->input("CollegeCoach.college",array("id"=>"college","div"=>false,"label"=>false,"required"=>"true"));?>
					   </span>
					   <font color="#0000ff">*</font>
					</p>
                                            <!--<p>
					   <label>College:</label>
					   <span>
					   		<?php echo $this->Form->input("CollegeCoach.college_id",array("id"=>"college_id","div"=>false,"label"=>false,"required"=>"true","options"=>@$colleges,"empty"=>"Select One"));?>
					   </span>
					   <font color="#0000ff">*</font>
					</p>  -->
                               </div>
		     	
		     	<div id="school_address">
		     		<?php if(@$college_id == 'Other'):?>
						<p>
							<label>College Name:</label>
							<span>
								<?php echo $this->Form->input("College.name",array("div"=>false,"label"=>false,"required"=>"true",'pattern=".{3,}"','title'=>'Please enter correct name.'));?>
							</span>
						</p>
					<?php endif;?>
					
					<p>
						<label>Address:</label>
						<span>
							<?php echo $this->Form->input("College.address",array("div"=>false,"label"=>false,"required"=>"true","value"=>@$CollegeDetail['College']['address_1'],'pattern=".{3,}"','title'=>'Please enter correct address.'));?>
						</span>
					</p>
					
					<p>
						<label>City:</label>
						<span>
							<?php echo $this->Form->input("College.city",array("div"=>false,"label"=>false,"required"=>"true","value"=>@$CollegeDetail['College']['city'],'pattern=".{3,}"','title'=>'Please enter correct city.'));?>
						</span>
					</p>
					
					<p style="display:none;">
						<label>State:</label>
						<span>
							<?php echo $this->Form->input("College.state",array("div"=>false,"label"=>false,"required"=>"true","selected"=>@$CollegeDetail['College']['state'],"options"=>$this->Register->getStates(),"empty"=>"Select One"));?>
						</span>
					</p>
					
					<p>
						<label>Zip Code:</label>
						<span>
							<?php echo $this->Form->input("College.zip",array("div"=>false,"label"=>false,"required"=>"true","value"=>@$CollegeDetail['College']['zip']));?>
						</span>
					</p>
		     	</div>
		     	
				<p>
					<label>Sport:</label>
					<span>
						<?php echo $this->Form->input("sport_id",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getSports(),"empty"=>"Select One"));?>
					</span>
				</p>	
				<p>
					<label>Sport Divison:</label>
					<span>
						<?php echo $this->Form->input("division",array("div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getDivisions(),"empty"=>"Select One"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Job Position:</label>
					<span>
						<?php echo $this->Form->input("position",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				
				<hr class="line" />
				<p>
				   <label>Enter your Security Question:</label>
                   <span><?php echo $this->Form->input("question",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                   <font color="#0000ff">&nbsp;*</font>
			    </p>

				<p>
                   <label>Enter your Security Answer:</label>
                   <span><?php echo $this->Form->input("answer",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                   <font color="#0000ff">&nbsp;*</font>
			    </p>
			    
			     <p align="center">
			   		<img src="<?php echo $this->Html->webroot($captcha_url); ?>" alt="captcha">
			     </p>
			   
			     <p>
			   	    <label>Code:</label>
			   	    <span>
			   	  		<?php echo $this->Form->input('code',array("div"=>false,'label'=>false,"required",'type'=>'text','value'=>'')); ?>
			   	  		<font color="#0000ff">*</font>
			   	    </span>
			     </p>
				
				<p>
					<label>&nbsp;</label>
					<span>
						<?php echo $this->Form->submit("Register",array("type"=>"submit","div"=>false,"label"=>false));?>
						
						<?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"User","action"=>"register"))."'"));?>
					</span>
				</p>
			</div>
		
		<?php echo $this->Form->end();?>
	</div>
</div>

<style>
    .ui-autocomplete {
        max-height: 100px;
        overflow-y: auto;
        /* prevent horizontal scrollbar */
        overflow-x: hidden;
    }
    /* IE 6 doesn't support max-height
     * we use height instead, but this forces the menu to always be this tall
    */
    * html .ui-autocomplete {
        height: 100px;
    }
    .ui-autocomplete-loading {
        background: white url("<?php echo $this->Html->url('/img/loading.gif')?>") right center no-repeat;
    }
</style>
<script>
    $(function() {
        $("#state_id").change(function(){
          $( "#college" ).val('');
          $("#CollegeAddress").val('');
          $("#CollegeCity").val('');
          $("#CollegeZip").val('');
      });
        var url = '<?php echo $this->Html->url('autoCompleteCollege'); ?>' ;
        $("#college").autocomplete({
            source: function( request, response ) {
                if($("#state_id").val() != ''){
                    $.ajax({
                        url: url ,
                        dataType: "json",
                        data: {
                            q: request.term ,
                            state_id : $("#state_id").val()
                        },
                        success: function( data ) {
                            response( data );
                        }
                    });
                }
            },
            minLength: 1,
            select: function( event, ui ) {
                if(ui.item){
                    var url1 = '<?php echo $this->Html->url('getCollegeInfoHtml'); ?>' ;
                    $.ajax({
                        url: url1 ,
                        data: {
                            collegename: ui.item.label,
                            state_id : $("#state_id").val()
                        },
                        success: function(data) {
                            $("#school_address").html(data);
                        }
                    });
                }
            }

        });
    });
</script>