<?php $total = count($this->Register->getSports());?>
<script type="text/javascript">
   var position = 0;
   
   function addRow(){
	   position = parseInt(position);
	   if(position > '<?php echo $total - 2?>'){
		   //return;
	   }
	   position++;
	   var row = "<div id='sport_position_"+position+"'><p>"+
		            "<label>Sport: "+ (position + 1) +"</label>"+
					"<span>"+
						"<select id='HsAauCoachSportId' required='required' name='data[HsAauCoach][sport_id]["+position+"]'>"+
							"<option value=''>Select One</option>"+
							"<option value='12'>Basketball - Womens</option>"+
							"<option value='11'>Basketball - Mens</option>"+
							"<option value='10'>Football</option>"+
						"</select>"+
					"</span>"+
					"<font color='#0000ff'>*</font>"+
				 "</p>"+	
				 "<p>"+
					"<label>Position: "+ (position + 1) +"</label>"+
					"<span>"+
						"<input type='text' id='HsAauCoachPosition' required='required' name='data[HsAauCoach][position]["+position+"]'>"+
					"</span>"+
					"<font color='#0000ff'>&nbsp;*</font>"+
				 "</p></div>";
		jQuery("#sportTable").append(row);			
		jQuery("#remfield").show();		 
   }

   function removeRow(){
	   position = parseInt(position);

	   if(position <= 1){
		   jQuery("#remfield").hide();	
	   }
	   
	   if(position < 1){
		   return;
	   }

	   jQuery("#sport_position_"+position).remove();
	   position--;
   }

   jQuery(document).ready(function(){
	   jQuery('#username').change(function(){
		     username = jQuery('#username').val();
		     username = username.toLowerCase();
		     username = username.replace(/[^\w\s]/gi,""); 
		     jQuery('#username').val(username);

		     requestUrl = '<?php echo Router::url(array("controller"=>"User","action"=>"checkUsername"))?>';
		     jQuery.ajax({
			     url: requestUrl+"/"+username+"/HsAauCoach" ,
			     success: function(res){
			     	 if(res == 'Yes'){
			     		 jQuery("#errorMessage").html("Username is not available.");
				     }
			     	 else{
				     	 jQuery("#errorMessage").html("Username is available.");
				     }
			     }
			 });
	   });
   });
</script>
<div class="cantener">
	<div class="register-main">
		<?php echo $this->Form->create("HsAauCoach",array("url"=>array("controller"=>"User","action"=>"registerHSCoach")));?>
		
			<h1>High School / AAU Coach Registration</h1>
			<span class="msg"><font color="#0000ff">&nbsp;*</font> Fields are Mandatory.</span>
			<div class="registerPage">
				<p>
					<label>User Name:</label>
					<span>
						<?php echo $this->Form->input("username",array("div"=>false,"label"=>false,"required"=>"true",'id'=>'username'));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
					<b id="errorMessage"></b>
				</p>
				<p>
					<label>Password:</label>
					<span>
						<?php echo $this->Form->input("password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Confirm Password:</label>
					<span>
						<?php echo $this->Form->input("confirm_password",array("div"=>false,"label"=>false,"required"=>"true","type"=>"password"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<hr class="line" />
				
				<p>
					<label>First Name:</label>
					<span>
						<?php echo $this->Form->input("firstname",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Last Name:</label>
					<span>
						<?php echo $this->Form->input("lastname",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Email:</label>
					<span>
						<?php echo $this->Form->input("email",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Alternate Email:</label>
					<span>
						<?php echo $this->Form->input("email2",array("div"=>false,"label"=>false));?>
					</span>
				</p>
				<p>
					<label>Phone:</label>
					<span>
						<?php echo $this->Form->input("phone",array("div"=>false,"label"=>false,"required"=>"true"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				<p>
					<label>Alternate Phone:</label>
					<span>
						<?php echo $this->Form->input("phone2",array("div"=>false,"label"=>false));?>
					</span>
				</p>
				<hr class="line" />
				
				<p>
					<label>State (for your HS/AAU Team):</label>
					<span>
						<?php echo $this->Form->input("state_id",array("id"=>"state_id","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getStates(),"empty"=>"Select One"));?>
					</span>
					<font color="#0000ff">&nbsp;*</font>
				</p>
				
				<?php $this->Js->get("#state_id"); ?>
		    	<?php $this->Js->event('change',$this->Js->request(array('controller' => 'User','action' => 'getHsAauSchools'),
		    					   array('async' => true,'update' => '#schools','data' => '$("#state_id").serialize()','dataExpression' => true
		               		 ))); 
		     	?>
				
				<div id="schools">
				
		     	</div>
		     	
		     	<div id="school_address">
		     	
		     	
		     	</div>
				
		     	<div id="sportTable">
		     		<div id='sport_position_0'>
						<p>
							<label>Sport 1:</label>
							<span>
								<?php echo $this->Form->input("sport_id",array("name"=>"data[HsAauCoach][sport_id][0]","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getSports(),"empty"=>"Select One"));?>
							</span>
							<font color="#0000ff">*</font>
						</p>	
						<p>
							<label>Position 1:</label>
							<span>
								<?php echo $this->Form->input("position",array("name"=>"data[HsAauCoach][position][0]","div"=>false,"label"=>false,"required"=>"true"));?>
							</span>
							<font color="#0000ff">&nbsp;*</font>
						</p>
					</div>	
				</div>
				
				<p style="margin-bottom:3px;padding-bottom:0;" class="lineheightnormal">
					<label>&nbsp;</label>
					<span style="font-weight:bold;">Do you coach more than one sport?</span>
				</p>
				<p class="lineheightnormal">
					<label>&nbsp;</label>
					<span>
						<input type="hidden" name="currentrow" value="0" id="currentrow" />
						
						<a href="javascript://" onclick="javascript:addRow(); return false;" style="float:left;text-decoration: none">[+] Add Sport</a>
                		<span id="remfield" style="display:none">&nbsp;&nbsp;&nbsp;&nbsp;
                			<a href="javascript://" onclick="javascript:removeRow(); return false;" style="text-decoration: none">[-] Remove Sport</a>
                		</span>
					</span>
				</p>
				
				<hr class="line" />
				<p>
				   <label>Enter your Security Question:</label>
                   <span><?php echo $this->Form->input("question",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                   <font color="#0000ff">&nbsp;*</font>
			    </p>

				<p>
                   <label>Enter your Security Answer:</label>
                   <span><?php echo $this->Form->input("answer",array("div"=>false,"label"=>false,"required"=>"true"));?></span>
                   <font color="#0000ff">&nbsp;*</font>
			    </p>
				
				<p>
					<label>&nbsp;</label>
					<span>
						<?php echo $this->Form->submit("Register",array("type"=>"submit","div"=>false,"label"=>false));?>
						
						<?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"User","action"=>"register"))."'"));?>
					</span>
				</p>
			</div>
		
		<?php echo $this->Form->end();?>
	</div>
</div>	