<div>
  <h1>Add Note / Comment</h1>
  
  <?php if(!isset($message)):?>
		  <div class="registerPage popupsmall">
			  <?php echo $this->Form->create("Note",array("url"=>array("controller"=>"Note","action"=>"add",$athlete_id),"type"=>"post"));?>	
				  <p>
				     <label>Title:</label> 
				     <span> 
				        <?php echo $this->Form->input("title",array("label"=>false,"div"=>false,"required"));?>
				     </span>
				     <font color="#0000ff">&nbsp;</font>
				  </p>
				  
				  <p>
				     <label>Comment:</label> 
				     <span> 
				        <?php echo $this->Form->input("description",array("label"=>false,"div"=>false,"type"=>"textarea","required"));?>
				     </span>
				     <font color="#0000ff">&nbsp;</font>
				  </p>
				
				  <p>
				     <label>&nbsp;</label> 
				     <span>
				     	<?php echo $this->Form->submit("Submit",array("div"=>false));?>
				     </span>
				  </p>
			   <?php echo $this->Form->end(); ?>
		   </div>
  <?php else: ?>
  			<p class="thankyoumessage"><?php echo $message;?></p>
  <?php endif;?>		   
</div>