<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!--Main Center Content BEGIN -->

								<table border="1" cellpadding="1" cellspacing="0" width="100%"
									style="border-collapse: collapse" class="tablePadd">

									<tr>
										<td align="center" class="normalwhite_14" colspan="6"
											bgcolor="#808080"><strong>Note Listing</strong></td>
									</tr>
									<tr>
										<td align='center' class='normalblack_12' colspan='6'
											height='30' valign='middle'><span style="color: #FF0000;"></span>
										</td>
									</tr>
									<tr>
										<td align='center' class='normalblack_12' colspan='6'
											height='30' valign='middle'>
										<form name="searchFrm" id="searchFrm" action="" method="POST"><input
											type="hidden" name="page" id="page" value="0"> <input
											type="text" name="searchname" id="searchname"> <input
											type="submit" name="search" id="search" style="width: 180px"
											value="Search Category By Name"></form>
										</td>
									</tr>
								</table>
								<form name="frmNoteList" action="" method="post" onSubmit="">
								<table border="1" cellpadding="1" cellspacing="0" width="100%"
									style="border-collapse: collapse" class="tablePadd">

									<tr>
										<td align="left" style="padding-left: 7px;" colspan="6"><input
											type="checkbox" id="check_all" name="check_all" value=""
											onClick="javascript:checkAll();"> <b>Check All</b>&nbsp;
										&nbsp;<input type="button" name="delete"
											value="Delete Selected" onClick="return deleteSelectedNote();">
										</td>
									</tr>

									<? if(sizeof($notes)>0){ ?>
									<tr>
										<td align="center" class="normalblack_12" width="4%">&nbsp;</td>
										<td align="left" class="normalblack_12" width="4%">&nbsp;<strong>S.No.</strong></td>
										<td align="left" class="normalblack_12" width="10%">&nbsp;<strong>Title</strong></td>
										<td align="left" class="normalblack_12" width="60%">&nbsp;<strong>Notes</strong></td>
										<td class="normalblack_12" width="5%" align="center"><strong>Edit</strong></td>
										<td class="normalblack_12" width="7%" align="center"><strong>Delete</strong></td>
									</tr>

									<?php $i = 1 ;?>
									<?php foreach ($notes as $note) : ?>

									<tr>

										<td align="center" class="normalblack_12">&nbsp;<input
											type="checkbox" id="check_delete[]" name="check_delete[]"
											value="<?php echo $note['Note']['id']?>" onclick="return checkItSelf();"></td>

										<td align="left" class="normalblack_12">&nbsp;<?php echo ($i + $limit * ($this->Paginator->current() - 1));?></td>
										<td align="left" class="normalblack_12"><?php echo wordwrap($note['Note']['title'],17,"\n",true);?></td>
										<td align="left" class="normalblack_12"><?php echo wordwrap($note['Note']['description'],30,"\n",true);?></td>
										<td class="normalblack_12" align="center">
											<?php echo $this->Html->link($this->Html->image('/img/b_edit.png'), array('controller' => 'Note', 'action' => 'editNote', $note['Note']['id']), array('escape' => false, 'title' => 'Edit'))?>
										</td>

										<td class="normalblack_12" align="center"><?php echo $this->Html->link($this->Html->image('/img/b_drop.png'), array('controller' => 'Note', 'action' => 'deleteNote', $note['Note']['id']), array('escape' => false, 'title' => 'Delete'), "Are you sure to delete the Note?")?>
										</td>


									</tr>

									<?php	$i++;?>
									<?php endforeach;?>
									<?php } else { ?>

									<tr>
										<td align="center" class="normalblack_12" colspan="6"
											height="30"><font color="red">No Records Available.</font></td>
									</tr>


									<?php } ?>

									</form>
								</table>
						
						</table>
						</form>

						<!--Main Center Content END --> <?php echo $this->element('pagination');?>

						</td>
					</tr>

				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
</table>
</td>
</tr>
									<?php echo $this->element('admin_footer');?>
</table>
