<div class="cantener">
  <div class="register-main">
      <div class="registerPage">
			<?php echo $this->Form->create("Athlete",array("url"=>array("controller"=>"Profile" , "action"=>"changePassword" ),"id"=>"forgetForm"));?>
	            <p>
					<label>Old Password:</label>
					<span>
						<?php echo $this->Form->input("old_password" , array("label" => false , "div" => false,"required","type"=>"password"))?>
					</span><font color="#0000ff">&nbsp;*</font>
				</p>
				
				<p>
					<label>Password:</label>
					<span>
						<?php echo $this->Form->input("password" , array("label" => false , "div" => false,"required","type"=>"password"))?>
					</span><font color="#0000ff">&nbsp;*</font>
				</p>
				
				<p>
					<label>Confirm Password:</label>
					<span>
						<?php echo $this->Form->input("confirm_password" , array("label" => false , "div" => false,"required","type"=>"password"))?>
					</span><font color="#0000ff">&nbsp;*</font>
				</p>
				
				<p>
                   <label>&nbsp;</label>
                   <span>
                        <?php echo $this->Form->submit("Update",array("div"=>false));?>
                        
                        <?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"Profile","action"=>"index"))."'"));?>
                   </span>
                </p>
			
			<?php echo $this->Form->end()?>
		</div>
	</div>
</div>					