<script type="text/javascript" src="<?php echo Router::fullBaseUrl().$this->base;?>/fancybox/jquery.fancybox.js"></script>
<link type="text/css" rel="stylesheet" href="<?php echo Router::fullBaseUrl().$this->base;?>/fancybox/jquery.fancybox.css" />
<script type="text/javascript">
   jQuery(document).ready(function() {
	   jQuery(".fancybox").fancybox({fitToView:true,width:'600px',height:'100%',autoSize:true});
	   jQuery(".fancybox2").fancybox({fitToView:true,width:'950px;',height:'100%',autoSize:true});
   });
</script>

<div class="profile">
  <div class="cantener">
	 <div class="register-main">
		<div class="registerPage1"><form>
			<h1 style="float:left;">College Coach Profile</h1>									

			<?php if($profileDetail['CollegeCoach']['id'] != $this->Session->read('user_id')):?>
					<div class="btnclass1" style="float:right;margin-right:20px;">
						<p>
							<span>
								<?php echo $this->Html->link("Add To Network",array("controller"=>"Network","action"=>"sendRequest",$profileDetail['CollegeCoach']['id'],"college"));?>
							</span>
						</p>
						<div class="clear"></div>
					</div>

					<div class="btnclass1" style="float:right;margin-right:20px;">
                        <p>
                          <span>
                          	 <?php echo $this->Html->link("Send Message",array("controller"=>"Mail","action"=>"composePopup","type"=>"college","receiver"=>$profileDetail['CollegeCoach']['username']),array("class"=>"fancybox fancybox.iframe"));?>
                          </span>
                        </p>
                        <div class="clear"></div>
                    </div>
			 <?php endif;?>									

			 <div class="clear"></div>

			 <!--START-ROW1-->
			 <div style="width: 890px;background#000;">
				<div style="width: 286px;float:left;background#ccc;">
					 <h3>General Information</h3>
					 <div class="boxes">
						<p>
                             <font class="title">Username:</font><?php echo $profileDetail['CollegeCoach']['username'];?>
                        </p>
                            
                        <p>
						     <font class="title">Name:</font> <?php echo $profileDetail['CollegeCoach']['firstname'] . " " . $profileDetail['CollegeCoach']['lastname']?>
						</p>
						
						<p>
							<font class="title">Phone:</font><?php echo $profileDetail['CollegeCoach']['phone'];?>
						</p>
						
						<p>
							<font class="title">Position:</font><?php echo $profileDetail['CollegeCoach']['position'];?>
						</p>

						<p>
						   <font class="title">Sport:</font><?php echo $profileDetail['Sport']['name'];?>
						</p>
					</div><!--//end-box-->

					<h3>Network</h3>
					<div class="boxes">
						<p>
							<span class="title">Total Users in Network: </span>
							<?php echo count($networkRequests); ?>
						</p>
					</div><!--//end-box-->
			    </div>

				<div style="width: 555px;float:right;background#ff8000;">
					<h3>College Information</h3>
					<div class="boxes">
						<p>
							<font class="title">Name: </font><?php echo $profileDetail['College']['name'];?>
						</p>

						<p>
							<font class="title">Address: </font>
							<?php echo ($profileDetail['College']['address_1']) ? $profileDetail['College']['address_1'] : 'N/A';?>
						</p>

						<p>
							<font class="title">City: </font>
							<?php echo ($profileDetail['College']['city']) ? $profileDetail['College']['city'] : 'N/A';?>
						</p>

						<p>
							<font class="title">State: </font>
							<?php echo ($profileDetail['College']['state']) ? $profileDetail['College']['state'] : 'N/A';?>
						</p>

						<p>
							<font class="title">Zip Code: </font>
							<?php echo ($profileDetail['College']['zip']) ? $profileDetail['College']['zip'] : 'N/A';?>
						</p>

						<p>
							<font class="title">Divison: </font>
							<?php echo ($profileDetail['College']['divison']) ? $profileDetail['College']['divison'] : 'N/A';?>
						</p>
					</div><!--//end-boxes-->

					<h3 style="float:left;">College Coach Needs</h3>
						<div style="float:right;">
							 <?php if ($this->Session->read('user_type') == 'college' && $is_trial_mode == false): ?>
								   <a href="<?php echo $this->Html->url(array("controller"=>"CollegeCoach","action"=>"addNeed"));?>" class="fancybox2 fancybox.iframe">Add Need</a>
							 <?php endif; ?>
						</div>

						<div class="clear"></div>
						<div class="boxes">
						    <?php if (count($collegeNeeds) == 0): ?>
						    
									You have not posted any needs. Click "Add Need" to post a need.
									
  					        <?php else: ?>
									<?php foreach ($collegeNeeds as $i => $collegeNeed): ?>
										   <p>
							                 <b>
												Need #<?php echo ++$i; ?> - 
												
												<a href="<?php echo $this->Html->url(array("controller"=>"CollegeCoach","action"=>"editNeed",$collegeNeed['CollegeNeed']['id']));?>" class="fancybox2 fancybox.iframe">Edit</a>
												
												|
												
												<?php echo $this->Html->link("Delete",array("controller"=>"CollegeCoach","action"=>"deleteNeed",$collegeNeed['CollegeNeed']['id']),null,"Are you sure?");?>
											 </b>
										   </p>
									<?php endforeach; ?>
							<?php endif; ?>												
						</div><!--//END-box-->
				   </div>
				   <div class="clear"></div>
			 </div>

			 <div style="width: 880px;display:block;">
				<h3>Your Network</h3>
				
				<div class="boxes" style="width:880px;padding: 8 10px;">
					<?php if (count($networkRequests) > 0): ?>
							<table cellspacing="2" cellpadding="5" bordercolor="#e7e7e7" border="0" width="100%" class="tablePadd whitetable" style="border-collapse: collapse;">
								<thead>
									<tr>
									   <th class="normalblack_12">User</th>
									   <th class="normalblack_12">Type</th>
									   <th class="normalblack_12">Status</th>
									</tr>
							    </thead>
							    <tbody>
									<?php foreach ($networkRequests as $request): ?>
										   <tr>
										      <td class="normalblack_12">
										      		<?php echo $this->Profile->url($request['Network']['sender_id'],$request['sender_type']);?>
							                  </td>

										      <td class="normalblack_12">
										            <?php echo $request['sender_type']; ?>
										      </td>

										      <td class="normalblack_12">
										            <?php echo $request['status']; ?>
										      </td>
	 						              </tr>
									<?php endforeach; ?>
								</tbody>
						   </table>
					 <?php else:?>
					 
					 	<p>You dont have networks.</p>
					 	   
					 <?php endif; ?>
					 <div class="clear"></div>
				  </div><!--//END-box-->
			 </div><!--//END-ROW2-->
		</form></div>
	 </div>
  </div>
</div>							