<div class="profile">
  <div class="cantener">
	 <div class="register-main">
		<div class="registerPage1"><form>
			<h1 style="float:left;">College Coach Profile</h1>									

			<?php if($profileDetail['CollegeCoach']['id'] == $this->Session->read('user_id')):?>
					<div class="btnclass1" style="float:right;margin-right:20px;">
						<p>
							<span>
								<?php echo $this->Html->link("Add To Network",array("controller"=>"Network","action"=>"sendRequest",$profileDetail['CollegeCoach']['id']));?>
							</span>
							<div class="clear"></div>
						</p>
					</div>

					<div class="btnclass1" style="float:right;margin-right:20px;">
                        <p>
                          <span>
                          	 <?php echo $this->Html->link("Send Message",array("controller"=>"Mail","action"=>"compose",$profileDetail['CollegeCoach']['id']));?>
                          </span>
                          <div class="clear"></div>
                        </p>
                    </div>
			 <?php endif;?>									

			 <div class="clear"></div>

			 <!--START-ROW1-->
			 <div style="width: 890px;background#000;">
				<!--START-LEFTCOL-->
				<div style="width: 286px;float:left;background#ccc;">
					 <h3>General Information</h3>
					 <div class="boxes">
						<p>
                               <font class="title">Username:</font><?php echo $profileDetail['CollegeCoach']['username'];?>
                            </p>
                            
                            <p>
						   <font class="title">Name:</font> <?php echo $profileDetail['CollegeCoach']['firstname'] . " " . $profileDetail['CollegeCoach']['lastname']?>
						</p>
						
						<p>
							<font class="title">Phone:</font><?php echo $profileDetail['CollegeCoach']['phone'];?>
						</p>
						
						<p>
							<font class="title">Position:</font><?php echo $profileDetail['CollegeCoach']['position'];?>
						</p>

						<p>
						   <font class="title">Sport:</font><?php echo $profileDetail['Sport']['name'];?>
						</p>
					</div><!--//end-box-->

					<h3>Network</h3>
					<div class="boxes">
						<p>
							<span class="title">Total Users in Network: </span>
							<?php echo count($networkRequests); ?>
						</p>
					</div><!--//end-box-->
			    </div>

				<!--//END-LEFTCOL-->

				<!--START-RIGHTCOL-->

				<div style="width: 555px;float:right;background#ff8000;">
					<h3>College Information</h3>
					<div class="boxes">
						<p>
							<font class="title">Name: </font><?php echo $profileDetail['College']['name'];?>
						</p>

						<p>
							<font class="title">Address: </font>
							<?php echo ($profileDetail['College']['address_1']) ? $profileDetail['College']['address_1'] : 'N/A';?>
						</p>

						<p>
							<font class="title">City: </font>
							<?php echo ($profileDetail['College']['city']) ? $profileDetail['College']['city'] : 'N/A';?>
						</p>

						<p>
							<font class="title">State: </font>
							<?php echo ($profileDetail['College']['state']) ? $profileDetail['College']['state'] : 'N/A';?>
						</p>

						<p>
							<font class="title">Zip Code: </font>
							<?php echo ($profileDetail['College']['zip']) ? $profileDetail['College']['zip'] : 'N/A';?>
						</p>

						<p>
							<font class="title">Divison: </font>
							<?php echo ($profileDetail['College']['divison']) ? $profileDetail['College']['divison'] : 'N/A';?>
						</p>
					</div><!--//end-boxes-->

					<h3 style="float:left;">College Coach Needs</h3>
						<div style="float:right;">
							 <?php if ($this->Session->read('user_type') == 'CollegeCoach'): ?>
										<a href="" class="">Add Need</a>
							 <?php endif; ?>
						</div>

						<div class="clear"></div>
						<div class="boxes">
						    <?php if (count($collegeNeeds) == 0): ?>
						    
									You have not posted any needs. Click "Add Need" to post a need.
									
  					        <?php else: ?>
									<?php foreach ($collegeNeeds as $id => $collegeNeed): ?>
										   <p>
							                 <b>
												Need #<?php echo $i++; ?> - 
							                    <a href="javascript:Showcomments('collegeNeed.php?action=edit&id=<?php echo $id; ?>','collegeNeed','width=1024,height=650')">Edit</a> /
	
											    <a href="javascript:deleteRecord(<?php echo $id; ?>);">Delete</a>
											 </b>
											 <br />
											 <?php echo $summary; ?>
										   </p>
	
									<?php endforeach; ?>
							<?php endif; ?>												
						</div><!--//END-box-->
				   </div>

				   <!--//END-RIGHTCOL-->
				   <div class="clear"></div>

				   <!--//CLEAR-LEFTandRIGHTcols-->
				   <!--//END-ROW1-->
			 </div>

			 <!--START-ROW2-->
			 <div style="width: 880px;display:block;">
				<h3>Your Network</h3>
				
				<div class="boxes" style="width:880px;padding: 8 10px;">
					<?php if (count($networkRequests) > 0): ?>
							<table cellspacing="2" cellpadding="5" bordercolor="#e7e7e7" border="0" width="100%" class="tablePadd whitetable" style="border-collapse: collapse;">
								<thead>
									<tr>
									   <th class="normalblack_12">User</th>
									   <th class="normalblack_12">Type</th>
									   <th class="normalblack_12">Status</th>
									</tr>
							    </thead>
							    <tbody>
									<?php foreach ($networkRequests as $request): ?>
										   <tr>
										      <td class="normalblack_12">
										      		<?php if($request['Network'][''])?>
										            <?php echo $func->GetUserProfileURLbyID($request['memberId'], $request['memberType']); ?>
							                  </td>

										      <td class="normalblack_12">
										            <?php echo $request['memberType']; ?>
										      </td>

										      <td class="normalblack_12">
										            <?php echo $request['status']; ?>
										      </td>
	 						              </tr>
									<?php endforeach; ?>
								</tbody>
						   </table>
						<?php endif; ?>
				  </div><!--//END-box-->
			 </div><!--//END-ROW2-->
		</form></div>
	 </div>
  </div>
</div>							