<div class="cantener">
 <?php if($this->Session->read('user_type') == 'athlete'):?>	
     <div class="register-main myaccount">
	 	 <h1 class="margin5">My Account</h1>
		   		
		 <div class="registerPage" style="position:relative;">
		 	 <h2>My Profile</h2>
		
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"athleteProfile"));?>">View My Profile</a></p>
		 	 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"index"));?>">Manage Game Tape</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"editAthleteProfile"));?>">Edit My Profile</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"changePassword"));?>">Change Password</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"addEditTeams",$this->Session->read('user_id')));?>">Add More Teams</a></p>
		
			 <h2>Messaging</h2>
			 <?php if ($mailCount > 0):?>
				 <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox (<?php echo $mailCount; ?>)</a></p>
			 <?php else:?>
			 	<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox</a></p>
			 <?php endif;?>
			 
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"sent"));?>">Sent</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"trash"));?>">Trash</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"coach"));?>">Send Message to a HS / AAU Coach</a></p>								
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"athlete"));?>">Send Message to a Fellow Athlete</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"college"));?>">Send Message to a College Coach</a></p>
					
			 <h2>My Network</h2>                                    
			 <?php if ($networkCount > 0):?>
			 	 <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests (<?php echo $networkCount;?>)</a></p>
			 <?php else:?>
				 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests</a></p>
			 <?php endif;?>  
			 
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","athlete"));?>">My Athletes</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","coach"));?>">My HS/AAU Coaches</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","college"));?>">My College Coaches</a></p>

		   	 <h2>Find a College</h2>
		
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"College","action"=>"index"));?>">Browse All Colleges</a></p>
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"College","action"=>"matches"));?>">View College Need Matches</a></p>
		
		     <h2>Games & Events</h2>
		
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"index"));?>">Add Game Stats</a></p>
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"addStat"));?>">Add New Game or Event</a></p>									
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"index"));?>">View All Games & Events</a></p>
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"upcoming"));?>">View Upcoming Games & Events</a></p>
		</div>
    </div>
  <?php elseif($this->Session->read('user_type') == 'coach'):?>	
	 <div class="register-main myaccount">
	 	 <h1 class="margin5">My Account</h1>

		 <div class="registerPage" style="position:relative;">
			<h2>Profile</h2>

			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"hsAauCoachProfile"));?>">View My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"editHsAauCoachProfile"));?>">Edit My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"changePassword"));?>">Change Password</a></p>
					
			<h2>Messaging</h2>
			
			<?php if ($mailCount > 0):?>
				 <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox (<?php echo $mailCount; ?> Unread)</a></p>
			<?php else:?>
			 	<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox</a></p>
			<?php endif;?>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"sent"));?>">Sent</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"trash"));?>">Trash</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"coach"));?>">Send Message to a Fellow HS / AAU Coach</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"athlete"));?>">Send Message to an Athlete</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"college"));?>">Send Message to a College Coach</a></p>

			<h2>Athlete Approval Requests</h2>

			<?php if($athleteApproval > 0):?>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href=<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"approval"));?>>Athlete Approval(<?php echo @$athleteApproval; ?>)</a></p>
			<?php else:?>		
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href=<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"approval"));?>>Athlete Approval(<?php echo @$athleteApproval; ?>)</a></p>
			<?php endif;?>		
			
			<?php if($athleteStatApproval > 0):?>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"statsList"));?>">Athlete Stats Approval(<?php echo @$athleteStatApproval; ?>)</a></p>

			<?php else:?>		
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"statsList"));?>">Athlete Stats Approval(0)</a></p>
			<?php endif;?>		

            <h2>My Network</h2>
            
            <?php if($networkCount > 0):?>
	            <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests(<?php echo $networkCount; ?>)</a></p>
	        <?php else:?>
	        	<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests(0)</a></p>
	        <?php endif;?>
	              
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","athlete"));?>">My Athletes</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","coach"));?>">My HS/AAU Coaches</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","college"));?>">My College Coaches</a></p>

			<h2>Find an Athlete</h2>

            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"index"));?>">Browse All Athletes</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"invite"));?>">Invite an Athlete to Join Site</a></p>

			<h2>Find a College</h2>

            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"College","action"=>"index"));?>">Browse All Colleges</a></p>
	    </div>
    </div>
  <?php else:?>
    <div class="register-main myaccount">
	    <h1 class="margin5">My Account</h1>

	    <div class="registerPage" style="position:relative;">
	    	<div class="event_scouting">
	    		<h2>Event Scouting Report</h2>
	    		
	    		<?php if(isset($profileDetail['CollegeCoach']['scouting_report'])):?>
					<a href="<?php echo Router::fullBaseUrl().$this->base."/".$profileDetail['CollegeCoach']['scouting_report'];?>"><?php echo $profileDetail['CollegeCoach']['scouting_report_name']?></a>
				
	    		<?php else:?>
					<p>No report uploaded yet</p>
				<?php endif;?>
                                <!-- <form name="pdfform" action="<?php echo $this->webroot . 'pdf' ?>" method="post">
                                    <select name="best_game" id="best_game" required style="width: 220px">
                                            <?php $games = $this->Register->getgames() ; ?>
                                            <option value="">Select Best game</option>
                                            <?php foreach($games as $key=>$game){ ?>
                                            <option value="<?php echo $key ; ?>"><?php echo $game ; ?></option>
                                            <?php } ?>
                                    </select> 
                                            <input type="submit" value="Generate Pdf" name="submit">
                                 </form>-->


                                       <?php //echo $this->Html->link(__('PDF'), array("controller"=>"ScoutReport",'action' => 'view', 'ext' => 'pdf', 207)); ?>
	    	</div>
	    	
		    <div class="subscriptionbox">
			    <h2>Your Subscription</h2>
					   
				<?php if ($is_trial_mode):?>
					  <p style="color:#222;margin-bottom:15px;">
						   You currently have limited access to Athletes & HS/AAU Coaches. please <a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"index"));?>" class="underline">Purchase a Subscription</a> to gain full access.
					  </p>
                <?php endif;?>
                
                <?php if(isset($collegeSubscription)):?>
					<p><b>Type:</b><?php  echo $collegeSubscription['Subscription']['name'];?></p>
					<p><b>Status:</b><?php  echo $collegeSubscription['CollegeSubscription']['status'];?></p>
					<p><b>Valid Until:</b><?php  echo $collegeSubscription['CollegeSubscription']['next_billdate'];?></p> 	   
							
					<h2>Account Details</h2>
	
					<p><b>Last Amount Paid:</b>$<?php  echo $collegeSubscription['CollegeSubscription']['amount'];?> USD</p>
	                <p><b>Created On:</b><?php echo $collegeSubscription['CollegeSubscription']['start_date'];?></p>
	                <p><b>Last Modified On:</b><?php echo $collegeSubscription['CollegeSubscription']['start_date'];?></p>
				<?php endif;?>	                
			</div>		
			 	
			<h2>Profile</h2>

			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"collegeCoachProfile"));?>">View My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"editCollegeCoachProfile"));?>">Edit My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"changePassword"));?>">Change Password</a></p>

			<h2>Messaging</h2>
					
			<?php If (!$is_trial_mode):?>   
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox(<?php echo $mailCount; ?>)</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"sent"));?>">Sent</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"trash"));?>">Trash</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"coach"));?>">Send Message to a HS / AAU Coach</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"athlete"));?>">Send Message to an Athlete</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"college"));?>">Send Message to a Fellow College Coach</a></p>
		
			<?php else:?>
                     <p>Sorry, this feature is disabled in Trial Mode, please <a href='<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"index"));?>'>Purchase a Subscription</a></p>
            
			<?php endif;?>
                         
                         
            <h2>My Network</h2>

		    <?php if(!$is_trial_mode):?>   
                          <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests(<?php echo $networkCount; ?>)</a></p>
                <?php else:?>
                          <p>Sorry, this feature is disabled in Trial Mode</p>
			<?php endif;?>
                
            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","athlete"));?>">My Athletes</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","coach"));?>">My HS/AAU Coaches</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","college"));?>">My College Coaches</a></p>

			<h2>Athlete Section</h2>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"search"));?>">Athlete Search</a></p>
            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"index"));?>">Browse All Athletes</a></p>


			<h2>HS / AAU Coach  Section</h2>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"HsAauCoach","action"=>"index"));?>">Browse  HS / AAU Coaches</a></p>

			<h2>Manage Subscription</h2>

			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"index"));?>">Add New Subscription</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"edit"));?>">Edit Subscription</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"history"));?>">View Payment History</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"cancel"));?>">Cancel Subscription</a></p>       
	    </div>
    </div>		
 <?php endif;?>	   
</div>

<script>
$(document).ready(function() {
  $('#flashMessage').animate({opacity: 1.0}, 5000).fadeOut();
});
</script>