<div class="cantener">
 <?php if($this->Session->read('user_type') == 'athlete'):?>	
     <div class="register-main myaccount">
	 	 <h1 class="margin5">My Account</h1>
		   		
		 <div class="registerPage" style="position:relative;">
		 	 <h2>My Profile</h2>
		
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"athleteProfile"));?>">View My Profile</a></p>
		 	 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Video","action"=>"index"));?>">Manage Game Tape</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"editAthleteProfile"));?>">Edit My Profile</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"changePassword"));?>">Change Password</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"addEditTeams",$this->Session->read('user_id')));?>">Add More Teams</a></p>
		
			 <h2>Messaging</h2>
			 <?php if ($mailCount > 0):?>
				 <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox (<?php echo $mailCount; ?>)</a></p>
			 <?php else:?>
			 	<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox</a></p>
			 <?php endif;?>
			 
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"sent"));?>">Sent</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"trash"));?>">Trash</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"coach"));?>">Send Message to a HS / AAU Coach</a></p>								
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"athlete"));?>">Send Message to a Fellow Athlete</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"college"));?>">Send Message to a College Coach</a></p>
					
			 <h2>My Network</h2>                                    
			 <?php if ($networkCount > 0):?>
			 	 <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests (<?php echo $networkCount;?>)</a></p>
			 <?php else:?>
				 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests</a></p>
			 <?php endif;?>  
			 
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","athlete"));?>">My Athletes</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","coach"));?>">My HS/AAU Coaches</a></p>
			 <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","college"));?>">My College Coaches</a></p>

		   	 <h2>Find a College</h2>
		
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"College","action"=>"index"));?>">Browse All Colleges</a></p>
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"College","action"=>"matches"));?>">View College Need Matches</a></p>
		
		     <h2>Games & Events</h2>
		
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"index"));?>">Add Game Stats</a></p>
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"addStat"));?>">Add New Game or Event</a></p>									
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"index"));?>">View All Games & Events</a></p>
		     <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Game","action"=>"upcoming"));?>">View Upcoming Games & Events</a></p>
		</div>
    </div>
  <?php elseif($this->Session->read('user_type') == 'coach'):?>
	 <div class="register-main myaccount">
	 	 <h1 class="margin5">My Account</h1>

		 <div class="registerPage" style="position:relative;">
			<h2>Profile</h2>

			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"hsAauCoachProfile"));?>">View My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"editHsAauCoachProfile"));?>">Edit My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"changePassword"));?>">Change Password</a></p>
					
			<h2>Messaging</h2>
			
			<?php if ($mailCount > 0):?>
				 <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox (<?php echo $mailCount; ?> Unread)</a></p>
			<?php else:?>
			 	<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox</a></p>
			<?php endif;?>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"sent"));?>">Sent</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"trash"));?>">Trash</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"coach"));?>">Send Message to a Fellow HS / AAU Coach</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"athlete"));?>">Send Message to an Athlete</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"college"));?>">Send Message to a College Coach</a></p>

			<h2>Athlete Approval Requests</h2>

			<?php if($athleteApproval > 0):?>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href=<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"approval"));?>>Athlete Approval(<?php echo @$athleteApproval; ?>)</a></p>
			<?php else:?>		
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href=<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"approval"));?>>Athlete Approval(<?php echo @$athleteApproval; ?>)</a></p>
			<?php endif;?>		
			
			<?php if($athleteStatApproval > 0):?>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"statsList"));?>">Athlete Stats Approval(<?php echo @$athleteStatApproval; ?>)</a></p>

			<?php else:?>		
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"statsList"));?>">Athlete Stats Approval(0)</a></p>
			<?php endif;?>		

            <h2>My Network</h2>
            
            <?php if($networkCount > 0):?>
	            <p><?php echo $this->Html->image('bullet-grey.gif');?><a style="color:#900000" href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests(<?php echo $networkCount; ?>)</a></p>
	        <?php else:?>
	        	<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests(0)</a></p>
	        <?php endif;?>
	              
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","athlete"));?>">My Athletes</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","coach"));?>">My HS/AAU Coaches</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","college"));?>">My College Coaches</a></p>

			<h2>Find an Athlete</h2>

            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"index"));?>">Browse All Athletes</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"invite"));?>">Invite an Athlete to Join Site</a></p>

			<h2>Find a College</h2>

            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"College","action"=>"index"));?>">Browse All Colleges</a></p>
	    </div>
    </div>
  <?php else:?>
    <link type="text/css" rel="stylesheet" href="<?php echo Router::fullBaseUrl().$this->base ; ?>/css/bootstrap.min.css" />
<script type="text/javascript" src="<?php echo Router::fullBaseUrl().$this->base ; ?>/js/bootstrap.min.js"></script>
<style>
.modal-content {
    height: 580px;
    overflow-y: scroll;
}
</style>
    <div class="register-main myaccount">
	    <h1 class="margin5">My Account</h1>

	    <div class="registerPage" style="position:relative;">
                <div class="event_scouting" style="right:90px;">
	    		<h2>Event Scouting Report</h2>
	    		
	    		<?php if(isset($profileDetail['CollegeCoach']['scouting_report'])):?>
					<a href="<?php echo Router::fullBaseUrl().$this->base."/".$profileDetail['CollegeCoach']['scouting_report'];?>"><?php echo $profileDetail['CollegeCoach']['scouting_report_name']?></a>
				
	    		<?php else:?>
					<p>No report uploaded yet</p>
				<?php endif;?>

                                        <a href="javascript:void(0);" data-toggle="modal" data-target="#myModal" >Show Scout Reports</a>

    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                </div>
                <div class="modal-body text-center">

                    <table border="1" cellpadding="1" cellspacing="0" width="100%" bordercolor="#808080" style="border-collapse: collapse" class="tablePadd">
                                                <tr>
                                                        <td align="center" class="normalwhite_14" colspan="10" bgcolor="#808080"><strong>Scout Report Listing</strong></td>
                                                </tr>

                                                <tr>
                                                        <td align='center' class='normalblack_12' colspan='10' height='30' valign='middle'><font color='red'></font></td>
                                                </tr>

                                                        <?php if(sizeof($ScoutReports)>0){ ?>
                                                        <tr>
                                                                <td align="left" class="normalblack_12" width="8%">&nbsp;<strong>S.No.</strong></td>

                                                                <td align="left" class="normalblack_12" width="25%">&nbsp;<strong>Title</strong></td>

                                                                <td align="left" class="normalblack_12" width="25%">&nbsp;<strong>Add Date</strong></td>

                                                                <td align="left" class="normalblack_12" width="25%">&nbsp;<strong>Last Modify</strong></td>

                                                                <td class="normalblack_12" width="7%" align="center"><strong>Details</strong></td>
                                                        </tr>
                                                        <?php $i = 1 ;?> <?php foreach ($ScoutReports as $ScoutReport) : ?>

                                                        <tr>
                                                                <td align="left" class="normalblack_12">&nbsp;<?php echo ($i + $limit * ($this->Paginator->current() - 1));?></td>

                                                                <td align="left" class="normalblack_12"><?php echo $ScoutReport['ScoutReports']['title'] ; ?></td>

                                                                <td align="left" class="normalblack_12">
                                                                        <?php echo date("M d Y",$ScoutReport['ScoutReports']['add_date']) ; ?>
                                                                </td>

                                                                <td align="left" class="normalblack_12">
                                                                        <?php if($ScoutReport['ScoutReports']['modify_date'] !=0){ echo date("M d Y",$ScoutReport['ScoutReports']['modify_date']) ; }else{ echo "Not Yet" ; } ?>
                                                                </td>

                                                                <td  class="normalblack_12" align="center"><a href="<?php echo $this->Html->url('/download_report/'.$ScoutReport['ScoutReports']['id'])  ; ?>">Download</a></td>

                                                        </tr>

                                                        <?php $i++;?> <?php endforeach;?> <?php } else { ?>

                                                        <tr>
                                                                <td align="center" class="normalblack_12" colspan="11" height="30"><font color="red">No Records Available.</font></td>
                                                   </tr>
                                                <?php } ?>
			</table>

                    <?php echo $this->element('pagination'); ?>

                </div>
            </div>
        </div>
    </div>


                      	    	</div>
	    	
		    <div class="subscriptionbox"  style="right:90px;top:134px;">
			    <h2>Your Subscription</h2>
					   
				<?php if ($is_trial_mode):?>
					  <p style="color:#222;margin-bottom:15px;">
						   You currently have limited access to Athletes & HS/AAU Coaches. please <a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"index"));?>" class="underline">Purchase a Subscription</a> to gain full access.
					  </p>
                <?php endif;?>
                
                <?php if(isset($collegeSubscription)):?>
					<p><b>Type:</b><?php  echo $collegeSubscription['Subscription']['name'];?></p>
					<p><b>Status:</b><?php  echo $collegeSubscription['CollegeSubscription']['status'];?></p>
					<p><b>Valid Until:</b><?php  echo $collegeSubscription['CollegeSubscription']['next_billdate'];?></p> 	   
							
					<h2>Account Details</h2>
	
					<p><b>Last Amount Paid:</b>$<?php  echo $collegeSubscription['CollegeSubscription']['amount'];?> USD</p>
	                <p><b>Created On:</b><?php echo $collegeSubscription['CollegeSubscription']['start_date'];?></p>
	                <p><b>Last Modified On:</b><?php echo $collegeSubscription['CollegeSubscription']['start_date'];?></p>
				<?php endif;?>	                
			</div>		
			 	
			<h2>Profile</h2>

			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"collegeCoachProfile"));?>">View My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"editCollegeCoachProfile"));?>">Edit My Profile</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"changePassword"));?>">Change Password</a></p>

			<h2>Messaging</h2>
					
			<?php If (!$is_trial_mode):?>   
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"index"));?>">Inbox(<?php echo $mailCount; ?>)</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"sent"));?>">Sent</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"trash"));?>">Trash</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"coach"));?>">Send Message to a HS / AAU Coach</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"athlete"));?>">Send Message to an Athlete</a></p>
					<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Mail","action"=>"compose",'value'=>"college"));?>">Send Message to a Fellow College Coach</a></p>
		
			<?php else:?>
                     <p>Sorry, this feature is disabled in Trial Mode, please <a href='<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"index"));?>'>Purchase a Subscription</a></p>
            
			<?php endif;?>
                         
                         
            <h2>My Network</h2>

		    <?php if(!$is_trial_mode):?>   
                          <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"requests"));?>">Network Requests(<?php echo $networkCount; ?>)</a></p>
                <?php else:?>
                          <p>Sorry, this feature is disabled in Trial Mode</p>
			<?php endif;?>
                
            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","athlete"));?>">My Athletes</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","coach"));?>">My HS/AAU Coaches</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Network","action"=>"index","college"));?>">My College Coaches</a></p>

			<h2>Athlete Section</h2>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"search"));?>">Athlete Search</a></p>
            <p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Athlete","action"=>"index"));?>">Browse All Athletes</a></p>


			<h2>HS / AAU Coach  Section</h2>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"HsAauCoach","action"=>"index"));?>">Browse  HS / AAU Coaches</a></p>

			<h2>Manage Subscription</h2>

			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"index"));?>">Add New Subscription</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"edit"));?>">Edit Subscription</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"history"));?>">View Payment History</a></p>
			<p><?php echo $this->Html->image('bullet-grey.gif');?><a href="<?php echo $this->Html->url(array("controller"=>"Subscribe","action"=>"cancel"));?>">Cancel Subscription</a></p>       
	    </div>
    </div>		
 <?php endif;?>	   
</div>

<script>
$(document).ready(function() {
  $('#flashMessage').animate({opacity: 1.0}, 5000).fadeOut();
});
</script>