<table width="100%" cellpadding="3" cellspacing="5">
	<tr>
		<td width="100%" align="center">
		<table width="95%" cellpadding="0" cellspacing="3">
			<tr>
				<td width="100%" class="SearchHead"><b>College Coach Details</b></td>
			</tr>
			<tr>
				<td width="100%" class="GeneralFont">&nbsp;</td>
			</tr>
			<tr>
				<td width="100%">
				<table width="100%" cellspacing="0" cellpadding="2">
					<tr>
						<td width="100%" valign="top">
						<table width="100%" cellspacing="0" cellpadding="3">						
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>College
								Name</b></td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['College']['name']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Divison</b>
								</td>

								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['division']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Address</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['address_1']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>City</b>
								</td>

								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['city']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Zip
								Code</b></td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['zip']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>State</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['state']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>First
								Name</b></td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['firstname']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Last
								Name</b></td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['lastname']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Phone</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['phone']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Alternate
								Phone</b></td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['phone2']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Email
								Address</b></td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['email']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Alternative
								Email Address</b></td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['CollegeCoach']['email2']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Sport</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $collegeCoach['Sport']['name']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Subscription
								Status</b></td>
								<?php $subscribe = $collegeCoach['CollegeCoach']['subscription_id'];?>
								<td class="normalblack_12" valign="top"><?php if($subscribe==0){echo "Not Subscribe";}if($subscribe==1){echo "Subscribe";}if($subscribe==2){echo "Trial Period";}?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Payment Date</b></td>								
								<td class="normalblack_12" valign="top">									
									<?php echo (isset($collegeCoach['CollegeCoach']['last_payment_date']) ? $collegeCoach['CollegeCoach']['last_payment_date'] :  "Payment not yet made")?>
								</td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Amount</b>
								</td>
								<td class="normalblack_12" valign="top">
									<?php echo (isset($collegeCoach['CollegeCoach']['last_pay_amount']) ? $collegeCoach['CollegeCoach']['last_pay_amount'] : "Payment not yet made")?>
								</td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Status</b>
								</td>
								<td class="normalblack_12" valign="top">
									<?php if($collegeCoach['CollegeCoach']['status'] == 1) {echo "ACTIVE";} else {echo "DE-ACTIVE";} ?>									
								</td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" colspan="2">&nbsp;</td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									colspan="2"><input type=button value="Close"
									onClick="javascript:window.close();"></td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td width="100%" align="center">&nbsp;</td>
	</tr>

</table>
