<script
	type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<?php
echo $this->Html->css('/fancybox/admin/jquery.fancybox-1.3.4.css');
echo $this->Html->script('/fancybox/admin/jquery.easing-1.3.pack.js');
echo $this->Html->script('/fancybox/admin/jquery.fancybox-1.3.4.js');
echo $this->Html->script('/fancybox/admin/jquery.mousewheel-3.0.4.pack.js'); 
?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!--Main Center Content BEGIN -->

								<table border="1" cellpadding="1" cellspacing="0" width="100%"
									bordercolor="#808080" style="border-collapse: collapse"
									class="tablePadd">
									<tr>
										<td align="center" class="normalwhite_14" colspan="10"
											bgcolor="#808080"><strong>Other Listing</strong></td>
									</tr>
									<tr>
										<td align='center' class='normalblack_12' colspan='10'
											height='30' valign='middle'><font color='red'></font></td>
									</tr>

									<tr>
										<td align='center' class='normalblack_12' colspan='10'
											height='30' valign='middle'>
										<form name="searchFrm" id="searchFrm" action="" method="POST">
										<input type="hidden" name="page" id="page" value="0"> <input
											type="text" name="searchname" id="searchname"> <input
											type="submit" name="search" id="search" style="width: 180px"
											value="Search Category By Name"></form>
										</td>
									</tr>
									<form name="frmListOther" action="" method="post" onsubmit="">
									<?php if (sizeof($others) > 0) {?>
									<tr>
										<td align="left" style="padding-left: 7px;" colspan="10"><input
											type="checkbox" id="check_all" name="check_all" value=""
											onclick="javascript:checkAll();"> <b>Check All</b>&nbsp;
										&nbsp;<input type="button" name="delete"
											value="Delete Selected" onclick="return submitDeleteAll();"></td>
									</tr>

									<tr>
										<td align="center" class="normalblack_12" width="4%">&nbsp;</td>
										<td align="left" class="normalblack_12" width="8%">&nbsp;<strong>S.No.</strong></td>
										<td align="left" class="normalblack_12" width="25%">&nbsp;<strong>Other
										Name</strong></td>
										<td class="normalblack_12" width="5%" align="center"><strong>Edit</strong></td>
										<td class="normalblack_12" width="7%" align="center"><strong>Delete</strong></td>
										<td class="normalblack_12" width="7%" align="center"><strong>View</strong></td>

									</tr>
									<?php	foreach ($others as $other) :
											$i = 1 ;?>

									<tr>
										<td align="center" class="normalblack_12">&nbsp;<input
											type="checkbox" id="check_delete[]" name="check_delete[]"
											value="'.$fldId.'" onclick="return checkItSelf();">

										<td align="left" class="normalblack_12">&nbsp;<?php echo ($i + $limit * ($this->Paginator->current() - 1));?></td>
										<td align="left" class="normalblack_12"><?php echo wordwrap($other['Other']['name'],17,"\n",true)?></td>
										<td class="normalblack_12" align="center">
											<?php echo $this->Html->link('Edit', array('controller' => 'Other', 'action' => 'otherEdit', $other['Other']['id']))?>
										</td>
										<td class="normalblack_12" align="center">
											<?php echo $this->Html->link($this->Html->image('/img/b_drop.png'), array('controller' => 'Other', 'action' => 'deleteOther', $other['Other']['id']), array('escape' => false, 'title' => 'Delete'), "Are you sure to delete the Other?")?>	
										</td>
										<td class="normalblack_12" align="center">
											<?php echo $this->Html->link('View', array('controller' => 'Other', 'action' => 'otherDetails', $other['Other']['id']), array('id' => 'view_other', 'target' => 'blank'))?>
										</td>								
									</tr>

									<?php	$i++;?>
									<tr>
										<td align="right" class="normalblack_12" colspan="10">&nbsp;</td>
									</tr>
									<?php endforeach;?> <?php } else { ?>																		
										<tr>
											<td align="center" class="normalblack_12" colspan="10"
												height="30"><font color="red">No Records Available.</font></td>
										</tr>
									<?php } ?>

									</form>
								</table>
								<!--Main Center Content END --> 
								<?php echo $this->element('pagination');?>
								</td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>

<script type="text/javascript">
$(document).ready(function() {
		
	$("a#view_other").fancybox({
		'hideOnContentClick': true
	});
		
});
</script>