-- MySQL Script generated by MySQL Workbench
-- 08/17/14 22:36:00
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema CollegeProspectNetwork
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CollegeProspectNetwork` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `CollegeProspectNetwork` ;

-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`admin` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `user_type` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `last_login` DATETIME NULL,
  `dateofmodification` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`sports` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` TEXT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `dateofmodification` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`athletes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`athletes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `class` VARCHAR(255) NULL,
  `height` VARCHAR(255) NULL,
  `width` VARCHAR(255) NULL,
  `sport_id` INT NOT NULL,
  `primary_position` VARCHAR(255) NULL,
  `secondary_position` VARCHAR(255) NULL,
  `vertical` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `school` VARCHAR(255) NULL,
  `image` VARCHAR(255) NULL,
  `status` TINYINT(1) NULL,
  `comments` VARCHAR(255) NULL,
  `division` VARCHAR(255) NULL,
  `yarddash_40` VARCHAR(255) NULL,
  `shuttle_run` VARCHAR(255) NULL,
  `bench_press_max` VARCHAR(255) NULL,
  `squat_max` VARCHAR(255) NULL,
  `gpa` VARCHAR(255) NULL,
  `sat_score` VARCHAR(255) NULL,
  `act_score` VARCHAR(255) NULL,
  `class_rank` VARCHAR(255) NULL,
  `clearing_house_eligible` VARCHAR(255) NULL,
  `intended_major` VARCHAR(255) NULL,
  `coach_id` INT NOT NULL,
  `question` VARCHAR(255) NULL,
  `answer` VARCHAR(255) NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `zip` VARCHAR(255) NULL,
  `jersey_number` VARCHAR(255) NULL,
  `is_notified` TINYINT(1) NULL DEFAULT 0,
  `note_id` VARCHAR(255) NULL,
  `last_week_counter` INT NULL DEFAULT 0,
  `weekly_counter` INT NULL DEFAULT 0,
  `total_counter` INT NULL DEFAULT 0,
  `youtube_link` VARCHAR(255) NULL,
  `youtube_modifydate` DATETIME NULL,
  `rating` INT NULL DEFAULT 0,
  `total_points` INT NULL DEFAULT 0,
  `added_date` DATETIME NOT NULL,
  `modify_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `sport_fk_idx` (`sport_id` ASC),
  CONSTRAINT `sport_fk`
    FOREIGN KEY (`sport_id`)
    REFERENCES `CollegeProspectNetwork`.`sports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cost` DECIMAL(10,2) NOT NULL,
  `period` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `dateofmodification` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`colleges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`colleges` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `address_1` VARCHAR(255) NOT NULL,
  `address_2` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `zip` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `divison` VARCHAR(255) NULL,
  `latitude` VARCHAR(255) NULL,
  `longitude` VARCHAR(255) NULL,
  `approved` TINYINT(1) NOT NULL DEFAULT 0,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `join_date` DATETIME NOT NULL,
  `dateofmodification` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`college_coaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`college_coaches` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `college_id` INT NOT NULL,
  `city` VARCHAR(255) NULL,
  `state` VARCHAR(255) NULL,
  `country` VARCHAR(255) NULL,
  `zip` VARCHAR(255) NULL,
  `address_1` VARCHAR(255) NOT NULL,
  `address_2` VARCHAR(255) NULL,
  `sport_id` INT NOT NULL,
  `position` VARCHAR(255) NULL,
  `need_type_id` INT NULL,
  `email` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `phone2` VARCHAR(255) NULL,
  `division` VARCHAR(255) NULL,
  `question` VARCHAR(255) NOT NULL,
  `answer` VARCHAR(255) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `added_date` DATETIME NOT NULL,
  `modified_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`hs_aau_coach`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`hs_aau_coach` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `firstname` VARCHAR(255) NULL,
  `lastname` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NULL,
  `decription` VARCHAR(255) NULL,
  `school` VARCHAR(255) NULL,
  `sport_id` INT NULL,
  `question` VARCHAR(255) NULL,
  `answer` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `added_date` DATETIME NOT NULL,
  `modify_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`hs_aau_coach_rating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`hs_aau_coach_rating` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `hs_aau_coach_id` INT NOT NULL,
  `college_coach_id` INT NOT NULL,
  `contribute` VARCHAR(45) NULL,
  `comunication` VARCHAR(45) NULL,
  `request_game_tape` VARCHAR(45) NULL,
  `honest` VARCHAR(45) NULL,
  `prepration` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL DEFAULT 0,
  `added_date` VARCHAR(45) NOT NULL,
  `modify_date` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`special_events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`special_events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sport_id` INT NOT NULL,
  `event_name` VARCHAR(255) NOT NULL,
  `event_desc` VARCHAR(255) NULL,
  `location` VARCHAR(255) NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `current_price` DECIMAL(10,2) NULL,
  `future_price` DECIMAL(10,2) NULL,
  `early_discount_day` INT NULL,
  `early_discount_rate` FLOAT NULL,
  `transcript_discount` FLOAT NULL,
  `home_team` TINYINT(1) NULL,
  `away_team` TINYINT(1) NULL,
  `event_opponent` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `added_date` DATETIME NOT NULL,
  `modify_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`special_event_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`special_event_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `special_event_id` INT NOT NULL,
  `firstname` VARCHAR(255) NOT NULL,
  `lastname` VARCHAR(255) NOT NULL,
  `address_1` VARCHAR(255) NOT NULL,
  `address_2` VARCHAR(255) NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NULL,
  `zip` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `referred_by` VARCHAR(255) NULL,
  `transcript` VARCHAR(255) NULL,
  `price` VARCHAR(255) NULL,
  `class` VARCHAR(255) NULL,
  `primary_position` VARCHAR(255) NULL,
  `secondary_position` VARCHAR(255) NULL,
  `coach_name` VARCHAR(255) NOT NULL,
  `school` VARCHAR(255) NULL,
  `other_school` VARCHAR(255) NULL,
  `hs_aau_coach_name` VARCHAR(255) NOT NULL,
  `hs_aau_team_id` INT NOT NULL,
  `coupon_number` VARCHAR(255) NULL,
  `payment_status` VARCHAR(255) NULL,
  `added_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`hs_aau_team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`hs_aau_team` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `school_code` VARCHAR(255) NULL,
  `school_name` VARCHAR(255) NULL,
  `coach_name` VARCHAR(255) NULL,
  `coach_phone` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  `country` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `zip` VARCHAR(255) NULL,
  `logo` VARCHAR(255) NULL,
  `sport_id` INT NULL,
  `athlete_url` VARCHAR(255) NULL,
  `enrollment` VARCHAR(255) NULL,
  `latitude` VARCHAR(255) NULL,
  `longitude` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `added_date` DATETIME NOT NULL,
  `modify_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`athelete_stats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`athelete_stats` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `athelete_id` INT NOT NULL,
  `category_id` INT NULL,
  `value` VARCHAR(45) NULL,
  `label_name` VARCHAR(45) NULL,
  `college_coach_id` INT NOT NULL,
  `sport_id` INT NOT NULL,
  `group` VARCHAR(45) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `sort_order` VARCHAR(45) NULL,
  `added_date` DATETIME NOT NULL,
  `modify_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`athelete_stat_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`athelete_stat_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `code` VARCHAR(45) NOT NULL,
  `parent_id` INT NOT NULL DEFAULT 0,
  `group` VARCHAR(45) NULL,
  `status` TINYINT(1) NOT NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`athlete_videos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`athlete_videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `video_path` VARCHAR(45) NOT NULL,
  `video_type` VARCHAR(45) NULL,
  `athlete_id` INT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `added_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`classes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`classes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `added_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`college_subscriptions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`college_subscriptions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sport_id` INT NOT NULL,
  `college_coach_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `next_billdate` DATETIME NOT NULL,
  `transaction_id` VARCHAR(45) NOT NULL,
  `payment_profile_id` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `cancel_date` DATETIME NULL,
  `cancel_reason` VARCHAR(45) NULL,
  `added_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`coupons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`coupons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `event_id` INT NOT NULL,
  `amount` DECIMAL(10,2) NOT NULL,
  `is_used` TINYINT(1) NOT NULL DEFAULT 0,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `added_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`events` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sport_id` INT NOT NULL,
  `event_name` VARCHAR(255) NOT NULL,
  `event_desc` VARCHAR(255) NULL,
  `location` VARCHAR(255) NULL,
  `start_date` DATETIME NOT NULL,
  `end_date` DATETIME NOT NULL,
  `home_team` TINYINT(1) NULL,
  `away_team` TINYINT(1) NULL,
  `event_opponent` VARCHAR(255) NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `added_date` DATETIME NOT NULL,
  `modify_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CollegeProspectNetwork`.`mails`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CollegeProspectNetwork`.`mails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sender` VARCHAR(45) NOT NULL,
  `receiver` VARCHAR(45) NOT NULL,
  `subject` VARCHAR(45) NOT NULL,
  `message` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 0,
  `sent_date` DATETIME NOT NULL,
  `usertype_from` VARCHAR(45) NULL,
  `usertype_to` VARCHAR(45) NULL,
  `added_date` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
