<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!--Main Center Content BEGIN -->

								<table border="1" cellpadding="1" cellspacing="0" width="100%"
									bordercolor="#808080" style="border-collapse: collapse"
									class="tablePadd">

									<tr>
										<td align="center" class="normalwhite_14" colspan="10"
											bgcolor="#808080"><strong>Home Page Content</strong></td>
									</tr>

									<tr>
										<td align='center' class='normalblack_12' colspan='10'
											height='30' valign='middle'><font color='red'></font></td>
									</tr>

									<form name="frmPage" action="" method="post" onsubmit="">
									<? if(sizeof($homeContents)>0){ ?>
									<tr>
										<td align="left" class="normalblack_12" width="8%">&nbsp;<strong>S.No.</strong></td>
										<td align="left" class="normalblack_12" width="25%">&nbsp;<strong>Title</strong></td>
										<td class="normalblack_12" width="5%" align="center"><strong>Edit</strong></td>
									</tr>

									<?php $i = 1 ;?> <?php foreach ($homeContents as $homeContent) : ?>
									<tr>
										<td align="left" class="normalblack_12">&nbsp;<?php echo ($i + $limit * ($this->Paginator->current() - 1));?></td>
										<td align="left" class="normalblack_12"><?php echo wordwrap($homeContent['HomeContent']['title'],17,"\n",true);?></td>
										<td class="normalblack_12" align="center">
											<?php echo $this->Html->link($this->Html->image('/img/b_edit.png'), array('controller' => 'Page', 'action' => 'editHomeContent', $homeContent['HomeContent']['id']), array('escape' => false, 'title' => 'Edit'))?>	
										</td>

									</tr>
									<?php	$i++;?> <?php endforeach;?> <?php } else { ?>
																		
									<tr>
										<td align="center" class="normalblack_12" colspan="10"
											height="30"><font color="red">No Records Available.</font></td>
									</tr>								
									<?php } ?>
									</form>
								</table>

								<!--Main Center Content END --> <?php echo $this->element('pagination');?>

								</td>
							</tr>

						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>
