<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!--Main Center Content BEGIN -->

								<table border="1" cellpadding="1" cellspacing="0" width="100%"
									bordercolor="#808080" style="border-collapse: collapse"
									class="tablePadd">

									<tr>
										<td align="center" class="normalwhite_14" colspan="10"
											bgcolor="#808080"><strong>Transportation Discount Detail
										Listing</strong></td>
									</tr>

									<tr>
										<td align='center' class='normalblack_12' colspan='10'
											height='30' valign='middle'><font color='red'></font></td>
									</tr>

									<form name="frmTransportationDiscount" action="" method="post" onSubmit="">
									<tr>
										<td align="left" style="padding-left: 7px;" colspan="10"><input
											type="checkbox" id="check_all" name="check_all" value=""
											onClick="javascript:checkAll();"> <b>Check All</b>&nbsp;
										&nbsp;<input type="button" name="delete"
											value="Delete Selected" onClick="return deleteSelectedTransportationDiscount();"></td>
									</tr>
									<? if(sizeof($transportationDiscounts)>0){ ?>
									<tr>
										<td align="center" class="normalblack_12" width="4%">&nbsp;</td>
										<td align="left" class="normalblack_12" width="8%">&nbsp;<strong>S.No.</strong></td>
										<td align="left" class="normalblack_12" width="35%">&nbsp;<strong>Departure
										City</strong></td>
										<td align="left" class="normalblack_12" width="10%">&nbsp;<strong>Departure
										Time</strong></td>
										<td align="left" class="normalblack_12" width="10%">&nbsp;<strong>Transportation
										Charge</strong></td>
										<td class="normalblack_12" width="5%" align="center"><strong>Edit</strong></td>
										<td class="normalblack_12" width="7%" align="center"><strong>Delete</strong></td>
									</tr>
									<?php $i = 1 ;?> <?php foreach ($transportationDiscounts as $transportationDiscount) : ?>
									<tr>
										<td align="center" class="normalblack_12">&nbsp; <input
											type="checkbox" id="check_delete[]" name="check_delete[]"
											value="<?php echo $transportationDiscount['TransportationDiscount']['id']?>" onclick="return checkItSelf();">
										<td align="left" class="normalblack_12">&nbsp;<?php echo ($i + $limit * ($this->Paginator->current() - 1));?></td>
										<td align="left" class="normalblack_12"><?php echo wordwrap($transportationDiscount['TransportationDiscount']['departure_city'],17,"\n",true);?></td>
										<td align="left" class="normalblack_12"><?php echo wordwrap($transportationDiscount['TransportationDiscount']['departure_time'],17,"\n",true);?></td>
										<td align="left" class="normalblack_12"><?php echo wordwrap($transportationDiscount['TransportationDiscount']['transport_charge'],17,"\n",true);?></td>
										<td class="normalblack_12" align="center">
											<?php echo $this->Html->link($this->Html->image('/img/b_edit.png'), array('controller' => 'TransportationDiscount', 'action' => 'editTransportationDiscount', $transportationDiscount['TransportationDiscount']['id']), array('escape' => false, 'title' => 'Edit'))?>	
										</td>
										<td class="normalblack_12" align="center">
											<?php echo $this->Html->link($this->Html->image('/img/b_drop.png'), array('controller' => 'TransportationDiscount', 'action' => 'deleteTransportationDiscount', $transportationDiscount['TransportationDiscount']['id']), array('escape' => false, 'title' => 'Delete'), "Are you sure to delete the TransportationDiscount?")?>
										</td>
									
									</tr>

									<?php	$i++;?> <?php endforeach;?> <?php } else { ?>
									
									
									<tr>
										<td align="center" class="normalblack_12" colspan="10"
											height="30"><font color="red">No Records Available.</font></td>
									</tr>
									<?php } ?>
									</form>
								</table>

								<!--Main Center Content END --> <?php echo $this->element('pagination');?>
								</td>
							</tr>

						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>
