<?php $error_msg = '';?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!-- MAin Content Starts From Here -->
								<form name="frmAddTransDis" action="" method="post"
									enctype="multipart/form-data" id="frmtransport">
								<table width="100%" border="1" cellpadding="1" cellspacing="0"
									bordercolor="#808080" style="border-collapse: collapse">
									<tr height="20">
										<td align="center" class="normalblack_12" width="90%"
											valign="top">
										<table width="100%" border="0" cellpadding="0" cellspacing="0"
											bgcolor="#FFFFFF">
											<tr>
												<!-- Display the message on heading of the page -->
												<td valign="top" class="normalwhite_14" colspan=3
													bgcolor="#808080" align="center"><b>Add Transportation
												Discount</b></td>
											</tr>
											<tr>
												<!-- Display the message on heading of the page -->
												<td valign="top" colspan=3 align="center">&nbsp;</td>
											</tr>
											<tr>
												<td valign="top" colspan=3 align="center"
													class="normalblack_12"><font color="Red"></font>
												</td>
											</tr>
											<tr>
												<td height="35" colspan="3" align="right"
													class="normalblack_12"><FONT color="Red">Fields marked with
												* are mandatory&nbsp;</FONT></td>
											</tr>
											<tr height="20">
												<td valign="top" class="normalwhite_14" colspan=4
													align="center">&nbsp;</td>
												<tr height="20" id="txtEvent">
													<td valign="top" align="right" class="normalblack_12"
														width="30%">Special Event<font color="red">*</font></td>
													<td valign="top" align="center" class="normalblack_12">:
													&nbsp;</td>
													<td valign="top" align="left" class="normalblack_12"
														colspan=2>
														<?php echo $this->Form->input('event_id', array('type' => 'select', 'empty' => array('select' => 'Select Event'), 'style' => 'width: 220px', 'label' => false, 																								
																								'options' => $eventList)); ?>	
													</td>
												</tr>
												<tr height="20">
													<td valign="top" class="normalwhite_14" colspan=4
														align="center">&nbsp;</td>
													<tr height="20" id="txtEvent">
														<td valign="top" align="right" class="normalblack_12"
															width="30%">Diparture City <font color="red">*</font></td>
														<td valign="top" align="center" class="normalblack_12">:
														&nbsp;</td>
														<td valign="top" align="left" class="normalblack_12"
															colspan=2><input type="text" name="departure_city"
															id="departure_city" value=""
															maxlength="30" style="width: 220px;"></td>
													</tr>
													<tr height="20">
														<td valign="top" class="normalwhite_14" colspan=4
															align="center">&nbsp;</td>
														<tr height="20">
															<td valign="top" align="right" class="normalblack_12"
																width="30%">Departure Time<font color="red">*</font></td>
															<td valign="top" align="center" class="normalblack_12">:
															</td>
															<td valign="top" align="left" class="normalblack_12"><select
																name="hours" id="hours">
																<option value="">Select Hours</option>
																<?php for($i=1;$i<=12;$i++){
																	if($i<10)
																	{ $i="0".$i;}?>
																<option value="<?php echo $i;?>"><?php echo $i;?></option>
																<?php } ?>
															</select> <select name="minute" id="minute">
																<option value="">Select Minute</option>
																<?php for($i=1;$i<=60;$i++){
																	if($i<10)
																	{ $i="0".$i;}?>
																<option value="<?php echo $i;?>"><?php echo $i;?></option>
																<?php } ?>
															</select> <select name="option" id="option">
																<option value="">Select AM/PM</option>
																<option value="AM">AM</option>
																<option value="PM">PM</option>
															</select> <?php /*?><input type="text" name="Departure_Time" id="Departure_Time" value="<?=$Departure_Time?>" style="width: 220px;"><?php */?></td>
														</tr>

														<tr height="20">
															<td valign="top" class="normalwhite_14" colspan=4
																align="center">&nbsp;</td>
															<tr height="20">
																<td valign="top" align="right" class="normalblack_12"
																	width="30%">Transportation Charge<font color="red">*</font>
																</td>
																<td valign="top" align="center" class="normalblack_12">
																:</td>
																<td valign="top" align="left" class="normalblack_12"><input
																	type="text" name="transportation_charge"
																	id="transportation_charge"
																	value=""
																	style="width: 220px;"
																	onKeyPress="return isNumber(event)"></td>
															</tr>

															<tr height="20">
																<td valign="top" class="normalwhite_14" colspan=4
																	align="center">&nbsp;</td>
															</tr>
															<tr height="20">
																<td valign="top" align="right" class="normalblack_12"
																	width="30%">Status <font color="red">*</font></td>
																<td valign="top" align="center" class="normalblack_12">
																:</td>
																<td valign="top" align="left" class="normalblack_12">
																<?php echo $this->Form->input('status', array('type'=>'select', 'label' => false, 'style' => 'width: 220px',  
															 							  'options' => array('1' => 'ACTIVE', '0' => 'DE-ACTIVE'))); ?>
																</td>
															</tr>
															<tr height="20">
																<td valign="top" class="normalwhite_14" colspan=4
																	align="center">&nbsp;</td>
															</tr>
															<tr height="20">
																<td valign="top" align="right" class="normalblack_12"
																	width="30%">&nbsp</td>
																<td valign="top" align="center" class="normalblack_12">
																&nbsp</td>
																<td valign="top" align="left" class="normalblack_12"><input
																	type="hidden" name="isSubmit" value="save"> <input
																	type="submit" name="submit" value="Submit"
																	onClick="return validate();">&nbsp;&nbsp;<input
																	type="reset" name="Submit2" value="Reset"></td>
															</tr>

															<tr height="20">
																<td valign="top" colspan=3 align="center"
																	class="normalblack_12">&nbsp;</td>
															</tr>
															<!-- Upoad File END-->
										
										</table>
										</td>
									</tr>
								</table>
								</form>
								<!--Main Center Content END --></td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>

<script type="text/javascript">
function validate(){
	
	if(trimString(document.frmAddTransDis.event_id.value) == "select"){
		alert("Please Enter Event!");
		return false;
		document.frmAddTransDis.event_id.focus();
	}
	
	if(trimString(document.frmAddTransDis.departure_city.value) == ""){
		alert("Please Enter Diparture City!");
		return false;
		document.frmAddTransDis.diparture_city.focus();
	}
	
	if(trimString(document.frmAddTransDis.hours.value) == ""){
		alert("Please Enter Departure Hour!");
		return false;
		document.frmAddTransDis.hours.focus();
	}
	
	if(trimString(document.frmAddTransDis.minute.value) == ""){
		alert("Please Enter Departure Minute!");
		return false;
		document.frmAddTransDis.minute.focus();
	}
	
	if(trimString(document.frmAddTransDis.option.value) == ""){
		alert("Please Enter AM/PM!");
		return false;
		document.frmAddTransDis.option.focus();
	}
	
	if(trimString(document.frmAddTransDis.transportation_charge.value) == ""){
		alert("Please Enter Transportation Charge!");
		return false;
		document.frmAddTransDis.transportation_charge.focus();
	}
}

</script>
