<?php

//
// This is the layout page for the admin section. It's much simpler than the rest of the site!
//

	echo $this->Html->css('admin/styles');
?>
<!DOCTYPE html>
<html>
    <head>
		
        <title>			
            College Prospect Network
            &bull; Admin Panel
        </title>
    </head>
    <body>        
        <div id="admin-content">			
			<?php echo $content_for_layout; ?>
        </div>
    </body>
	
</html>