<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright     Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link          http://cakephp.org CakePHP(tm) Project
 * @package       app.View.Layouts
 * @since         CakePHP(tm) v 0.10.0.1076
 * @license       http://www.opensource.org/licenses/mit-license.php MIT License
 */

?>
<!DOCTYPE html>
<html>
<head>
	<?php echo $this->Html->charset(); ?>
	<title>
		<?php echo $title_for_layout; ?>
	</title>
	<?php echo $this->Html->meta('icon', 'favicon.ico');?>
	<?php echo $this->Html->meta('keywords', @$keywords_for_layout);?>
	<?php echo $this->Html->meta('description', @$description_for_layout);?>
	
	<link type="text/css" rel="stylesheet" href="<?php echo Router::fullBaseUrl().$this->base;?>/css.php?file=style.css" />
	<script type="text/javascript" src="<?php echo Router::fullBaseUrl().$this->base;?>/js.php?file=jquery-1.10.1.min.js"></script>
	<script type="text/javascript">
		//setTimeout(function(){jQuery('#flashMessage').hide();},10000);
	</script>
	
	<?php echo $this->Html->css("blur.css");?>
</head>
<body>
   <div id="main">
	    <?php echo $this->Element('header');?>	

		<div class="container">
			 <div class="innerWraper">
			 	<div class="middle-bg">	
			 	
			 		<?php if($this->Session->check('Message.flash')):?> 
						<div align="center" id="flashMessage" class="thankyoumessage">
							<?php echo $this->Session->flash(); ?>
							<br />
						</div>
					<?php endif;?>
					
					<?php echo $this->fetch('content'); ?>
				</div>	
			</div>
		</div>
		
		<?php echo $this->Element('footer');?>	
	</div>
	
	<?php echo $this->Js->writeBuffer();?>
	<?php 
		if (Configure::read('debug') == 2) {
			echo $this->element('sql_dump'); 
		}
	?>
	
	<?php echo $this->Html->script(array("index.js","modernizer.js","prefixfree.min.js"));?>
</body>
</html>