<script type="text/javascript" language="javascript" src="/datetimepicker/images/prototype-1.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/prototype-base-extensions.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/prototype-date-extensions.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/behaviour.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/datepicker.js"></script>
<link rel="stylesheet" href="/datetimepicker/images/datepicker.css">
<script type="text/javascript" language="javascript" src="/datetimepicker/images/behaviors.js"></script>

<?php $error_msg = '';?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!-- MAin Content Starts From Here -->

								<form name="frmEditSpecialEvent" action="" method="post"
									enctype="multipart/form-data" onSubmit="return validate()">

								<table width="100%" border="1" cellpadding="1" cellspacing="0"
									bordercolor="#808080" style="border-collapse: collapse">

									<tr height="20">

										<td align="center" class="normalblack_12" width="90%"
											valign="top">

										<table width="100%" border="0" cellpadding="0" cellspacing="0"
											bgcolor="#FFFFFF">

											<tr>

												<!-- Display the message on heading of the page -->

												<td valign="top" class="normalwhite_14" colspan=3
													bgcolor="#808080" align="center"><b>Edit Special Event
												Information</b></td>

											</tr>

											<tr>

												<!-- Display the message on heading of the page -->

												<td valign="top" colspan=3 align="center">&nbsp;</td>

											</tr>

											<tr>

												<td valign="top" colspan=3 align="center"
													class="normalblack_12"><font color="Red"></font>

												</td>

											</tr>

											<tr>

												<td height="35" colspan="3" align="right"
													class="normalblack_12"><FONT color="Red">Fields marked with
												* are mandatory&nbsp;</FONT></td>

											</tr>

											<tr height="20">

												<td valign="top" class="normalwhite_14" colspan=3
													align="center">&nbsp;</td>

											</tr>

											<tr height="20">

												<tr height="20">

												</tr>

												<tr height="20" id="txtEvent">

													<td valign="top" align="right" class="normalblack_12"
														width="30%">Special Event Name <font color="red">*</font>
													</td>

													<td valign="top" align="center" class="normalblack_12">:
													&nbsp;</td>

													<td valign="top" align="left" class="normalblack_12"
														colspan=2><input type="text" name="event_name"
														id="event_name" value=""
														maxlength="30" style="width: 220px;"></td>

												</tr>

												<tr height="20">

													<td valign="top" class="normalwhite_14" colspan=4
														align="center">&nbsp;</td>

												</tr>





												<tr height="20" id="txtHint">

													<td valign="top" align="right" class="normalblack_12"
														width="30%">Location<font color="red"> *</font></td>

													<td valign="top" align="center" class="normalblack_12">:</td>

												<td valign="top" align="left" class="normalblack_12"><textarea
														name="location" id="location" rows="4"
														cols="15" style="width: 220px;"></textarea></td>

												</tr>

												<tr height="20">

													<td valign="top" class="normalwhite_14" colspan=3
														align="center">&nbsp;</td>

													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">Special Event Detail<font color="red"> </font>
														</td>

														<td valign="top" align="center" class="normalblack_12">:</td>

														<td valign="top" align="left" class="normalblack_12"><textarea
															name="event_desc" id="event_desc"
															rows="10" cols="15" style="width: 220px;" class="txt"></textarea></td>

													</tr>

													<tr height="20">

														<td valign="top" class="normalwhite_14" colspan=3
															align="center">&nbsp;</td>

													</tr>

													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">Price(Early Graduation Year)<font color="red">
														*</font></td>

														<td valign="top" align="center" class="normalblack_12">:
														&nbsp;</td>

														<td valign="top" align="left" class="normalblack_12"
															colspan=2><input type="text"
															style="float: left; width: 220px;"
															id="current_price" name="current_price"
															value=""
															onKeyPress="return isNumber(event)" /></td>

													</tr>

													<tr height="20">

														<td valign="top" class="normalwhite_14" colspan=2
															align="center">&nbsp;</td>
														<td colspan="2"
															style="color: #333333; font-size: 12px; margin-left: 50px;">&nbsp;

														</td>

													</tr>

													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">Price(Future Graduation Year)<font
															color="red"> *</font></td>

														<td valign="top" align="center" class="normalblack_12">:
														&nbsp;</td>

														<td valign="top" align="left" class="normalblack_12"
															colspan=2><input type="text"
															style="float: left; width: 220px;"
															name="future_price" id="future_price"
															value=""
															onKeyPress="return isNumber(event)" /></td>

													</tr>

													<tr height="20">

														<td valign="top" class="normalwhite_14" colspan=2
															align="center">&nbsp;</td>
														<td colspan="2"
															style="color: #333333; font-size: 12px; margin-left: 50px;">&nbsp;</td>

													</tr>

													<td valign="top" align="right" class="normalblack_12"
														width="30%">Early Discount Day<font color="red"> *</font>
													</td>

													<td valign="top" align="center" class="normalblack_12">:
													&nbsp;</td>

													<td valign="top" align="left" class="normalblack_12"
														colspan=2>
													
														<?php
															$early_discount_day = array();
															for($i=1;$i<=31;$i++){
																$early_discount_day[$i] = $i;
															}
														?>
													
													
														<?php echo $this->Form->input('early_discount_day', array('type' => 'select', 'empty' => array('select' => 'Select Early Discount Day'), 'style' => 'width: 220px', 'label' => false,  
															'options' => $early_discount_day)); ?>
													</td>

												</tr>



												<td valign="top" class="normalwhite_14" colspan=2
													align="center">&nbsp;</td>
												<td colspan="2"
													style="color: #333333; font-size: 12px; margin-left: 50px;">&nbsp;

												</td>

											</tr>

											<tr height="20">

												<td valign="top" align="right" class="normalblack_12"
													width="30%">Early Discount Price<font color="red"> *</font>
												</td>

												<td valign="top" align="center" class="normalblack_12">:
												&nbsp;</td>

												<td valign="top" align="left" class="normalblack_12"
													colspan=2><input type="text"
													style="float: left; width: 220px;"
													name="early_discount_rate" id="early_discount_rate"
													value=""
													onKeyPress="return isNumber(event)" /></td>

											</tr>



											<td valign="top" class="normalwhite_14" colspan=2
												align="center">&nbsp;</td>
											<td colspan="2"
												style="color: #333333; font-size: 12px; margin-left: 50px;">&nbsp;

											</td>

											</tr>

											<tr height="20">

												<td valign="top" align="right" class="normalblack_12"
													width="30%">Transcript Discount Price<font color="red"> *</font>
												</td>

												<td valign="top" align="center" class="normalblack_12">:
												&nbsp;</td>

												<td valign="top" align="left" class="normalblack_12"
													colspan=2><input type="text"
													style="float: left; width: 220px;"
													name="transcript_discount" id="transcript_discount"
													value=""
													onKeyPress="return isNumber(event)" /></td>

											</tr>

											<tr height="20">

												<td valign="top" class="normalwhite_14" colspan=2
													align="center">&nbsp;</td>
												<td colspan="2"
													style="color: #333333; font-size: 12px; margin-left: 50px;">&nbsp;</td>

											</tr>

											<tr height="20">

												<td valign="top" align="right" class="normalblack_12"
													width="30%">Event Start Date<font color="red"> *</font></td>

												<td valign="top" align="center" class="normalblack_12">:
												&nbsp;</td>

												<td valign="top" align="left" class="normalblack_12"
													colspan=2><input type="text"
													style="float: left; width: 200;" class="datetimepicker_es"
													id="start_date" name="start_date"
													autocomplete="off" value=""></td>

											</tr>

											<tr height="20">

												<td valign="top" class="normalwhite_14" colspan=4
													align="center">&nbsp;</td>

											</tr>





											<tr height="20">

												<td valign="top" align="right" class="normalblack_12"
													width="30%">Status <font color="red"></font></td>

												<td valign="top" align="center" class="normalblack_12">:</td>

												<td valign="top" align="left" class="normalblack_12">
													<?php echo $this->Form->input('status', array('type'=>'select', 'label' => false, 'style' => 'width: 220px',  
															 							  'options' => array('1' => 'ACTIVE', '0' => 'FULL'))); ?>
												</td>

											</tr>

											<tr height="20">

												<td valign="top" class="normalwhite_14" colspan=4
													align="center">&nbsp;</td>

											</tr>

											<tr height="20">

												<td valign="top" align="right" class="normalblack_12"
													width="30%">&nbsp</td>

												<td valign="top" align="center" class="normalblack_12">
												&nbsp</td>

												<td valign="top" align="left" class="normalblack_12"><input
													type="hidden" name="isSubmit" value="save"> <input
													type="submit" name="submit" value="Submit"><!--&nbsp;&nbsp;<input type="reset" name="Submit2" value="Reset">--></td>

											</tr>



											<tr height="20">

												<td valign="top" colspan=3 align="center"
													class="normalblack_12">&nbsp;</td>

											</tr>

											<!-- Upoad File END-->

										</table>

										</td>

									</tr>

								</table>

								</form>

								<!--Main Center Content END --></td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>

<script type="text/javascript">
function validate(){
	if(trimString(document.frmEditSpecialEvent.event_name.value) == ""){
		alert("Please Enter Special Event Name!");
		return false;
		document.frmEditSpecialEvent.event_name.focus();
	}

	if(trimString(document.frmEditSpecialEvent.location.value) == ""){
		alert("Please Enter Special Event Loacation!");
		return false;
		document.frmEditSpecialEvent.location.focus();
	}

	if(document.frmEditSpecialEvent.current_price.value == ""){
		alert("Please Enter Special Event Current Price!");
		return false;
		document.frmEditSpecialEvent.current_price.focus();
	}
	else
	{
		var cur_price=parseInt(document.frmEditSpecialEvent.current_price.value);
		var tranc_disc=parseInt(document.frmEditSpecialEvent.transcript_discount.value);
		var early_disc=parseInt(document.frmEditSpecialEvent.early_discount_rate.value);
		if(cur_price < early_disc)
		{
			alert("Please Enter Current Price Larger then Early Register Discount!");
			return false;
			document.frmEditSpecialEvent.transcript_discount.focus();
		}
		else if(cur_price<tranc_disc)
		{
			alert("Please Enter Current Price Larger then Transcript Discount!");
			return false;
			document.frmEditSpecialEvent.transcript_discount.focus();
		}
	}
	if(document.frmEditSpecialEvent.future_price.value == ""){
		alert("Please Enter Special Event Future Price!");
		return false;
		document.frmEditSpecialEvent.future_price.focus();
	}
	else
	{
		var future_price=parseInt(document.frmEditSpecialEvent.future_price.value);
		var tranc_disc=parseInt(document.frmEditSpecialEvent.transcript_discount.value);
		var early_disc=parseInt(document.frmEditSpecialEvent.early_discount_rate.value);
		if(future_price < early_disc)
		{
			alert("Please Enter Future Price Larger then Early Register Discount!");
			return false;
			document.frmEditSpecialEvent.early_discount_rate.focus();
		}
		else if(future_price<tranc_disc)
		{
			alert("Please Enter Future Price Larger then Transcript Discount!");
			return false;
			document.frmEditSpecialEvent.transcript_discount.focus();
		}
	}
	if(document.frmEditSpecialEvent.Early_Discount_day.value == ""){
		alert("Please Enter Early Discount Day!");
		return false;
		document.frmEditSpecialEvent.Early_Discount_day.focus();
	}

	if(document.frmEditSpecialEvent.early_discount_rate.value == ""){
		alert("Please Enter Early Discount Price!");
		return false;
		document.frmEditSpecialEvent.early_discount_rate.focus();
	}
	else
	{
		var cur_price=parseInt(document.frmEditSpecialEvent.current_price.value);
		var future_price=parseInt(document.frmEditSpecialEvent.future_price.value);
		var early_disc=parseInt(document.frmEditSpecialEvent.early_discount_rate.value);
		if(cur_price > future_price)
		{
			calc_price = future_price;
		}
		else
		{
			calc_price = cur_price;
		}
		if(early_disc > calc_price)
		{
			alert("Please Enter Early Discount Price Smaller then Event Price!");
			return false;
			document.frmEditSpecialEvent.early_discount_rate.focus();
		}
	}

	if(document.frmEditSpecialEvent.transcript_discount.value == ""){
		alert("Please Enter Transcript Discount Price!");
		return false;
		document.frmEditSpecialEvent.transcript_discount.focus();
	}
	else
	{
		var cur_price=parseInt(document.frmEditSpecialEvent.current_price.value);
		var future_price=parseInt(document.frmEditSpecialEvent.future_price.value);
		var tranc_disc=parseInt(document.frmEditSpecialEvent.transcript_discount.value);
		if(cur_price > future_price)
		{
			calc_price = future_price;
		}
		else
		{
			calc_price = cur_price;
		}

		if(tranc_disc > calc_price)
		{
			alert("Please Enter Transcript Discount Price Smaller then Event Price!");
			return false;
			document.frmEditSpecialEvent.transcript_discount.focus();
		}
	}

	if(trimString(document.frmEditSpecialEvent.start_date.value) == ""){
		alert("Please Enter Special Event Start Date!");
		return false;
		document.frmEditSpecialEvent.start_date.focus();
	}
}

</script>
