<table width="100%" cellpadding="3" cellspacing="5">
	<tr>
		<td width="100%" align="center">
		<table width="100%" cellpadding="3" cellspacing="5">

			<tr>

				<td width="100%" align="center">

				<table width="95%" cellpadding="0" cellspacing="3">

					<tr>

						<td width="100%" class="SearchHead"><b>Special Event Register
						Details</b></td>

					</tr>

					<tr>

						<td width="100%" class="GeneralFont">&nbsp;</td>

					</tr>

					<tr>

						<td width="100%">

						<table width="100%" cellspacing="0" cellpadding="2">

							<tr>

								<td width="100%" valign="top">

								<table width="100%" cellspacing="0" cellpadding="3">



									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>First Name</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['firstname']?></td>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Last Name</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['lastname']?></td>

									</tr>



									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Address</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['address_1']?></td>

									</tr>
									
									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Address2</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['address_2']?></td>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>City</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['city']?></td>

									</tr>



									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>State</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['state']?></td>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Zip Code</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['zip']?></td>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Phone Number</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['phone']?></td>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Email Address (for Receipt)</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['email']?></td>

									</tr>



									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Special Event</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEvent['SpecialEvent']['event_name']?></td>

									</tr>



									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Referred by</b></td>

										<td class="normalblack_12" valign="top"><?php echo $specialEventUser['SpecialEventUser']['referred_by']?></td>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Transportation</b></td>

										<td class="normalblack_12" valign="top"><?php if($specialEventUser['SpecialEventUser']['transportation_discount_id']!='0' && $specialEventUser['SpecialEventUser']['transportation_discount_id'] !=''){ echo "Yes";}else{echo "No";}?></td>

									</tr>

									<?php   //echo $fldEventStartDate;

									//echo $fldAddDate;//7day

									$addate =strtotime($specialEventUser['SpecialEventUser']['added_date']);

									$evedate=strtotime($specialEvent['SpecialEvent']['start_date']);

									?>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Early Register</b></td>

										<td class="normalblack_12" valign="top"><?php if($addate<$evedate)

										{

											echo "Yes";

										}

										else

										{

											echo "No";

										}?></td>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Transcript</b></td>

											<?php if(isset($specialEventUser['SpecialEventUser']['transcript'])){?>

										<td class="normalblack_12" valign="top"><a
											href="<?php echo $this->webroot.$specialEventUser['SpecialEventUser']['transcript']; ?>"
											target="_blank">Download Transcript</a></td>

											<?php }else{ ?>

										<td class="normalblack_12" valign="top">No</td>

										<?php }?>

									</tr>

									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%"><b>Coupon</b></td>

										<td class="normalblack_12" valign="top"><?php if(isset($specialEventUser['SpecialEventUser']['coupon_number']))

										{ echo "Yes";}else{ echo "No";}?></td>

									</tr>
								
									<tr>

										<td class="normalblack_12" valign="top" height="25"
											width="40%" colspan="2"><input type=button value="Close"
											onClick="javascript:window.close();"></td>
									</tr>
								</table>
								</td>
							</tr>

						</table>

						</td>

					</tr>

				</table>

				</td>

			</tr>

			<tr>

				<td width="100%" align="center">&nbsp;</td>

			</tr>

		</table>
		</td>
	</tr>
	<tr>
		<td width="100%" align="center">&nbsp;</td>
	</tr>
</table>
