<table width="100%" cellpadding="3" cellspacing="5">
	<tr>
		<td width="100%" align="center">
		<table width="95%" cellpadding="0" cellspacing="3">
			<tr>
				<td width="100%" class="SearchHead"><b>HS/AAU Team Details</b></td>
			</tr>
			<tr>
				<td width="100%" class="GeneralFont">&nbsp;</td>
			</tr>
			<tr>
				<td width="100%">
				<table width="100%" cellspacing="0" cellpadding="2">
					<tr>
						<td width="100%" valign="top">
						<table width="100%" cellspacing="0" cellpadding="3">

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Name</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $schoolDetail['HsAauTeam']['school_name']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Address</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $schoolDetail['HsAauTeam']['address']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>City</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $schoolDetail['HsAauTeam']['city']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>state</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $schoolDetail['HsAauTeam']['state']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Zip
								Code</b></td>
								<td class="normalblack_12" valign="top"><?php echo $schoolDetail['HsAauTeam']['zip']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Enrollment</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $schoolDetail['HsAauTeam']['enrollment']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Status</b>
								</td>
								<td class="normalblack_12" valign="top">
									<?php
										if ($schoolDetail['HsAauTeam']['status'] == 1) {
											echo "ACTIVE";
										} else {
											echo "DEACTIVE";
										}
									?>
								</td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" colspan="2">&nbsp;</td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									colspan="2"><input type=button value="Close"
									onClick="javascript:window.close();"></td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td width="100%" align="center">&nbsp;</td>
	</tr>
</table>
