<script type="text/javascript" language="javascript" src="/datetimepicker/images/prototype-1.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/prototype-base-extensions.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/prototype-date-extensions.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/behaviour.js"></script>
<script type="text/javascript" language="javascript" src="/datetimepicker/images/datepicker.js"></script>
<link rel="stylesheet" href="/datetimepicker/images/datepicker.css">
<script type="text/javascript" language="javascript" src="/datetimepicker/images/behaviors.js"></script>

<?php $error_msg = '';?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
						<table cellSpacing=0 cellPadding=0 width=900 border=0>
							<tr>
								<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
								<td valign=top width=1%>&nbsp;</td>
								<?php $s_image = "/img/spacer.gif"; ?>
								<td width=10><img src="<?php echo $s_image?>" height="1"
									width="1"></td>
								<td valign=top width=""><!-- MAin Content Starts From Here -->

								<form name="frmEditEvent" action="" method="post"
									enctype="multipart/form-data" onsubmit="return validate()">

								<table width="100%" border="1" cellpadding="1" cellspacing="0"
									bordercolor="#808080" style="border-collapse: collapse">

									<tr height="20">
										<td align="center" class="normalblack_12" width="90%"
											valign="top">
										<table width="100%" border="0" cellpadding="0" cellspacing="0"
											bgcolor="#FFFFFF">
											<tr>
												<!-- Display the message on heading of the page -->
												<td valign="top" class="normalwhite_14" colspan=3
													bgcolor="#808080" align="center"><b>Edit Event Information</b>
												</td>
											</tr>
											<tr>
												<!-- Display the message on heading of the page -->
												<td valign="top" colspan=3 align="center">&nbsp;</td>
											</tr>
											<tr>
												<td valign="top" colspan=3 align="center"
													class="normalblack_12"><font color="Red"></font>
												</td>
											</tr>
											<tr>
												<td height="35" colspan="3" align="right"
													class="normalblack_12"><FONT color="Red">Fields marked with
												* are mandatory&nbsp;</FONT></td>
											</tr>
											<tr height="20">
												<td valign="top" class="normalwhite_14" colspan=3
													align="center">&nbsp;</td>
											</tr>
											<tr height="20">
												<tr height="20">
													<td valign="top" align="right" class="normalblack_12"
														width="30%">Sport <font color="red">*</font></td>
													<td valign="top" align="center" class="normalblack_12">:</td>
													<td valign="top" align="left" class="normalblack_12">
														<?php echo $this->Form->input('sport_id', array('type'=>'select', 'empty' => array('select' => 'Select Sport'), 'label' => false, 'style' => 'width: 220px;', 'value' => $event['Event']['sport_id'], 'options' => $sportList)); ?>
													</td>

												</tr>

												<tr height="20">

													<td valign="top" class="normalwhite_14" colspan=3
														align="center">&nbsp;</td>

												</tr>

												<tr height="20">

													<td valign="top" align="right" class="normalblack_12"
														width="30%">Home team<font color="red">*</font></td>

													<td valign="top" align="center" class="normalblack_12">:</td>

													<td valign="top" align="left" class="normalblack_12">																										
														<?php echo $this->Form->input('home_team', array('type'=>'select', 'empty' => array('select' => 'Select Home Team'), 'label' => false, 'style' => 'width: 220px;', 'value' => $event['Event']['home_team'], 'options' => $categoryList)); ?>
													</td>

												</tr>

												<tr height="20">

													<td valign="top" class="normalwhite_14" colspan=3
														align="center">&nbsp;</td>

												</tr>

												<tr height="20">

													<td valign="top" align="right" class="normalblack_12"
														width="30%">Away Team<font color="red">*</font></td>

													<td valign="top" align="center" class="normalblack_12">:</td>

													<td valign="top" align="left" class="normalblack_12">
														<?php echo $this->Form->input('away_team', array('type'=>'select', 'empty' => array('select' => 'Select Away Team'), 'label' => false, 'style' => 'width: 220px;', 'value' => $event['Event']['away_team'], 'options' => $categoryList)); ?>
													</td>

												</tr>

												<tr height="20">

													<td valign="top" class="normalwhite_14" colspan=3
														align="center">&nbsp;</td>

												</tr>

												<tr height="20" id="txtEvent">

													<td valign="top" align="right" class="normalblack_12"
														width="30%">Event Name <font color="red">*</font></td>

													<td valign="top" align="center" class="normalblack_12">:
													&nbsp;</td>

													<td valign="top" align="left" class="normalblack_12"
														colspan=2><input type="text" name="event_name"
														id="event_name" value="<?php echo $event['Event']['event_name']?>"
														maxlength="30" style="width: 220px;"></td>

												</tr>

												<tr height="20">

													<td valign="top" class="normalwhite_14" colspan=4
														align="center">&nbsp;</td>

												</tr>

												<tr height="20" id="txtHint">

													<td valign="top" align="right" class="normalblack_12"
														width="30%">Location<font color="red"> *</font></td>

													<td valign="top" align="center" class="normalblack_12">:</td>												
													<td valign="top" align="left" class="normalblack_12"><textarea
														name="location" id="location" rows="4"
														cols="15" style="width: 220px;"><?php echo $event['Event']['location']?></textarea></td>

												</tr>

												<tr height="20">

													<td valign="top" class="normalwhite_14" colspan=3
														align="center">&nbsp;</td>

													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">Event Detail<font color="red"> </font></td>

														<td valign="top" align="center" class="normalblack_12">:</td>

														<td valign="top" align="left" class="normalblack_12"><textarea
															name="event_desc" id="event_desc"
															rows="10" cols="15" style="width: 220px;" class="txt"><?php echo $event['Event']['event_desc']?></textarea></td>

													</tr>

													<tr height="20">

														<td valign="top" class="normalwhite_14" colspan=3
															align="center">&nbsp;</td>

													</tr>



													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">Event Start Date<font color="red"> *</font></td>

														<td valign="top" align="center" class="normalblack_12">:
														&nbsp;</td>

														<td valign="top" align="left" class="normalblack_12"
															colspan=2><input type="text"
															style="float: left; width: 200;"
															class="datetimepicker_es" id="start_date"
															name="start_date" autocomplete="off"
															value="<?php echo $event['Event']['start_date']?>"></td>

													</tr>

													<tr height="20">

														<td valign="top" class="normalwhite_14" colspan=4
															align="center">&nbsp;</td>

													</tr>

													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">Event End Date<font color="red"> *</font></td>

														<td valign="top" align="center" class="normalblack_12">:
														&nbsp;</td>

														<td valign="top" align="left" class="normalblack_12"
															colspan=2><input type="text"
															style="float: left; width: 200;"
															class="datetimepicker_es" id="end_date"
															name="end_date" autocomplete="off"
															value="<?php echo $event['Event']['end_date']?>"></td>

													</tr>

													<tr height="20">

														<td valign="top" class="normalwhite_14" colspan=4
															align="center">&nbsp;</td>

													</tr>



													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">Status <font color="red"></font></td>

														<td valign="top" align="center" class="normalblack_12">:</td>

														<td valign="top" align="left" class="normalblack_12"><select
															name="status"
															style="width: 220px; font-size: 12px;">

															<option value=1
															<?if($event['Event']['status'] ==1 ){ echo "selected"; }?>>ACTIVE</option>

															<option value=0
															<?if($event['Event']['status'] ==0 ){ echo "selected"; }?>>DE-ACTIVE</option>

														</select></td>

													</tr>

													<tr height="20">

														<td valign="top" class="normalwhite_14" colspan=4
															align="center">&nbsp;</td>

													</tr>

													<tr height="20">

														<td valign="top" align="right" class="normalblack_12"
															width="30%">&nbsp</td>

														<td valign="top" align="center" class="normalblack_12">
														&nbsp</td>

														<td valign="top" align="left" class="normalblack_12"><input
															type="hidden" name="isSubmit" value="save"> <input
															type="submit" name="submit" value="Submit"><!--&nbsp;&nbsp;<input type="reset" name="Submit2" value="Reset">--></td>

													</tr>



													<tr height="20">

														<td valign="top" colspan=3 align="center"
															class="normalblack_12">&nbsp;</td>

													</tr>

													<!-- Upoad File END-->
										
										</table>

										</td>

									</tr>

								</table>

								</form>

								<!--Main Center Content END --></td>
							</tr>
						</table>
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>

<script type="text/javascript">
function validate(){	
	var error_msg = "";
	if(trimString(document.frmEditEvent.event_name.value) == ""){	
		error_msg += "Please Enter Event Name! \n";
	} else {	
		if(hasSpecialCharaters(document.frmEditEvent.event_name.value)){	
			error_msg += "Enter valid Event Name! \n";	
		}	
	}
	
	if(trimString(document.frmEditEvent.sport.value) == "select"){	
		error_msg += "Please Select Sport! \n";	
	}
	
	if(trimString(document.frmEditEvent.home_team.value) == "select"){	
		error_msg += "Please Select Home Team! \n";	
	}
	
	if(trimString(document.frmEditEvent.away_team.value) == "select"){	
		error_msg += "Please Select Away Team! \n";	
	}
	
	if(trimString(document.frmEditEvent.location.value) == ""){	
		error_msg += "Please Enter Event Loacation! \n";	
	}
	
	if(trimString(document.frmEditEvent.start_date.value) == ""){	
		error_msg += "Please Enter Event Start Date! \n";	
	}
	
	if(trimString(document.frmEditEvent.end_date.value) == ""){	
		error_msg += "Please Enter End Event Date! \n";	
	}

	if(error_msg!=''){	
		alert(error_msg);	
		return false;	
	} else {	
		return true;	
	}
}

</script>
