<table width="100%" cellpadding="3" cellspacing="5">
	<tr>
		<td width="100%" align="center">
		<table width="95%" cellpadding="0" cellspacing="3">
			<tr>
				<td width="100%" class="SearchHead"><b>Event Details</b></td>
			</tr>
			<tr>
				<td width="100%" class="GeneralFont">&nbsp;</td>
			</tr>
			<tr>
				<td width="100%">
				<table width="100%" cellspacing="0" cellpadding="2">
					<tr>
						<td width="100%" valign="top">
						<table width="100%" cellspacing="0" cellpadding="3">
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Event
								Name</b></td>
								<td class="normalblack_12" valign="top"><?php echo $eventDet['Event']['event_name']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Sport</b>
								</td>
								<td class="normalblack_12" valign="top"><?php echo $sportName['Sport']['name']?></td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Home
								Team</b></td>
								<td class="normalblack_12" valign="top"><?php echo $teamName['HsAauTeam']['school_name']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Away
								Team</b></td>
								<td class="normalblack_12" valign="top"><?php echo $awayTeam['HsAauTeam']['school_name']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Event
								Detail</b></td>
								<td class="normalblack_12" valign="top"><?php echo $eventDet['Event']['event_desc']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Event
								Location</b></td>
								<td class="normalblack_12" valign="top"><?php echo $eventDet['Event']['location']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Start
								Date</b></td>
								<td class="normalblack_12" valign="top"><?php echo $eventDet['Event']['start_date']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>End
								date</b></td>
								<td class="normalblack_12" valign="top"><?php echo $eventDet['Event']['end_date']?></td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"><b>Status</b>
								</td>
								<td class="normalblack_12" valign="top"><?php if($eventDet['Event']['status']==1){ ?>Active<?php }else { ?>DeActive<?php  } ?>
								</td>
							</tr>

							<tr>
								<td class="normalblack_12" valign="top" colspan="2">&nbsp;</td>
							</tr>
							<tr>
								<td class="normalblack_12" valign="top" height="25" width="40%"
									colspan="2"><input type=button value="Close"
									onClick="javascript:window.close();"></td>
							</tr>
						</table
						
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td width="100%" align="center">&nbsp;</td>
	</tr>
</table>
