<?php $error_msg = '';?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

    <tr>
        <td height=120><?php echo $this->element('admin_header');?></td>
    </tr>
    <tr>
        <td>&nbsp;</td>
    </tr>
    <tr>
        <td class="heading">
            <table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
                <tr>
                    <td>
                        <table cellSpacing=0 cellPadding=1 width=780 border=0>
                            <tr>
                                <td bgColor=#ffffff>
                                    <table cellSpacing=0 cellPadding=0 width=900 border=0>
                                        <tr>
                                            <td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
                                            <td valign=top width=1%>&nbsp;</td>
                                            <?php $s_image = "/img/spacer.gif"; ?>
                                            <td width=10><img src="<?php echo $s_image?>" height="1" width="1"></td>
                                            <td valign=top width=""><!-- MAin Content Starts From Here -->

                                                <form name="frmaddscoutreport" action="<?php echo $this->Html->url('/admin/ScoutReport/addmultiplereport')?>" method="post" enctype="multipart/form-data">
                                                    <table width="100%" border="1" cellpadding="1" cellspacing="0" bordercolor="#808080" style="border-collapse: collapse">
                                                        <tr height="20">
                                                            <td align="center" class="normalblack_12" width="90%" valign="top">
                                                                <table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Title<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="title" id="title" required value="" maxlength="50" style="width: 220px">
                                                                            <input type="hidden" name="event_id" id="event_id" value="<?php echo $event_id ; ?>" />
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Event Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="event_name" disabled="disabled" value="<?php if(isset($EventDetail['SpecialEvent']['event_name'])) { echo $EventDetail['SpecialEvent']['event_name'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <?php for($i=0 ; $i< 5 ; $i++){ ?>

                                                                    <input type="hidden" name="report[<?php echo $i ; ?>][athlete]" id="athlete-<?php echo $i ; ?>" value="0" />
                                                                    <tr>
                                                                        <td valign="top" class="normalwhite_14" colspan=3 bgcolor="#808080" align="center"><b>Add Scout Report Info</b></td>
                                                                    </tr>

                                                                    <tr>
                                                                        <td valign="top" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td valign="top" colspan=3 align="center"
                                                                            class="normalblack_12"><font color="Red"></font>
                                                                        </td>
                                                                    </tr>
                                                                    <tr>
                                                                        <td height="35" colspan="3" align="right"
                                                                            class="normalblack_12"><FONT color="Red">Fields marked with * are mandatory&nbsp;</FONT></td>
                                                                    </tr>
                                                                    

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=4 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">First Name<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" class="report" name="report[<?php echo $i ; ?>][firstname]" id="firstname-<?php echo $i ; ?>" required value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Last Name<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][lastname]" id="lastname-<?php echo $i ; ?>" required value="<?php if(isset($athelte_data['lastname'])) { echo $athelte_data['lastname'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>



                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Email<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="email" name="report[<?php echo $i ; ?>][email]" id="email-<?php echo $i ; ?>" required value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Graduating Class<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][class]" id="class-<?php echo $i ; ?>" required style="width: 220px" >
                                                                                        <?php $Classes = $this->Register->getClasses() ; ?>
                                                                                <option value="">Select Class</option>
                                                                                        <?php foreach($Classes as $key=>$Class) { ?>
                                                                                <option value="<?php echo $key ; ?>"  ><?php echo $Class ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>

																	
																	
																	<tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">State<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][state]" id="state-<?php echo $i ; ?>" onchange="javascript:updateteams( this.value , '<?php echo $i ; ?>');" required style="width: 220px">
                                                                                        <?php $states = $this->Register->getStates() ; ?>
                                                                                <option value="">Select State</option>
                                                                                        <?php foreach($states as $key=>$state) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['state']) && $athelte_data['state']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $state ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">High School<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][high_school]" id="high_school-<?php echo $i ; ?>" required style="width: 220px">
                                                                                <option value="">Select High School</option>
                                                                                        <?php if(isset($athelte_data['state']) && $athelte_data['state'] != '' && isset($athelte_data['high_school'])) {
                                                                                            $schools = $this->Register->getHsScout($athelte_data['state']) ;
                                                                                            if($schools) {
                                                                                                foreach($schools as $key=>$school) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['high_school']) && $athelte_data['high_school']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $school ; ?></option>
                                                                                                <?php }
                                                                                            } } ?>
                                                                            </select>
                                                                                <!--<input type="text" name="high_school" id="high_school" required value="" maxlength="50" style="width: 220px">-->
                                                                        </td>

                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Primary Aau Team<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][primary_aau_team]" id="primary_aau_team-<?php echo $i ; ?>" required  style="width: 220px">
                                                                                <option value="">Select Primary Team</option>
                                                                                        <?php if(isset($athelte_data['state']) && $athelte_data['state'] != '' && isset($athelte_data['primary_aau_team'])) {
                                                                                            $schools = $this->Register->getHsScout($athelte_data['state']) ;
                                                                                            if($schools) {
                                                                                                foreach($schools as $key=>$school) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['primary_aau_team']) && $athelte_data['primary_aau_team']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $school ; ?></option>
                                                                                                <?php }
                                                                                            } } ?>
                                                                            </select>
                                                                            <!--    <input type="text" name="primary_aau_team" id="primary_aau_team" required value="" maxlength="50" style="width: 220px">-->
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Secondary Aau Team<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][secondary_aau_team]" id="secondary_aau_team-<?php echo $i ; ?>" required  style="width: 220px">
                                                                                <option value="">Select Secondary Team</option>
                                                                                        <?php if(isset($athelte_data['state']) && $athelte_data['state'] != '' && isset($athelte_data['secondary_aau_team'])) {
                                                                                            $schools = $this->Register->getHsScout($athelte_data['state']) ;
                                                                                            if($schools) {
                                                                                                foreach($schools as $key=>$school) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['secondary_aau_team']) && $athelte_data['secondary_aau_team']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $school ; ?></option>
                                                                                                <?php }
                                                                                            } } ?>
                                                                            </select>
                                                                            <!--    <input type="text" name="secondary_aau_team" id="secondary_aau_team" required value="" maxlength="50" style="width: 220px">-->
                                                                        </td>
                                                                    </tr>


																	<tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Best Game<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][best_game]" id="best_game" required style="width: 220px">
                                                                                        <?php $games = $this->Register->getgames() ; ?>
                                                                                <option value="">Select Best game</option>
                                                                                        <?php foreach($games as $key=>$game) { ?>
                                                                                <option value="<?php echo $key ; ?>" ><?php echo $game ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>



                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Other Game<font color="red">*</font></td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][other_game]" id="other_game" required style="width: 220px">
                                                                                        <?php $games = $this->Register->getgames() ; ?>
                                                                                <option value="">Select Other game</option>
                                                                                        <?php foreach($games as $key=>$game) { ?>
                                                                                <option value="<?php echo $key ; ?>" ><?php echo $game ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>


																	<tbody>
																		<tr>
																			<td colspan="3" align="left" >
																				<a href="javascript:void(0);" style="margin-left:20px;" onclick="ShowHide('<?php echo $i ; ?>')" class="expand"> Show Other Fields </a>
																			</td>
																		</tr>
																	<tbody class="collapse_<?php echo $i ; ?>" style="display:none;">

																	<tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Height</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][height]" id="height-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $heights = $this->Register->getHeights() ; ?>
                                                                                <option value="">Select Height</option>
                                                                                        <?php foreach($heights as $key=>$height) { ?>
                                                                                <option value="<?php echo $key ; ?>"  ><?php echo $height ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Weight</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][weight]" id="weight-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $Weights = $this->Register->getWeights() ; ?>
                                                                                <option value="">Select Weight</option>
                                                                                        <?php foreach($Weights as $key=>$Weight) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['weight']) && $athelte_data['weight']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $Weight ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Primary Position</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][primary_position]" id="primary_position-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $pri_positions = $this->Register->getPositions() ; ?>
                                                                                <option value="">Select Primary Positions</option>
                                                                                        <?php foreach($pri_positions as $key=>$primary) { ?>
                                                                                <option value="<?php echo $key ; ?>" ><?php echo $primary ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Secondary Position</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][secondary_position]" id="secondary_position-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $sec_positions = $this->Register->getPositions() ; ?>
                                                                                <option value="">Select Secondary Positions</option>
                                                                                        <?php foreach($sec_positions as $key=>$secondary) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['secondary_position']) && $athelte_data['secondary_position']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $secondary ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Wingspan</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][wingspan_id]" id="wingspan_id-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $wingspans = $this->Register->getWingspans() ; ?>
                                                                                <option value=0>Select Wingspan</option>
                                                                                        <?php foreach($wingspans as $key=>$wingspan) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['wingspan_id']) && $athelte_data['wingspan_id']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $wingspan ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">GPA</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][gpa]" id="gpa-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $gpas = $this->Register->getGPA() ; ?>
                                                                                <option value="">Select Gpa</option>
                                                                                        <?php foreach($gpas as $key=>$gpa) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['gpa']) && $athelte_data['gpa']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $gpa ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Sat Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][sat_score]" id="sat_score-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $sats = $this->Register->getSatScore() ; ?>
                                                                                <option value="">Select Sat Score</option>
                                                                                        <?php foreach($sats as $key=>$sat) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['sat_score']) && $athelte_data['sat_score']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $sat ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Act Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <select name="report[<?php echo $i ; ?>][act_score]" id="act_score-<?php echo $i ; ?>" style="width: 220px">
                                                                                        <?php $acts = $this->Register->getActScore() ; ?>
                                                                                <option value="">Select Act Score</option>
                                                                                        <?php foreach($acts as $key=>$act) { ?>
                                                                                <option value="<?php echo $key ; ?>" <?php if(isset($athelte_data['act_score']) && $athelte_data['act_score']== $key) { echo "Selected='Selected'" ; } ?> ><?php echo $act ; ?></option>
                                                                                        <?php } ?>
                                                                            </select>
                                                                        </td>
                                                                    </tr>




                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Street Address</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][street_address]" id="street_address-<?php echo $i ; ?>" value="<?php if(isset($athelte_data['street_address'])) { echo $athelte_data['street_address'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">City</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][city]" id="city-<?php echo $i ; ?>" value="<?php if(isset($athelte_data['city'])) { echo $athelte_data['city'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Zip Code</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][zip_code]" id="zip_code-<?php echo $i ; ?>" value="<?php if(isset($athelte_data['zip_code'])) { echo $athelte_data['zip_code'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    
                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Jersey Number</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][jersey_number]" id="jersey_number-<?php echo $i ; ?>" value="<?php if(isset($athelte_data['jersey_number'])) { echo $athelte_data['jersey_number'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Reach</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][reach]" id="reach" value="<?php if(isset($athelte_data['reach'])) { echo $athelte_data['reach'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Strengths</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][strengths]" id="strengths"  value="<?php if(isset($athelte_data['strengths'])) { echo $athelte_data['strengths'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Weakness</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][weakness]"   value="<?php if(isset($athelte_data['weakness'])) { echo $athelte_data['weakness'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>



                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">60 seconds of threes</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][60_seconds_of_threes]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Elite High Major Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_elite_high_major_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Ncca High Major Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_high_major_score]"   value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Mid Major Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_mid_major_score]"  value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Low Major Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_low_major_score]"  value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Division II Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_division_II_score]"  value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>



                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Division III Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_division_III_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division I Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][junior_college_division_I_score]"  value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division II Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][junior_college_division_II_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>



                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division III Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][junior_college_division_III_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division I Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][naia_division_I_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division II Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][naia_division_II_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division III Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][naia_division_III_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Nccaa Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][nccaa_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Club Level Score</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][club_level_score]" value="" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Colleges Shown Interest(Enter College Name with comma seprated)</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][colleges_shown_interest]" value="<?php if(isset($athelte_data['colleges_shown_interest'])) { echo $athelte_data['colleges_shown_interest'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Colleges Offered Scholarship(Enter College Name with comma seprated)</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][colleges_offered_scholarship]" value="<?php if(isset($athelte_data['colleges_offered_scholarship'])) { echo $athelte_data['colleges_offered_scholarship'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Phone Number</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][phone_number]" value="<?php if(isset($athelte_data['phone_number'])) { echo $athelte_data['phone_number'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Father First Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][father_firstname]" value="<?php if(isset($athelte_data['father_firstname'])) { echo $athelte_data['father_firstname'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Father Last Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][father_lastname]"  value="<?php if(isset($athelte_data['father_lastname'])) { echo $athelte_data['father_lastname'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Father Phone Number</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][father_phone]" value="<?php if(isset($athelte_data['father_phone'])) { echo $athelte_data['father_phone'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Mother First Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][mother_firstname]" value="<?php if(isset($athelte_data['mother_firstname'])) { echo $athelte_data['mother_firstname'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Mother Last Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][mother_lastname]" value="<?php if(isset($athelte_data['mother_lastname'])) { echo $athelte_data['mother_lastname'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Mother Phone Number</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][mother_phone]" value="<?php if(isset($athelte_data['mother_phone'])) { echo $athelte_data['mother_phone'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][high_school_coach_name]" value="<?php if(isset($athelte_data['high_school_coach_name'])) { echo $athelte_data['high_school_coach_name'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach  Phone Number</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][high_school_coach_phone]" value="<?php if(isset($athelte_data['high_school_coach_phone'])) { echo $athelte_data['high_school_coach_phone'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>



                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach  Email</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="email" name="report[<?php echo $i ; ?>][high_school_coach_email]" value="<?php if(isset($athelte_data['high_school_coach_email'])) { echo $athelte_data['high_school_coach_email'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][primary_aau_coach_name]" value="<?php if(isset($athelte_data['primary_aau_coach_name'])) { echo $athelte_data['primary_aau_coach_name'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Phone</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][primary_aau_coach_phone]"  value="<?php if(isset($athelte_data['primary_aau_coach_phone'])) { echo $athelte_data['primary_aau_coach_phone'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Email</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="email" name="report[<?php echo $i ; ?>][primary_aau_coach_email]" value="<?php if(isset($athelte_data['primary_aau_coach_email'])) { echo $athelte_data['primary_aau_coach_email'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Name</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][secondary_aau_coach_name]" value="<?php if(isset($athelte_data['secondary_aau_coach_name'])) { echo $athelte_data['secondary_aau_coach_name'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Phone</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="number" name="report[<?php echo $i ; ?>][secondary_aau_coach_phone]" value="<?php if(isset($athelte_data['secondary_aau_coach_phone'])) { echo $athelte_data['secondary_aau_coach_phone'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Email</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="email" name="report[<?php echo $i ; ?>][secondary_aau_coach_email]" value="<?php if(isset($athelte_data['secondary_aau_coach_email'])) { echo $athelte_data['secondary_aau_coach_email'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>



                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Facebook</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][facebook]" value="<?php if(isset($athelte_data['facebook'])) { echo $athelte_data['facebook'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Twitter</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][twitter]"  value="<?php if(isset($athelte_data['twitter'])) { echo $athelte_data['twitter'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Lane Agility</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="text" name="report[<?php echo $i ; ?>][lane_agility]" value="<?php if(isset($athelte_data['lane_agility'])) { echo $athelte_data['lane_agility'] ; } ?>" maxlength="50" style="width: 220px">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Description</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <textarea name="report[<?php echo $i ; ?>][description]" style="width: 220px" id="description-<?php echo $i ; ?>" ><?php if(isset($athelte_data['description'])) { echo $athelte_data['description'] ; } ?></textarea>
                                                                        </td>
                                                                    </tr>




                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Picture</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <input type="file" name="picture[<?php echo $i ; ?>]" id="picture">
                                                                        </td>
                                                                    </tr>


                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>

                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">Notes</td>
                                                                        <td valign="top" align="center" class="normalblack_12">:</td>
                                                                        <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                            <textarea name="report[<?php echo $i ; ?>][notes]" style="width: 220px" ><?php if(isset($athelte_data['notes'])) { echo $athelte_data['notes'] ; } ?></textarea>
                                                                        </td>
                                                                    </tr>

																	
																	</tbody>
																	
                                                                    
                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>
                                                                    <tr height="20">
                                                                        <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                                                    </tr>

                                                                    

                                                                    <?php }   ?>




                                                                    <tr height="20">
                                                                        <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                    </tr>
                                                                    <tr height="20">
                                                                        <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                                                    </tr>
                                                                    <tr height="20">
                                                                        <td valign="top" align="right" class="normalblack_12" width="30%">&nbsp</td>
                                                                        <td valign="top" align="center" class="normalblack_12">&nbsp</td>
                                                                        <td valign="top" align="left" class="normalblack_12">
                                                                            <input type="hidden" name="isSubmit" value="save">
                                                                            <input type="submit" name="submit" value="Submit">&nbsp;&nbsp;
                                                                            
                                                                        </td>
                                                                    </tr>
                                                                    <tr height="20">
                                                                        <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                                                    </tr>
                                                                </table>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </form>
                                                
                                                <!--Main Center Content END -->
                                            </td>
                                            
                                        </tr>

                                                                    
                                    </table>
                                </td>
                            </tr>
                        </table>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <?php echo $this->element('admin_footer');?>
</table>

<link type="text/css" rel="stylesheet" href="<?php echo Router::fullBaseUrl().$this->base;?>/css.php?file=jquery-ui.css" />
<script type="text/javascript" src="<?php echo Router::fullBaseUrl().$this->base;?>/js.php?file=jquery-1.10.1.min.js,jquery-ui.js,expand.js"></script>
<!--<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>-->

<style>
  .ui-autocomplete {
    max-height: 100px;
    overflow-y: auto;
    /* prevent horizontal scrollbar */
    overflow-x: hidden;
  }
  /* IE 6 doesn't support max-height
   * we use height instead, but this forces the menu to always be this tall
   */
  * html .ui-autocomplete {
    height: 100px;
  }
  .ui-autocomplete-loading {
    background: white url("<?php echo $this->Html->url('/img/loading.gif')?>") right center no-repeat;
  }
  </style>
  
<script type="text/javascript">

function ShowHide(index){
	if(index != ''){
		$(".collapse_"+index).toggle() ;
	}
}


    function validate(){
        var error_msg = "";
        if(trimString(document.frmaddscoutreport.firstname.value) == ""){
            error_msg += "Please Enter Scout First Name! \n";
        }
        else{
            if(hasSpecialCharaters(document.frmaddscoutreport.firstname.value)){
                error_msg += "Don`t enter special characters in Scout First Name! \n";
            }
        }
        if(trimString(document.frmaddscoutreport.lastname.value) == ""){
            error_msg += "Please Enter Scout Last Name! \n";
        }
        else{
            if(hasSpecialCharaters(document.frmaddscoutreport.lastname.value)){
                error_msg += "Don`t enter special characters in Scout Last Name! \n";
            }
        }
        if(error_msg!=''){
            alert(error_msg);
            return false;
        } else {
            return true;
        }
    }


    /*   $(function(){
        var url = '<?php //echo $this->webroot . "admin/ScoutReport/getHSScout" ; ?>' ;
        $("#state").change(function(){
            var state = $("#state").val() ;
            if(state != ''){
                $.ajax({
                    url: url ,
                    //dataType: "json",
                    data: {
                        state_id : $("#state").val()
                    },
                    success: function( data ) {
                        $("#high_school").html(data) ;
                        $("#primary_aau_team").html(data) ;
                        $("#secondary_aau_team").html(data) ;
                    }
                });
            }
        });
    });
     */
    function updateteams(state,index) {
        var url = '<?php echo $this->webroot . "admin/ScoutReport/getHSScout" ; ?>' ;
        //alert(state);alert(index);
        if(state != '' && index != ''){
            $.ajax({
                url: url ,
                //dataType: "json",
                data: {
                    state_id : state
                },
                success: function( data ) {
                    $("#high_school-"+index+"").html(data) ;
                    $("#primary_aau_team-"+index+"").html(data) ;
                    $("#secondary_aau_team-"+index+"").html(data) ;
                }
            });
        }
    }



    $(function(){
      var url1 = '<?php echo $this->Html->url('/admin/ScoutReport/autoComplete_scout_multiple'); ?>' ;
    $(".report").autocomplete({
      source: function( request, response ){ var id = this.element.attr('id');
        $.ajax({
          url: url1 ,
          dataType: "json",
          data: {
            q: request.term , tag: id
          },
          success: function( data ) { 
            response( data );
          }
        });
      },
      minLength: 1,
      select: function( event, ui ) {
                if(ui.item){
                    var url2 = '<?php echo $this->Html->url('/admin/ScoutReport/getAthleteInfo_multiple'); ?>' ;
                    $.ajax({
                        url: url2 ,
                        data: {
                            athlete: ui.item.other , tag: ui.item.tag
                        },
                        success: function(data) {  
                            var obj = $.parseJSON(data);
                            var split = obj.tag.split('-');
                            $("#athlete-"+split[1]).val(obj.athleteDetail.Athlete.id);
                            $("#lastname-"+split[1]).val(obj.athleteDetail.Athlete.lastname);
                            $("#email-"+split[1]).val(obj.athleteDetail.Athlete.email);
                            $("#class-"+split[1]).val(obj.athleteDetail.Athlete.class);
                            $("#height-"+split[1]).val(obj.athleteDetail.Athlete.height);
                            $("#weight-"+split[1]).val(obj.athleteDetail.Athlete.weight);
                            $("#primary_position-"+split[1]).val(obj.athleteDetail.Athlete.primary_position);
                            $("#secondary_position-"+split[1]).val(obj.athleteDetail.Athlete.secondary_position);
                            $("#gpa-"+split[1]).val(obj.athleteDetail.Athlete.gpa);
                            $("#sat_score-"+split[1]).val(obj.athleteDetail.Athlete.sat_score);
                            $("#act_score-"+split[1]).val(obj.athleteDetail.Athlete.act_score);
                            $("#wingspan_id-"+split[1]).val(obj.athleteDetail.Athlete.wingspan);
                            $("#city-"+split[1]).val(obj.athleteDetail.Athlete.city);
                            if(obj.athleteDetail.Athlete.state != ''){
                                $("#state-"+split[1]).val(obj.athleteDetail.Athlete.state);
                                $("#state-"+split[1]).trigger("change");
                            }
                            $("#zip_code-"+split[1]).val(obj.athleteDetail.Athlete.zip);
                            $("#jersey_number-"+split[1]).val(obj.athleteDetail.Athlete.jersey_number);
                            $("#description-"+split[1]).val(obj.athleteDetail.Athlete.description);

                        }
                    });
                }
            }
    });

      });


</script>