<?php $error_msg = '';?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

    <tr>
            <td height=120><?php echo $this->element('admin_header');?></td>
    </tr>
    <tr>
            <td>&nbsp;</td>
    </tr>
    <tr>
            <td class="heading">
            <table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
                    <tr>
                            <td>
                            <table cellSpacing=0 cellPadding=1 width=780 border=0>
                                    <tr>
                                            <td bgColor=#ffffff>
                                            <table cellSpacing=0 cellPadding=0 width=900 border=0>
                                                    <tr>
                                                            <td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
                                                            <td valign=top width=1%>&nbsp;</td>
                                                            <?php $s_image = "/img/spacer.gif"; ?>
                                                            <td width=10><img src="<?php echo $s_image?>" height="1" width="1"></td>
                                                            <td valign=top width=""><!-- MAin Content Starts From Here -->

                                                            <form name="frmaddscoutreport" action="" method="post" enctype="multipart/form-data" onsubmit="return validate()">
                                                            <table width="100%" border="1" cellpadding="1" cellspacing="0" bordercolor="#808080" style="border-collapse: collapse">
                                                                    <tr height="20">
                                                                            <td align="center" class="normalblack_12" width="90%" valign="top">
                                                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
                                                                                            <tr>
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 bgcolor="#808080" align="center"><b>Add Scout Report Info</b></td>
                                                                                            </tr>
                                                                                            <tr>
                                                                                                    <td valign="top" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>
                                                                                            <tr>
                                                                                                    <td valign="top" colspan=3 align="center"
                                                                                                            class="normalblack_12"><font color="Red"></font>
                                                                                                    </td>
                                                                                            </tr>
                                                                                            <tr>
                                                                                                    <td height="35" colspan="3" align="right"
                                                                                                            class="normalblack_12"><FONT color="Red">Fields marked with * are mandatory&nbsp;</FONT></td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=4 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">First Name<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="firstname" id="firstname" required value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Last Name<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="lastname" id="lastname" required value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Email<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="email" id="email" required value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Graduating Class<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="class" id="class" required style="width: 220px" >
                                                                                                            <?php $Classes = $this->Register->getClasses() ; ?>
                                                                                                            <option value="">Select Class</option>
                                                                                                            <?php foreach($Classes as $key=>$Class){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $Class ; ?></option>
                                                                                                            <?php } ?>
                                                                                                        </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Height</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="height" id="height" style="width: 220px">
                                                                                                            <?php $heights = $this->Register->getHeights() ; ?>
                                                                                                            <option value="">Select Height</option>
                                                                                                            <?php foreach($heights as $key=>$height){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $height ; ?></option>
                                                                                                            <?php } ?>
                                                                                                        </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                                                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Weight</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="weight" id="weight" style="width: 220px">
                                                                                                            <?php $Weights = $this->Register->getWeights() ; ?>
                                                                                                            <option value="">Select Weight</option>
                                                                                                            <?php foreach($Weights as $key=>$Weight){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $Weight ; ?></option>
                                                                                                            <?php } ?>
                                                                                                        </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary Position</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="primary_position" id="primary_position" style="width: 220px">
                                                                                                            <?php $pri_positions = $this->Register->getPositions() ; ?>
                                                                                                            <option value="">Select Primary Positions</option>
                                                                                                            <?php foreach($pri_positions as $key=>$primary){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $primary ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary Position</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="secondary_position" id="secondary_position" style="width: 220px">
                                                                                                            <?php $sec_positions = $this->Register->getPositions() ; ?>
                                                                                                            <option value="">Select Secondary Positions</option>
                                                                                                            <?php foreach($sec_positions as $key=>$secondary){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $secondary ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Wingspan</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="wingspan_id" id="wingspan_id" style="width: 220px">
                                                                                                            <?php $wingspans = $this->Register->getWingspans() ; ?>
                                                                                                            <option value=0>Select Wingspan</option>
                                                                                                            <?php foreach($wingspans as $key=>$wingspan){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $wingspan ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">GPA</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="gpa" id="gpa" style="width: 220px">
                                                                                                            <?php $gpas = $this->Register->getGPA() ; ?>
                                                                                                            <option value="">Select Gpa</option>
                                                                                                            <?php foreach($gpas as $key=>$gpa){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $gpa ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Sat Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="sat_score" id="sat_score" style="width: 220px">
                                                                                                            <?php $sats = $this->Register->getSatScore() ; ?>
                                                                                                            <option value="">Select Sat Score</option>
                                                                                                            <?php foreach($sats as $key=>$sat){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $sat ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Act Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="act_score" id="act_score" style="width: 220px">
                                                                                                            <?php $acts = $this->Register->getActScore() ; ?>
                                                                                                            <option value="">Select Act Score</option>
                                                                                                            <?php foreach($acts as $key=>$act){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $act ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>




                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Street Address</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="street_address" id="street_address" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">City</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="city" id="city" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Zip Code</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="zip_code" id="zip_code" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">State<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="state" id="state" required style="width: 220px">
                                                                                                            <?php $states = $this->Register->getStates() ; ?>
                                                                                                            <option value="">Select State</option>
                                                                                                            <?php foreach($states as $key=>$state){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $state ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                           

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="high_school" id="high_school" required style="width: 220px">
                                                                                                            <option value="">Select High School</option>
                                                                                                        </select>
                                                                                                            <!--<input type="text" name="high_school" id="high_school" required value="" maxlength="50" style="width: 220px">-->
                                                                                                    </td>
                                                                                              
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary Aau Team<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="primary_aau_team" id="primary_aau_team" required style="width: 220px">
                                                                                                            <option value="">Select Primary Team</option>
                                                                                                    </select>
                                                                                                    <!--    <input type="text" name="primary_aau_team" id="primary_aau_team" required value="" maxlength="50" style="width: 220px">-->
                                                                                                  </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary Aau Team<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="secondary_aau_team" id="secondary_aau_team" required style="width: 220px">
                                                                                                            <option value="">Select Secondary Team</option>
                                                                                                    </select>
                                                                                                    <!--    <input type="text" name="secondary_aau_team" id="secondary_aau_team" required value="" maxlength="50" style="width: 220px">-->
                                                                                                  </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Jersey Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="jersey_number" id="jersey_number" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Best Game<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="best_game" id="best_game" required style="width: 220px">
                                                                                                            <?php $games = $this->Register->getgames() ; ?>
                                                                                                            <option value="">Select Best game</option>
                                                                                                            <?php foreach($games as $key=>$game){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $game ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Other Game<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="other_game" id="other_game" required style="width: 220px">
                                                                                                            <?php $games = $this->Register->getgames() ; ?>
                                                                                                            <option value="">Select Other game</option>
                                                                                                            <?php foreach($games as $key=>$game){ ?>
                                                                                                            <option value="<?php echo $key ; ?>"><?php echo $game ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Reach</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="reach" id="reach" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Strengths</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="strengths" id="strengths"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Weakness</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="weakness" id="weakness"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">60 seconds of threes</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="60_seconds_of_threes" id="60_seconds_of_threes" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Elite High Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="ncca_elite_high_major_score" id="ncca_elite_high_major_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca High Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="ncca_high_major_score" id="ncca_high_major_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Mid Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="ncca_mid_major_score" id="ncca_mid_major_score" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Low Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="ncca_low_major_score" id="ncca_low_major_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Division II Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="ncca_division_II_score" id="ncca_division_II_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Division III Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="ncca_division_III_score" id="ncca_division_III_score" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division I Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="junior_college_division_I_score" id="junior_college_division_I_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division II Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="junior_college_division_II_score" id="junior_college_division_II_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division III Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="junior_college_division_III_score" id="junior_college_division_III_score" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division I Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="naia_division_I_score" id="naia_division_I_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division II Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="naia_division_II_score" id="naia_division_II_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division III Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="naia_division_III_score" id="naia_division_III_score" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Nccaa Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="nccaa_score" id="nccaa_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Club Level Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="club_level_score" id="club_level_score"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Colleges Shown Interest(Enter College Name with comma seprated)</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="colleges_shown_interest" id="colleges_shown_interest" value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Colleges Offered Scholarship(Enter College Name with comma seprated)</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="colleges_offered_scholarship" id="colleges_offered_scholarship"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="phone_number" id="phone_number"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Father First Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="father_firstname" id="father_firstname"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Father Last Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="father_lastname" id="father_lastname"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Father Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="father_phone" id="father_phone"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Mother First Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="mother_firstname" id="mother_firstname"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Mother Last Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="mother_lastname" id="mother_lastname"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Mother Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="mother_phone" id="mother_phone"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="high_school_coach_name" id="high_school_coach_name"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach  Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="high_school_coach_phone" id="high_school_coach_phone"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach  Email</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="high_school_coach_email" id="high_school_coach_email"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="primary_aau_coach_name" id="primary_aau_coach_name"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Phone</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="primary_aau_coach_phone" id="primary_aau_coach_phone"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Email</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="primary_aau_coach_email" id="primary_aau_coach_email"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="secondary_aau_coach_name" id="secondary_aau_coach_name"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Phone</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="secondary_aau_coach_phone" id="secondary_aau_coach_phone"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Email</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="secondary_aau_coach_email" id="secondary_aau_coach_email"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Facebook</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="facebook" id="facebook"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Twitter</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="twitter" id="twitter"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Lane Agility</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="lane_agility" id="lane_agility"  value="" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Description</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <textarea name="description" id="description" style="width: 220px" ></textarea>
                                                                                                    </td>
                                                                                            </tr>




                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Picture</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="file" name="picture" id="picture">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>
                                                                                            <tr height="20">
                                                                                                    <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                                                                            </tr>
                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">&nbsp</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">&nbsp</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12">
                                                                                                            <input type="hidden" name="isSubmit" value="save">
                                                                                                            <input type="submit" name="submit" value="Submit">&nbsp;&nbsp;
                                                                                                            <input type="reset" name="Submit2" value="Reset">&nbsp;&nbsp;
                                                                                                    </td>
                                                                                            </tr>
                                                                                            <tr height="20">
                                                                                                    <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                                                                            </tr>
                                                                                    </table>
                                                                            </td>
                                                                    </tr>
                                                            </table>
                                                            </form>
                                                            <!--Main Center Content END --></td>
                                                    </tr>
                                            </table>
                                            </td>
                                    </tr>
                            </table>
                            </td>
                    </tr>
            </table>
            </td>
    </tr>
    <?php echo $this->element('admin_footer');?>
</table>
<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>

<script type="text/javascript">
function validate(){	
    var error_msg = "";
    if(trimString(document.frmaddscoutreport.firstname.value) == ""){
            error_msg += "Please Enter Scout First Name! \n";
    }
    else{
            if(hasSpecialCharaters(document.frmaddscoutreport.firstname.value)){
                    error_msg += "Don`t enter special characters in Scout First Name! \n";
            }
    }
    if(trimString(document.frmaddscoutreport.lastname.value) == ""){
            error_msg += "Please Enter Scout Last Name! \n";
    }
    else{
            if(hasSpecialCharaters(document.frmaddscoutreport.lastname.value)){
                    error_msg += "Don`t enter special characters in Scout Last Name! \n";
            }
    }
    if(error_msg!=''){
            alert(error_msg);
            return false;
    } else {
            return true;
    }
}

//function getHs(state){
//    if(state != ''){
//        var url = '<?php echo $this->Html->url('getHSScout'); ?>' ;
//                $.ajax({
//                        url: url ,
//                        dataType: "json",
//                        data: {
//                            state_id : $("#state").val()
//                        },
//                        success: function( data ) {
//                            alert(data);
//                        }
//                    });
//            }
//}

$(function(){
    var url = '<?php echo $this->webroot . "admin/ScoutReport/getHSScout" ; ?>' ;
        $("#state").change(function(){
            var state = $("#state").val() ;
            if(state != ''){
                $.ajax({
                        url: url ,
                        //dataType: "json",
                        data: {
                            state_id : $("#state").val()
                        },
                        success: function( data ) {
                            $("#high_school").html(data) ;
                            $("#primary_aau_team").html(data) ;
                            $("#secondary_aau_team").html(data) ;
                        }
                    });
            }
      });
      });
</script>