<?php $error_msg = '';?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

    <tr>
            <td height=120><?php echo $this->element('admin_header');?></td>
    </tr>
    <tr>
            <td>&nbsp;</td>
    </tr>
    <tr>
            <td class="heading">
            <table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
                    <tr>
                            <td>
                            <table cellSpacing=0 cellPadding=1 width=780 border=0>
                                    <tr>
                                            <td bgColor=#ffffff>
                                            <table cellSpacing=0 cellPadding=0 width=900 border=0>
                                                    <tr>
                                                            <td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
                                                            <td valign=top width=1%>&nbsp;</td>
                                                            <?php $s_image = "/img/spacer.gif"; ?>
                                                            <td width=10><img src="<?php echo $s_image?>" height="1" width="1"></td>
                                                            <td valign=top width=""><!-- MAin Content Starts From Here -->

                                                            <form name="frmaddscoutreport" action="" method="post" enctype="multipart/form-data">
                                                            <table width="100%" border="1" cellpadding="1" cellspacing="0" bordercolor="#808080" style="border-collapse: collapse">
                                                                    <tr height="20">
                                                                            <td align="center" class="normalblack_12" width="90%" valign="top">
                                                                                    <table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">

                                                                                        <tr height="20">
                                                                                            <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                        </tr>

                                                                                        <tr height="20">
                                                                                            <td valign="top" align="right" class="normalblack_12" width="30%">Title<font color="red">*</font></td>
                                                                                            <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                            <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                <input type="text" name="title" id="title" required value="<?php if(isset($ScoutReportMain['ScoutReports']['title'])){ echo $ScoutReportMain['ScoutReports']['title'] ; } ?>" maxlength="50" style="width: 220px">
                                                                                                <input type="hidden" name="event_id" id="event_id" value="<?php if(isset($ScoutReportMain['ScoutReports']['event_id'])){ echo $ScoutReportMain['ScoutReports']['event_id'] ; }  ?>" />
                                                                                                <input type="hidden" id="total_reports" value="<?php  echo count($ScoutReports) ;   ?>" />
                                                                                            </td>
                                                                                        </tr>

                                                                                        <tr height="20">
                                                                                            <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                        </tr>

                                                                                        <tr height="20">
                                                                                            <td valign="top" align="right" class="normalblack_12" width="30%">Event Name</td>
                                                                                            <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                            <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                <input type="text" name="event_name" disabled="disabled" value="<?php if(isset($EventDetail['SpecialEvent']['event_name'])){ echo $EventDetail['SpecialEvent']['event_name'] ; } ?>" maxlength="50" style="width: 220px">
                                                                                            </td>
                                                                                        </tr>

                                                                                        <tr height="20">
                                                                                            <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                        </tr>

                                                                                        <tr height="20">
                                                                                            <td valign="top" align="left" colspan="3" class="normalblack_12"><a id="add_more" href="javascript:void(0);" style="margin-left:20px;">Add more athelete to report</a></td>
                                                                                        </tr>

                                                                                        <tr height="20">
                                                                                            <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                        </tr>


                                                                                        <?php if($ScoutReports){
                                                                                            foreach($ScoutReports as $i=>$ScoutReport){ ?>

                                                                                        <tr>
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 bgcolor="#808080" align="center"><b>Edit Scout Report Info</b></td>
                                                                                            </tr>
                                                                                            <tr>
                                                                                                    <td valign="top" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>
                                                                                            <tr>
                                                                                                    <td valign="top" colspan=3 align="center"
                                                                                                            class="normalblack_12"><font color="Red"></font>
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <input type="hidden" name="report[<?php echo $i ; ?>][scout_report_athletes_id]" id="scout_report_athletes_id-<?php echo $i ; ?>" value="<?php echo $ScoutReport['ScoutReport']['id'] ; ?>" />
                                                                                            <input type="hidden" name="report[<?php echo $i ; ?>][athlete]" id="athlete-<?php echo $i ; ?>" value="<?php echo $ScoutReport['ScoutReport']['athlete'] ; ?>" />

                                                                                            <tr>
                                                                                                    <td height="35" colspan="3" align="right"
                                                                                                            class="normalblack_12"><FONT color="Red">Fields marked with * are mandatory&nbsp;</FONT></td>
                                                                                            </tr>

                                                                                           
                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=4 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">First Name<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" class="report" name="report[<?php echo $i ; ?>][firstname]" id="firstname-<?php echo $i ; ?>" required value="<?php echo $ScoutReport['ScoutReport']['firstname'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Last Name<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][lastname]" id="lastname-<?php echo $i ; ?>" required value="<?php echo $ScoutReport['ScoutReport']['lastname'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                             <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Email<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="report[<?php echo $i ; ?>][email]" id="email-<?php echo $i ; ?>" required value="<?php echo $ScoutReport['ScoutReport']['email'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Graduating Class<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][class]" id="class-<?php echo $i ; ?>" required style="width: 220px" required >
                                                                                                            <?php $Classes = $this->Register->getClasses() ; ?>
                                                                                                            <option value="">Select Class</option>
                                                                                                            <?php foreach($Classes as $key=>$Class){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['class'] == $key){ ?> selected <?php } ?> ><?php echo $Class ; ?></option>
                                                                                                            <?php } ?>
                                                                                                        </select>
                                                                                                    </td>
                                                                                            </tr>


																							<tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">State<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="report[<?php echo $i ; ?>][state]" id="state-<?php echo $i ; ?>" required onchange="javascript:updateteams( this.value , '<?php echo $i ; ?>');" style="width: 220px">
                                                                                                            <?php $states = $this->Register->getStates() ; ?>
                                                                                                            <option value="">Select State</option>
                                                                                                            <?php foreach($states as $key=>$state){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['state'] == $key){ ?> selected <?php } ?> ><?php echo $state ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="report[<?php echo $i ; ?>][high_school]" id="high_school-<?php echo $i ; ?>" required style="width: 220px">
                                                                                                            <?php if($ScoutReport['ScoutReport']['high_school'] != '' && $ScoutReport['ScoutReport']['state'] != '' ){ ?>
                                                                                                            <?php $hschools = $this->Register->getHsScout($ScoutReport['ScoutReport']['state']) ; ?>
                                                                                                            <?php foreach($hschools as $key=>$hschool){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['high_school'] == $key){ ?> selected <?php } ?> ><?php echo $hschool ; ?></option>
                                                                                                            <?php } ?>
                                                                                                             <?php }else{ ?>
                                                                                                            <option value="">Select High School</option>
                                                                                                            <?php } ?>
                                                                                                        </select>
                                                                                                            <!--<input type="text" name="high_school" id="high_school" required value="" maxlength="50" style="width: 220px">-->
                                                                                                    </td>

                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary Aau Team<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][primary_aau_team]" id="primary_aau_team-<?php echo $i ; ?>" required style="width: 220px">
                                                                                                        <?php if($ScoutReport['ScoutReport']['primary_aau_team'] != '' && $ScoutReport['ScoutReport']['state'] != '' ){ ?>
                                                                                                            <?php $hschools = $this->Register->getHsScout($ScoutReport['ScoutReport']['state']) ; ?>
                                                                                                            <?php foreach($hschools as $key=>$hschool){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['primary_aau_team'] == $key){ ?> selected <?php } ?> ><?php echo $hschool ; ?></option>
                                                                                                            <?php } ?>
                                                                                                             <?php }else{ ?>
                                                                                                            <option value="">Select Primary Team</option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    <!--    <input type="text" name="primary_aau_team" id="primary_aau_team" required value="" maxlength="50" style="width: 220px">-->
                                                                                                  </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary Aau Team<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][secondary_aau_team]" id="secondary_aau_team-<?php echo $i ; ?>" required style="width: 220px">
                                                                                                        <?php if($ScoutReport['ScoutReport']['secondary_aau_team'] != '' && $ScoutReport['ScoutReport']['state'] != '' ){ ?>
                                                                                                            <?php $hschools = $this->Register->getHsScout($ScoutReport['ScoutReport']['state']) ; ?>
                                                                                                            <?php foreach($hschools as $key=>$hschool){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['secondary_aau_team'] == $key){ ?> selected <?php } ?> ><?php echo $hschool ; ?></option>
                                                                                                            <?php } ?>
                                                                                                             <?php }else{ ?>
                                                                                                            <option value="">Select Secondary Team</option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    <!--    <input type="text" name="secondary_aau_team" id="secondary_aau_team" required value="" maxlength="50" style="width: 220px">-->
                                                                                                  </td>
                                                                                            </tr>



																							<tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Best Game<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][best_game]" id="best_game-<?php echo $i ; ?>" required style="width: 220px">
                                                                                                            <?php $games = $this->Register->getgames() ; ?>
                                                                                                            <option value="">Select Best game</option>
                                                                                                            <?php foreach($games as $key=>$game){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['best_game'] == $key){ ?> selected <?php } ?> ><?php echo $game ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Other Game<font color="red">*</font></td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][other_game]" id="other_game-<?php echo $i ; ?>" required style="width: 220px">
                                                                                                            <?php $games = $this->Register->getgames() ; ?>
                                                                                                            <option value="">Select Other game</option>
                                                                                                            <?php foreach($games as $key=>$game){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['other_game'] == $key){ ?> selected <?php } ?> ><?php echo $game ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tbody>
                                                                                                <tr>
                                                                                                    <td colspan="3" align="left" >
                                                                                                        <a href="javascript:void(0);" style="margin-left:20px;" onclick="ShowHide('<?php echo $i ; ?>')" class="expand"> Show Other Fields </a>
                                                                                                    </td>
                                                                                                </tr>
                                                                                            <tbody class="collapse_<?php echo $i ; ?>" style="display:none;">

                                                                                                <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Height</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="report[<?php echo $i ; ?>][height]" id="height-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $heights = $this->Register->getHeights() ; ?>
                                                                                                            <option value="">Select Height</option>
                                                                                                            <?php foreach($heights as $key=>$height){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['height'] == $key){ ?> selected <?php } ?> ><?php echo $height ; ?></option>
                                                                                                            <?php } ?>
                                                                                                        </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                                                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Weight</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <select name="report[<?php echo $i ; ?>][weight]" id="weight-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $Weights = $this->Register->getWeights() ; ?>
                                                                                                            <option value="">Select Weight</option>
                                                                                                            <?php foreach($Weights as $key=>$Weight){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['weight'] == $key){ ?> selected <?php } ?> ><?php echo $Weight ; ?></option>
                                                                                                            <?php } ?>
                                                                                                        </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary Position</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][primary_position]" id="primary_position-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $pri_positions = $this->Register->getPositions() ; ?>
                                                                                                            <option value="">Select Primary Positions</option>
                                                                                                            <?php foreach($pri_positions as $key=>$primary){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['primary_position'] == $key){ ?> selected <?php } ?> ><?php echo $primary ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary Position</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][secondary_position]" id="secondary_position-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $sec_positions = $this->Register->getPositions() ; ?>
                                                                                                            <option value="">Select Secondary Positions</option>
                                                                                                            <?php foreach($sec_positions as $key=>$secondary){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['secondary_position'] == $key){ ?> selected <?php } ?> ><?php echo $secondary ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Wingspan</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][wingspan_id]" id="wingspan_id-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $wingspans = $this->Register->getWingspans() ; ?>
                                                                                                            <option value=0>Select Wingspan</option>
                                                                                                            <?php foreach($wingspans as $key=>$wingspan){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['wingspan_id'] == $key){ ?> selected <?php } ?> ><?php echo $wingspan ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">GPA</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][gpa]" id="gpa-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $gpas = $this->Register->getGPA() ; ?>
                                                                                                            <option value="">Select Gpa</option>
                                                                                                            <?php foreach($gpas as $key=>$gpa){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['gpa'] == $key){ ?> selected <?php } ?> ><?php echo $gpa ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Sat Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][sat_score]" id="sat_score-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $sats = $this->Register->getSatScore() ; ?>
                                                                                                            <option value="">Select Sat Score</option>
                                                                                                            <?php foreach($sats as $key=>$sat){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['sat_score'] == $key){ ?> selected <?php } ?> ><?php echo $sat ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Act Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                    <select name="report[<?php echo $i ; ?>][act_score]" id="act_score-<?php echo $i ; ?>"  style="width: 220px">
                                                                                                            <?php $acts = $this->Register->getActScore() ; ?>
                                                                                                            <option value="">Select Act Score</option>
                                                                                                            <?php foreach($acts as $key=>$act){ ?>
                                                                                                            <option value="<?php echo $key ; ?>" <?php if($ScoutReport['ScoutReport']['act_score'] == $key){ ?> selected <?php } ?> ><?php echo $act ; ?></option>
                                                                                                            <?php } ?>
                                                                                                    </select>
                                                                                                    </td>
                                                                                            </tr>




                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Street Address</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][street_address]" id="street_address-<?php echo $i ; ?>"  value="<?php echo $ScoutReport['ScoutReport']['street_address'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">City</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][city]" id="city-<?php echo $i ; ?>"  value="<?php echo $ScoutReport['ScoutReport']['city'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Zip Code</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][zip_code]" id="zip_code-<?php echo $i ; ?>"  value="<?php echo $ScoutReport['ScoutReport']['zip_code'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Jersey Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][jersey_number]" id="jersey_number-<?php echo $i ; ?>"  value="<?php echo $ScoutReport['ScoutReport']['jersey_number'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Reach</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][reach]" id="reach"  value="<?php echo $ScoutReport['ScoutReport']['reach'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Strengths</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][strengths]" id="strengths"  value="<?php echo $ScoutReport['ScoutReport']['strengths'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Weakness</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][weakness]" id="weakness"  value="<?php echo $ScoutReport['ScoutReport']['weakness'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>




                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">60 seconds of threes</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][60_seconds_of_threes]" id="60_seconds_of_threes" value="<?php echo $ScoutReport['ScoutReport']['60_seconds_of_threes'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Elite High Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_elite_high_major_score]" id="ncca_elite_high_major_score"  value="<?php echo $ScoutReport['ScoutReport']['ncca_elite_high_major_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca High Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_high_major_score]" id="ncca_high_major_score"  value="<?php echo $ScoutReport['ScoutReport']['ncca_high_major_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Mid Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_mid_major_score]" id="ncca_mid_major_score" value="<?php echo $ScoutReport['ScoutReport']['ncca_mid_major_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Low Major Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_low_major_score]" id="ncca_low_major_score"  value="<?php echo $ScoutReport['ScoutReport']['ncca_low_major_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Division II Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_division_II_score]" id="ncca_division_II_score"  value="<?php echo $ScoutReport['ScoutReport']['ncca_division_II_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Ncca Division III Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][ncca_division_III_score]" id="ncca_division_III_score" value="<?php echo $ScoutReport['ScoutReport']['ncca_division_III_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division I Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][junior_college_division_I_score]" id="junior_college_division_I_score"  value="<?php if(isset($ScoutReport['ScoutReport']['junior_college_division_I_score'])) { echo $ScoutReport['ScoutReport']['junior_college_division_I_score'] ; } ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division II Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][junior_college_division_II_score]" id="junior_college_division_II_score"  value="<?php if(isset($ScoutReport['ScoutReport']['junior_college_division_II_score'])) { echo $ScoutReport['ScoutReport']['junior_college_division_II_score'] ; } ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Junior College Division III Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][junior_college_division_III_score]" id="junior_college_division_III_score" value="<?php if(isset($ScoutReport['ScoutReport']['junior_college_division_III_score'])) { echo $ScoutReport['ScoutReport']['junior_college_division_III_score'] ; } ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division I Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][naia_division_I_score]" id="naia_division_I_score"  value="<?php echo $ScoutReport['ScoutReport']['naia_division_I_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division II Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][naia_division_II_score]" id="naia_division_II_score"  value="<?php echo $ScoutReport['ScoutReport']['naia_division_II_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Naia Division III Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][naia_division_III_score]" id="naia_division_III_score" value="<?php echo $ScoutReport['ScoutReport']['naia_division_III_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Nccaa Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][nccaa_score]" id="nccaa_score"  value="<?php echo $ScoutReport['ScoutReport']['nccaa_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Club Level Score</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][club_level_score]" id="club_level_score"  value="<?php echo $ScoutReport['ScoutReport']['club_level_score'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Colleges Shown Interest(Enter College Name with comma seprated)</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][colleges_shown_interest]" id="colleges_shown_interest" value="<?php echo $ScoutReport['ScoutReport']['colleges_shown_interest'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Colleges Offered Scholarship(Enter College Name with comma seprated)</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][colleges_offered_scholarship]" id="colleges_offered_scholarship"  value="<?php echo $ScoutReport['ScoutReport']['colleges_offered_scholarship'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][phone_number]" id="phone_number"  value="<?php echo $ScoutReport['ScoutReport']['phone_number'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Father First Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][father_firstname]" id="father_firstname"  value="<?php echo $ScoutReport['ScoutReport']['father_firstname'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Father Last Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][father_lastname]" id="father_lastname"  value="<?php echo $ScoutReport['ScoutReport']['father_lastname'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Father Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][father_phone]" id="father_phone"  value="<?php echo $ScoutReport['ScoutReport']['father_phone'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Mother First Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][mother_firstname]" id="mother_firstname"  value="<?php echo $ScoutReport['ScoutReport']['mother_firstname'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Mother Last Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][mother_lastname]" id="mother_lastname"  value="<?php echo $ScoutReport['ScoutReport']['mother_lastname'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Mother Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][mother_phone]" id="mother_phone"  value="<?php echo $ScoutReport['ScoutReport']['mother_phone'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][high_school_coach_name]" id="high_school_coach_name"  value="<?php echo $ScoutReport['ScoutReport']['high_school_coach_name'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach  Phone Number</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][high_school_coach_phone]" id="high_school_coach_phone"  value="<?php echo $ScoutReport['ScoutReport']['high_school_coach_phone'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">High School Coach  Email</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="report[<?php echo $i ; ?>][high_school_coach_email]" id="high_school_coach_email"  value="<?php echo $ScoutReport['ScoutReport']['high_school_coach_email'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][primary_aau_coach_name]" id="primary_aau_coach_name"  value="<?php echo $ScoutReport['ScoutReport']['primary_aau_coach_name'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Phone</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][primary_aau_coach_phone]" id="primary_aau_coach_phone"  value="<?php echo $ScoutReport['ScoutReport']['primary_aau_coach_phone'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Primary AAU Coach Email</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="report[<?php echo $i ; ?>][primary_aau_coach_email]" id="primary_aau_coach_email"  value="<?php echo $ScoutReport['ScoutReport']['primary_aau_coach_email'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Name</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][secondary_aau_coach_name]" id="secondary_aau_coach_name"  value="<?php echo $ScoutReport['ScoutReport']['secondary_aau_coach_name'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Phone</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="number" name="report[<?php echo $i ; ?>][secondary_aau_coach_phone]" id="secondary_aau_coach_phone"  value="<?php echo $ScoutReport['ScoutReport']['secondary_aau_coach_phone'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Secondary AAU Coach Email</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="email" name="report[<?php echo $i ; ?>][secondary_aau_coach_email]" id="secondary_aau_coach_email"  value="<?php echo $ScoutReport['ScoutReport']['secondary_aau_coach_email'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Facebook</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][facebook]" id="facebook"  value="<?php echo $ScoutReport['ScoutReport']['facebook'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Twitter</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][twitter]" id="twitter"  value="<?php echo $ScoutReport['ScoutReport']['twitter'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Lane Agility</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="text" name="report[<?php echo $i ; ?>][lane_agility]" id="lane_agility"  value="<?php echo $ScoutReport['ScoutReport']['lane_agility'] ; ?>" maxlength="50" style="width: 220px">
                                                                                                    </td>
                                                                                            </tr>


                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Description</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <textarea name="report[<?php echo $i ; ?>][description]" id="description-<?php echo $i ; ?>" style="width: 220px" ><?php echo $ScoutReport['ScoutReport']['description'] ; ?>
                                                                                                        </textarea>
                                                                                                    </td>
                                                                                            </tr>




                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Picture</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                            <input type="file" name="picture[<?php echo $i ; ?>]" id="picture">
                                                                                                            <?php if($ScoutReport['ScoutReport']['picture'] != '') { ?>
                                                                                                            <img src="<?php echo $this->webroot . "/app/webroot/img/scoutreport/" . $ScoutReport['ScoutReport']['picture'] ; ?>" alt="<?php echo $ScoutReport['ScoutReport']['firstname'] . " " . $ScoutReport['ScoutReport']['lastname'] ; ?>" width="150" height="150" >
                                                                                                            <?php } ?>
                                                                                                    </td>
                                                                                            </tr>



                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>

                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">Notes</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">:</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12" colspan=2>
                                                                                                        <textarea name="report[<?php echo $i ; ?>][notes]" id="notes" style="width: 220px" ><?php echo $ScoutReport['ScoutReport']['notes'] ; ?>
                                                                                                        </textarea>
                                                                                                    </td>
                                                                                            </tr>



                                                                                            </tbody>



                                                                                        <?php    }

                                                                                            } ?>

                                                                                            <tr>
                                                                                                <td  class="normalwhite_14" id="new_form_html" colspan="3" width="100%">

                                                                                                </td>
                                                                                            </tr>

                                                                                            
                                                                                            
                                                                                            <tr height="20">
                                                                                                    <td valign="top" class="normalwhite_14" colspan=3 align="center">&nbsp;</td>
                                                                                            </tr>
                                                                                            <tr height="20">
                                                                                                    <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                                                                            </tr>
                                                                                            <tr height="20">
                                                                                                    <td valign="top" align="right" class="normalblack_12" width="30%">&nbsp</td>
                                                                                                    <td valign="top" align="center" class="normalblack_12">&nbsp</td>
                                                                                                    <td valign="top" align="left" class="normalblack_12">
                                                                                                            <input type="hidden" name="isSubmit" value="save">
                                                                                                            <input type="submit" name="submit" value="Submit">&nbsp;&nbsp;
                                                                                                            
                                                                                                    </td>
                                                                                            </tr>
                                                                                            <tr height="20">
                                                                                                    <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                                                                            </tr>
                                                                                    </table>
                                                                            </td>
                                                                    </tr>
                                                            </table>
                                                            </form>
                                                            <!--Main Center Content END --></td>
                                                    </tr>
                                            </table>
                                            </td>
                                    </tr>
                            </table>
                            </td>
                    </tr>
            </table>
            </td>
    </tr>
    <?php echo $this->element('admin_footer');?>
</table>
<link type="text/css" rel="stylesheet" href="<?php echo Router::fullBaseUrl().$this->base;?>/css.php?file=jquery-ui.css" />
<script type="text/javascript" src="<?php echo Router::fullBaseUrl().$this->base;?>/js.php?file=jquery-1.10.1.min.js,jquery-ui.js"></script>
<!--<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>-->

<style>
  .ui-autocomplete {
    max-height: 100px;
    overflow-y: auto;
    /* prevent horizontal scrollbar */
    overflow-x: hidden;
  }
  /* IE 6 doesn't support max-height
   * we use height instead, but this forces the menu to always be this tall
   */
  * html .ui-autocomplete {
    height: 100px;
  }
  .ui-autocomplete-loading {
    background: white url("<?php echo $this->Html->url('/img/loading.gif')?>") right center no-repeat;
  }
  </style>

<script type="text/javascript">
  /*  $('.expand').on('click', function (e) {
    e.preventDefault();
    $(".collapse").toggle() ;
});*/

function ShowHide(index){
	if(index != ''){
		$(".collapse_"+index).toggle() ;
	}
}

function validate(){
    var error_msg = "";
    if(trimString(document.frmaddscoutreport.firstname.value) == ""){
            error_msg += "Please Enter Scout First Name! \n";
    }
    else{
            if(hasSpecialCharaters(document.frmaddscoutreport.firstname.value)){
                    error_msg += "Don`t enter special characters in Scout First Name! \n";
            }
    }
    if(trimString(document.frmaddscoutreport.lastname.value) == ""){
            error_msg += "Please Enter Scout Last Name! \n";
    }
    else{
            if(hasSpecialCharaters(document.frmaddscoutreport.lastname.value)){
                    error_msg += "Don`t enter special characters in Scout Last Name! \n";
            }
    }
    if(error_msg!=''){
            alert(error_msg);
            return false;
    } else {
            return true;
    }
}


function updateteams(state,index) {
        var url = '<?php echo $this->webroot . "admin/ScoutReport/getHSScout" ; ?>' ;
        //alert(state);alert(index);
        if(state != '' && index != ''){
            $.ajax({
                url: url ,
                //dataType: "json",
                data: {
                    state_id : state
                },
                success: function( data ) {
                    $("#high_school-"+index+"").html(data) ;
                    $("#primary_aau_team-"+index+"").html(data) ;
                    $("#secondary_aau_team-"+index+"").html(data) ;
                }
            });
        }
    }

      $(function(){
      var url1 = '<?php echo $this->Html->url('/admin/ScoutReport/autoComplete_scout_multiple'); ?>' ;
       $(".report").autocomplete({
      source: function( request, response ){ var id = this.element.attr('id');
        $.ajax({
          url: url1 ,
          dataType: "json",
          data: {
            q: request.term , tag: id
          },
          success: function( data ) {
            response( data );
          }
        });
      },
      minLength: 1,
      select: function( event, ui ) {
                if(ui.item){
                    var url2 = '<?php echo $this->Html->url('/admin/ScoutReport/getAthleteInfo_multiple'); ?>' ;
                    $.ajax({
                        url: url2 ,
                        data: {
                            athlete: ui.item.other , tag: ui.item.tag
                        },
                        success: function(data) {
                            var obj = $.parseJSON(data);
                            var split = obj.tag.split('-');
                            $("#athlete-"+split[1]).val(obj.athleteDetail.Athlete.id);
                            $("#lastname-"+split[1]).val(obj.athleteDetail.Athlete.lastname);
                            $("#email-"+split[1]).val(obj.athleteDetail.Athlete.email);
                            $("#class-"+split[1]).val(obj.athleteDetail.Athlete.class);
                            $("#height-"+split[1]).val(obj.athleteDetail.Athlete.height);
                            $("#weight-"+split[1]).val(obj.athleteDetail.Athlete.weight);
                            $("#primary_position-"+split[1]).val(obj.athleteDetail.Athlete.primary_position);
                            $("#secondary_position-"+split[1]).val(obj.athleteDetail.Athlete.secondary_position);
                            $("#gpa-"+split[1]).val(obj.athleteDetail.Athlete.gpa);
                            $("#sat_score-"+split[1]).val(obj.athleteDetail.Athlete.sat_score);
                            $("#act_score-"+split[1]).val(obj.athleteDetail.Athlete.act_score);
                            $("#wingspan_id-"+split[1]).val(obj.athleteDetail.Athlete.wingspan);
                            $("#city-"+split[1]).val(obj.athleteDetail.Athlete.city);
                            if(obj.athleteDetail.Athlete.state != ''){
                                $("#state-"+split[1]).val(obj.athleteDetail.Athlete.state);
                                $("#state-"+split[1]).trigger("change");
                            }
                            $("#zip_code-"+split[1]).val(obj.athleteDetail.Athlete.zip);
                            $("#jersey_number-"+split[1]).val(obj.athleteDetail.Athlete.jersey_number);
                            $("#description-"+split[1]).val(obj.athleteDetail.Athlete.description);

                        }
                    });
                }
            }
    });



    $("#add_more").click(function(){
     var index = parseInt($("#total_reports").val()) ;
        $.ajax({
          type:'post',
          data:{'index':index},
          url: '<?php echo $this->Html->url('/admin/ScoutReport/getAddMoreHtml'); ?>' ,
          success: function( data ) {
            $("#total_reports").val(index+1) ;
            $("#new_form_html").append(data);
            $('html, body').animate({
                scrollTop: $(document).height()}, 'slow'); 
            return false;
          }
        });
    });

      });

</script>