<?php $error_msg='' ;?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

  <tr>
    <td height=120>
      <?php echo $this->element('admin_header');?></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td class="heading">
      <table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
        <tr>
          <td>
            <table cellSpacing=0 cellPadding=1 width=780 border=0>
              <tr>
                <td bgColor=#ffffff>
                  <table cellSpacing=0 cellPadding=0 width=900 border=0>
                    <tr>
                      <td vAlign=top width=20%>
                        <?php echo $this->element('admin_menu');?></td>
                      <td valign=top width=1%>&nbsp;</td>
                      <?php $s_image="/img/spacer.gif" ; ?>
                      <td width=10><img src="<?php echo $s_image?>" height="1" width="1">
                      </td>
                      <td valign=top width="">
                        <!-- MAin Content Starts From Here -->

                        <form name="frmsearchatheltes" method="post" action="<?php echo $this->Html->url('/admin/ScoutReport/atheletesearch')?>">
                          <table width="100%" border="1" cellpadding="1" cellspacing="0" bordercolor="#808080" style="border-collapse: collapse">
                            <tr height="20">
                              <td align="center" class="normalblack_12" width="90%" valign="top">
                                <table width="100%" border="0" cellpadding="0" cellspacing="0" bgcolor="#FFFFFF">
                                  <tr>
                                    <td valign="top" class="normalwhite_14" colspan=3 bgcolor="#808080" align="center"><b>Search Results</b>
                                    </td>
                                  </tr>
                                  <tr>
                                    <td valign="top" colspan=3 align="center">&nbsp;</td>
                                  </tr>

                                  <?php if($events): ?>
                                  <?php foreach($events as $event): ?>
                                  <tr height="20">
                                    <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                  </tr>
                                  <tr height="20">
                                    <td valign="top" align="right" class="normalblack_12" width="30%"><span><?php echo $event['SpecialEvent']['event_name'] ; ?></span>
                                    </td>
                                    <td valign="top" align="center" class="normalblack_12" width="20%">&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                    <td valign="top" align="left" class="normalblack_12">
                                      <input type="submit" name="<?php echo $event['SpecialEvent']['id'] ; ?>" value="View or Modify Reports">&nbsp;&nbsp;
                                    </td>
                                  </tr>
                                  <?php endforeach; ?>
                                  <?php else : ?>
                                  <tr height="20">
                                    <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                  </tr>
                                  <tr height="20">
                                    <td valign="top" colspan=3 align="center" class="normalblack_12"> No events found related your search, Do you want create new event?</td>
                                  </tr>
                                  <tr height="20">
                                    <td valign="top" colspan=3 align="center" class="normalblack_12">&nbsp;</td>
                                  </tr>
                                  <tr height="20">
                                    <td valign="top" align="right" class="normalblack_12" widt="30%"><?php if(isset($event_name)){ echo $event_name ; } ?></td>
                                    <td valign="top" align="center" class="normalblack_12" width="20%">&nbsp;&nbsp;&nbsp;&nbsp;</td>
                                    <td valign="top" align="left" class="normalblack_12">
                                        <input type="hidden" name="new_event" value="<?php if(isset($event_name)){ echo $event_name ; } ?>"/>
                                        <input type="submit" name="0" value="Create this event and add report">&nbsp;&nbsp;
                                    </td>
                                  </tr>

                                  <?php endif; ?>

                                  <tr height="20">
                                    <td valign="top" colspan=3 align="center" class="normalblack_12"></td>
                                  </tr>
                                </table>
                              </td>
                            </tr>
                          </table>
                        </form>
                        <!--Main Center Content END -->
                      </td>
                    </tr>
                  </table>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </td>
  </tr>
  <?php echo $this->element('admin_footer');?>
</table>