<TABLE cellSpacing=0 cellPadding=0 width="100%" border=0>

	<TR>

		<TD height=120><?php echo $this->element('admin_header');?></TD>

	</TR>

	<TR>

		<TD>&nbsp;</TD>

	</TR>

	<TR>

		<TD class="heading">

		<TABLE cellSpacing=0 cellPadding=1 width="95%" align=center border=0>

			<TR>

				<TD>

				<TABLE cellSpacing=0 cellPadding=1 width=780 border=0>

					<TR>

						<TD bgColor=#ffffff>

						<TABLE cellSpacing=0 cellPadding=0 width=900 border=0>

							<TR>

								<TD vAlign=top width=20%><?php echo $this->element('admin_menu');?></TD>

								<TD valign=top width=1%>&nbsp;</TD>
								<?php $s_image = "img/spacer.gif"; ?>

								<TD width=10><img src="<?=$s_image?>" height="1" width="1"></TD>

								<TD valign=top width=""><!-- Main Center Table Starts Here -->

								<table width="100%" border="1" cellpadding="1" cellspacing="0"
									bordercolor="#808080" style="border-collapse: collapse">

									<tr>

										<td align="center" class="normalblack_12" width="100%"
											colspan="2">

										<table width="100%" border="0" cellpadding="0" cellspacing="0"
											bgcolor="#FFFFFF">

											<tr>

												<td align="center" class="normalblack_12"><br>

												<strong>Welcome to the Admin Panel</strong><br>
												</td>

											</tr>

											<tr>

												<td>&nbsp;</td>

											</tr>

										</table>

										</td>

									</tr>

								</table>

								</TD>

							</TR>

						</TABLE>

						</TD>

					</TR>

				</TABLE>

				</TD>

			</TR>

		</TABLE>

		</TD>

	</TR>

	<?php echo $this->element('admin_footer');?>

</TABLE>
