<div class="cantener">
  <div class="register-main">
  	 <div class="registerPage">
		<?php echo $this->Form->create("AthleteTeam",array("url"=>array("controller"=>"Athlete","action"=>"addEditTeams", $this->Session->read('user_id'))));?>
		
			<h1>Manage Teams</h1>
		
			<p>
				<label>High School State 1:</label>
				<span>
					<?php echo $this->Form->input("state_id1",array("id"=>"state_id1","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getStates(),"empty"=>"Select One"));?>
				</span>
				<font color="#0000ff">&nbsp;*</font>
			</p>
			
			<?php $this->Js->get("#state_id1"); ?>
	    	<?php $this->Js->event('change',$this->Js->request(array('controller' => 'Profile','action' => 'getHsAauSchools',1),
	    					   array('async' => true,'update' => '#schools1','data' => '$("#state_id1").serialize()','dataExpression' => true
	               		 ))); 
	     	?>
	     	
	     	<div id="schools1">
	     		<?php if(@$teams1):?>
					<p>
					   <label>High School/AAU Team:</label>
					   <span>
					   		<?php echo $this->Form->input("AthleteTeam.hs_aau_team_id1",array("name"=>"data[AthleteTeam][hs_aau_team_id1]","id"=>"hs_aau_team_id1","div"=>false,"label"=>false,"required"=>"true","options"=>$teams1,"empty"=>"Select One"));?>
					   </span>
					   <font color="#0000ff">*</font>
					</p> 
				<?php endif;?>		
	     	</div>
	     	
	     	<br /><br /><br />
	     	
			<p>
				<label>High School State 2:</label>
				<span>
					<?php echo $this->Form->input("state_id2",array("id"=>"state_id2","div"=>false,"label"=>false,"required"=>"true","options"=>$this->Register->getStates(),"empty"=>"Select One"));?>
				</span>
				<font color="#0000ff">&nbsp;*</font>
			</p>
			
			<?php $this->Js->get("#state_id2"); ?>
	    	<?php $this->Js->event('change',$this->Js->request(array('controller' => 'Profile','action' => 'getHsAauSchools',2),
	    					   array('async' => true,'update' => '#schools2','data' => '$("#state_id2").serialize()','dataExpression' => true
	               		 ))); 
	     	?>
	     	
	     	<div id="schools2">
	     		<?php if(@$teams2):?>
					<p>
					   <label>High School/AAU Team:</label>
					   <span>
					   		<?php echo $this->Form->input("AthleteTeam.hs_aau_team_id2",array("name"=>"data[AthleteTeam][hs_aau_team_id2]","id"=>"hs_aau_team_id2","div"=>false,"label"=>false,"required"=>"true","options"=>$teams2,"empty"=>"Select One"));?>
					   </span>
					   <font color="#0000ff">*</font>
					</p> 
				<?php endif;?>	
	     	</div>
		
			<p>
				<label>&nbsp;</label>
				<span>
					<?php echo $this->Form->submit("Submit",array("type"=>"submit","div"=>false,"label"=>false));?>
					
					<?php echo $this->Form->submit("Back",array("type"=>"button","div"=>false,"label"=>false,"onclick"=>"window.location.href='".$this->Html->url(array("controller"=>"Profile","action"=>"index"))."'"));?>
				</span>
			</p>
		<?php echo $this->Form->end();?>
	</div>	
  </div>	
</div>	