<?php echo $this->Html->css("jquery.ui.stars.css?v=3.0.0b38");?>   
<?php echo $this->Html->script("jquery-ui.custom.min.js?v=1.8");?>
<?php echo $this->Html->script("jquery.ui.stars.js?v=3.0.0b38");?>

<?php 
  $options = array();
  for($i=1;$i<=10;$i++){
  	  if($i == 1){
  	  	 $options[$i] = " (Lowest)";
  	  }	
  	  elseif($i == 10){
  	  	 $options[$i] = " (Highest)";
  	  }
  	  else{
  	   	 $options[$i] = $i; 
  	  }
  }
?>
<script type="text/javascript">
	jQuery(function(){
		jQuery(".multiField")
		.stars({
		    inputType: "select",
		    cancelValue: 0,
		    cancelShow: true,
		});
	});
	
	function validate() {
        var error_msg = "";
        
        if(jQuery("#leadership").find("input").val() == "0") {
            error_msg += "Please Select LeaderShip. \n";
        }
        if(jQuery("#work_ethic").find("input").val() == "0") {
            error_msg += "Please Select Work Ethic. \n";
        }
        if(jQuery("#primacy_go_to_guy").find("input").val() == "0") {
            error_msg += "Please Select Primacy Go To Guy. \n";
        }
        if(jQuery("#mental_toughness").find("input").val()== "0") {
            error_msg += "Please Select Mental Toughness. \n";
        }
        if(jQuery("#composure").find("input").val() == "0") {
            error_msg += "Please Select Composure. \n";
        }
        if(jQuery("#awareness").find("input").val() == "0") {
            error_msg += "Please Select Awareness. \n";
        }
        if(jQuery("#instincts").find("input").val()== "0") {
            error_msg += "Please Select Instincts. \n";
        }
        if(jQuery("#vision").find("input").val() == "0") {
            error_msg += "Please Select Vision. \n";
        }
        if(jQuery("#conditioning").find("input").val()== "0") {
            error_msg += "Please Select Conditioning. \n";
        }
        if(jQuery("#physical_toughness").find("input").val()== "0") {
            error_msg += "Please Select Physical Toughness. \n";
        }
        if(jQuery("#tenacity").find("input").val() == "0") {
            error_msg += "Please Select Tenacity. \n";
        }
        if(jQuery("#hustle").find("input").val() == "0") {
            error_msg += "Please Select Hustle. \n";
        }
        if(jQuery("#strength").find("input").val() == "0") {
            error_msg += "Please Select Strength. \n";
        }

        if(error_msg != '') {
            alert(error_msg);
            return false;
        } 
        else {
        	jQuery(".multiField").find("input").removeAttr("disabled");
            return true;
        }
    }
</script>

<div class="cantener">
  <div class="register-main">							
	<div class="registerPage smallest">			
	   <?php if(@$ratingSaved):?>
	   
	   		<div class="thankyoumessage">Thank you, your Rating was successfully added.</div>	
	   		
	   <?php elseif(!$ratingExist):?>
			<h1>Rate Athlete</h1>
			
			<?php echo $this->Form->create("Rating",array("url"=>array("controller"=>"Athlete","action"=>"addRating",$athlete_id),"onsubmit"=>"return validate();"))?>
                
                <p>
                   <label>Leadership:</label>                     
                   <span class="multiField" id="leadership">     
                   	  <?php echo $this->Form->input("leadership",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Work Ethic:</label>                     
                   <span class="multiField" id="work_ethic">     
                   	  <?php echo $this->Form->input("work_ethic",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Primacy (Go-To Guy):</label>                     
                   <span class="multiField" id="primacy_go_to_guy">     
                   	  <?php echo $this->Form->input("primacy_go_to_guy",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Mental Toughness:</label>                     
                   <span class="multiField" id="mental_toughness">     
                   	  <?php echo $this->Form->input("mental_toughness",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Composure:</label>                     
                   <span class="multiField" id="composure">     
                   	  <?php echo $this->Form->input("composure",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Awareness:</label>                     
                   <span class="multiField" id="awareness">     
                   	  <?php echo $this->Form->input("awareness",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Instincts:</label>                     
                   <span class="multiField" id="instincts">     
                   	  <?php echo $this->Form->input("instincts",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Vision:</label>                     
                   <span class="multiField" id="vision">     
                   	  <?php echo $this->Form->input("vision",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Conditioning:</label>                     
                   <span class="multiField" id="conditioning">     
                   	  <?php echo $this->Form->input("conditioning",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Physical Toughness:</label>                     
                   <span class="multiField" id="physical_toughness">     
                   	  <?php echo $this->Form->input("physical_toughness",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Tenacity:</label>                     
                   <span class="multiField" id="tenacity">     
                   	  <?php echo $this->Form->input("tenacity",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Hustle:</label>                     
                   <span class="multiField" id="hustle">     
                   	  <?php echo $this->Form->input("hustle",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                
                <p>
                   <label>Strength:</label>                     
                   <span class="multiField" id="strength">     
                   	  <?php echo $this->Form->input("strength",array("div"=>false,"label"=>false,"type"=>"select","options"=>$options,"empty"=>"Reset Rating","required"));?>    
                    </span>                  
                </p>
                  
             	<p style="height:20px;">&nbsp;</p>
             	
            	<p>
           		  <label>&nbsp;</label>
            	  <span>
            	  	  <?php echo $this->Form->submit("Submit Rating",array("div"=>false,"label"=>false))?>
                  </span>
                </p>
		<?php echo $this->Form->end();?>
		
	<?php else:?>
			
			<?php echo "Sorry, you have already voted for this Athlete.  Please <a href='".$this->Html->url(array("controller"=>"Rating","action"=>"viewAthleteRating",$athlete_id))."'>Click Here</a> to view Ratings";?>
	
	<?php endif;?>		
  </div>
</div>
</div>