<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
<?php
echo $this->Html->css('/fancybox/admin/jquery.fancybox-1.3.4.css');
echo $this->Html->script('/fancybox/admin/jquery.easing-1.3.pack.js');
echo $this->Html->script('/fancybox/admin/jquery.fancybox-1.3.4.js');
echo $this->Html->script('/fancybox/admin/jquery.mousewheel-3.0.4.pack.js');
?>
<table cellSpacing=0 cellPadding=0 width="100%" border=0>
	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
			<tr>
				<td>
				<table cellSpacing=0 cellPadding=1 width=780 border=0>
					<tr>
						<td bgColor=#ffffff>
							<table cellSpacing=0 cellPadding=0 width=780 border=0>
								<tr>
									<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
									<td valign=top width=1%>&nbsp;</td>
									<?php $s_image = "/img/spacer.gif"; ?>
									<td width=10><img src="<?php echo $s_image?>" height="1" width="1"></td>
									<td valign=top>
									<!-- Main Center Table Starts Here --> <!--Main Center Content BEGIN -->
										<table border="1" cellpadding="1" cellspacing="0" width="100%"
											bordercolor="#808080" style="border-collapse: collapse"
											class="tablePadd">	
											<tr>
												<td align="center" class="normalwhite_14" colspan="11"
													bgcolor="#808080"><strong>Athlete Listing</strong></td>
											</tr>	
											<tr>
												<td align='center' class='normalblack_12' colspan='11'
													height='30' valign='middle'><font color='red'><?php echo (isset($msg) ? $msg : "");?></font>
												</td>
											</tr>	
											<tr>
												<td align='center' class='normalblack_12' colspan='11'
													height='30' valign='middle'>
							
													<form name="searchFrm" id="searchFrm" action="/admin/Athlete/list"  method="POST">																												
														<input type="hidden" name="page" id="page" value="0">												 
														<input type="text" name="searchname" id="searchname">												 
														<input type="submit" name="search" id="search" style="width: 180px" value="Search Athlete By Name">												
													</form>
												</td>
											</tr>
											
											<form name="frmUsers" action="" method="post" onsubmit="">
												<?php if (!empty($athletes)) {?>
												<tr> 
													<td align="left" style="padding-left:7px;"colspan="11">
														<input type="checkbox" id="check_all" name="check_all" value="" onclick="javascript:checkAll();"> 
															<b>Check All</b>&nbsp; &nbsp;
														<input type="button" name="delete" value="Delete Selected" onclick="return deleteSelectedAthlete();">																																															
													</td>
												</tr>				
												<tr>
													<td align="center" class="normalblack_12" width="4%">&nbsp;</td>	
													<td align="left" class="normalblack_12" width="8%">&nbsp;<strong>S.No.</strong></td>	
													<td align="left" class="normalblack_12" width="20%">&nbsp;<strong>UserName</strong></td>	
													<td align="left" class="normalblack_12" width="25%">&nbsp;<strong>Email</strong></td>
													<td align="left" class="normalblack_12" width="15%">&nbsp;<strong>FirstName</strong></td>	
													<td align="left" class="normalblack_12" width="10%">&nbsp;<strong>LastName</strong></td>	
													<td class="normalblack_12" width="5%" align="center"><strong>Status</strong></td>	
													<td class="normalblack_12" width="5%" align="center"><strong>Edit</strong></td>	
													<td class="normalblack_12" width="7%" align="center"><strong>Delete</strong></td>	
													<td class="normalblack_12" width="7%" align="center"><strong>View</strong></td>		
												</tr>
												<?php $i = 0;?>
												<?php foreach ($athletes as $athlete):?>
												<?php $i++;?>
												<tr>
													<td align="center" class="normalblack_12">&nbsp; <input
														type="checkbox" id="check_delete[]" name="check_delete[]"
														value="<?php echo $athlete['Athlete']['id']?>" onclick="return checkItSelf();">
													</td>
													<td align="left" class="normalblack_12">&nbsp;<?php echo ($i + $limit * ($this->Paginator->current() - 1));?></td>			
													<td align="left" class="normalblack_12"><?php echo wordwrap($athlete['Athlete']['username'],14,"\n",true)?></td>	
													<td align="left" class="normalblack_12"><?php echo wordwrap($athlete['Athlete']['email'],24,"\n",true)?></td>	
													<td align="left" class="normalblack_12"><?php echo wordwrap($athlete['Athlete']['firstname'],15,"\n",true)?></td>	
													<td align="left" class="normalblack_12"><?php echo wordwrap($athlete['Athlete']['lastname'],15,"\n",true)?></td>
													<?php if ($athlete['Athlete']['status'] == '0') {?>
													<td  class="normalblack_12" align="center">																
														<?php echo $this->Html->link($this->Html->image('/img/red-point.gif'), array('controller' => 'Athlete', 'action' => 'activeRecord', $athlete['Athlete']['id']), array('escape' => false, 'title' => 'Active'), "Are you sure to active this Athlete?")?>
													</td>
													<?php } else {?>
													<td  class="normalblack_12" align="center">
														<?php echo $this->Html->link($this->Html->image('/img/green-point.gif'), array('controller' => 'Athlete', 'action' => 'deactiveRecord', $athlete['Athlete']['id']), array('escape' => false, 'title' => 'Deactive'), "Are you sure to deactive this Athlete?")?>
													</td>
													<?php }?>
													<td class="normalblack_12" align="center">																
														<?php echo $this->Html->link($this->Html->image('/img/b_edit.png'), array('controller' => 'Athlete', 'action' => 'edit', $athlete['Athlete']['id']), array('escape' => false, 'title' => 'Edit'))?>
													</td>
													<td class="normalblack_12" align="center">																
														<?php echo $this->Html->link($this->Html->image('/img/b_drop.png'), array('controller' => 'Athlete', 'action' => 'delete', $athlete['Athlete']['id']), array('escape' => false, 'title' => 'Delete'), "Are you sure to delete this Athlete?")?>
													</td>
													<td  class="normalblack_12" align="center" nowrap>
														<?php echo $this->Html->link('View', array('controller' => 'Athlete', 'action' => 'details', $athlete['Athlete']['id']), array('id' => 'view_athlete'))?> /
														<?php echo $this->Html->link('View Rate', array('controller' => 'Athlete', 'action' => 'viewRating', $athlete['Athlete']['id']), array('id' => 'view_rate'))?> /
														<?php echo $this->Html->link('Login As Athlete', array('controller' => 'Athlete', 'action' => 'viewAthlete', $athlete['Athlete']['id']), array('target' => 'blank'))?>
													</td>															
												</tr>
												<?php endforeach?>
							
											</form>
											<?php } else {?>
												<tr>
													<td align="center" class="normalblack_12" colspan="10" height="30">
														<font color="red">No Records Available.</font>
													</td>
												</tr>
											<?php }?>
										</table>	
										<!--Main Center Content END -->
										<?php echo $this->element('pagination');?>
									</td>
								</tr>
							</table>
							<!--Main Center Content END --> 
						
						</td>
					</tr>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
<?php echo $this->element('admin_footer');?>
</table>
<script type="text/javascript">
$(document).ready(function() {
		
	$("a#view_athlete").fancybox({
		'hideOnContentClick': true
	});
	
	$("a#view_rate").fancybox({
		'hideOnContentClick': true
	});	

});
</script>
