<table cellSpacing=0 cellPadding=0 width="100%" border=0>
	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<tr>
			<td class="heading">
			<table cellSpacing=0 cellPadding=1 width="95%" align=center border=0>
				<tr>
					<td>
					<table cellSpacing=0 cellPadding=1 width=780 border=0>
						<tr>
							<td bgColor=#ffffff>
							<table cellSpacing=0 cellPadding=0 width=900 border=0>
								<tr>
									<td vAlign=top width=20%><?php echo $this->element('admin_menu');?></td>
									<td valign=top width=1%>&nbsp;</td>
									<td width=10><img src="spacer.gif" height="1" width="1"></td>
									<td valign=top width="" align="center"><!-- MAin Content Starts From Here -->
									<form name="frmAthReg" action="" method="post"
										enctype="multipart/form-data" onsubmit="return validate()">
									<table width="100%" border="1" cellpadding="1" cellspacing="0"
										bordercolor="#808080" style="border-collapse: collapse">
										<tr height="20">
											<td align="center" class="normalblack_12" width="90%"
												valign="top">
											<table width="100%" border="0" cellpadding="0"
												cellspacing="0" bgcolor="#FFFFFF">
												<tr>
													<!-- Display the message on heading of the page -->
													<td valign="top" class="normalwhite_14" colspan=3
														bgcolor="#808080" align="center"><b>View Athlete Athletic
													Stats</b></td>
												</tr>
												<tr>
													<!-- Display the message on heading of the page -->
													<td valign="top" colspan=3 align="center">&nbsp;</td>
												</tr>
												<tr>
													<td valign="top" colspan=3 align="center"
														class="normalblack_12"><font color="Red"></font></td>
												</tr>
												<tr>
													<td height="35" colspan="3" align="right"
														class="normalblack_12"></td>
												</tr>
												<tr height="20">
													<td valign="top" class="normalwhite_14" colspan=3
														align="center">&nbsp;</td>
												</tr>
												<?php if (sizeof($athleteStats)>0) {?>
												<tr height="20">
													<td valign="top" colspan=2 align="center"
														class="normalblack_12"><strong><?php echo ucwords($event['Event']['event_name'])?></strong></td>
												</tr>
												</tr>
												<tr height="20">
													<td valign="top" colspan=2 align="center"
														class="normalblack_12">&nbsp;</td>
												</tr>
												<tr>
													<td align="center" class="normalblack_12" width="15%">&nbsp;<strong>Stats
													Category</strong></td>
													<td align="center" class="normalblack_12" width="15%">&nbsp;<strong>Points</strong></td>
												</tr>
												<tr height="20">
													<td valign="top" colspan=2 align="center"
														class="normalblack_12">&nbsp;</td>
												</tr>
												<?php foreach($athleteStats as $athleteStat) :?>
												<tr>
													<td valign="top" align="center" class="normalblack_12"
														width="15%"><?php echo $athleteStat['AthleteStat']['label_name'] ?></td>
													<td valign="top" align="center" class="normalblack_12"
														width="15%"><?php echo $athleteStat['AthleteStat']['value'] ?></td>
												</tr>
												<tr height="20">
													<td valign="top" colspan=2 align="center"
														class="normalblack_12">&nbsp;</td>
												</tr>
												<?php endforeach ?>
																								
												<?php } else { ?>
												<tr>
													<td align="center" class="normalblack_12" colspan="10"
														height="30"><font color="red">No Records Available.</font></td>
												</tr>												
												<?php } ?>

												<!-- Upoad File END-->
											</table>
											</td>
										</tr>
									</table>
									</form>
									<!--Main Center Content END --></td>
								</tr>
							</table>
							</td>
						</tr>
					</table>
					</td>
				</tr>
			</table>
			</td>
		</tr>
		<?php echo $this->element('admin_footer');?>

</table>
