<!-- Sport -->
<p class="alt">
    <label>Sport:</label>
    <span>
        <?php echo $this->Form->input("sport_id",array("div"=>false,"label"=>false,"options"=>$this->Register->getSports(),"empty"=>"Select Sport"));?>
    </span>
</p>

<!-- Graduating Class -->
<p class="alt">
    <label>Graduating Class:</label>
    <span>
        <?php echo $this->Form->input("class",array("div"=>false,"label"=>false,"options"=>$this->Register->getClasses(),"empty"=>"Select Class"));?>
    </span>
</p>

<!-- Division -->
<p class="alt">
    <label>Division:</label>
    <span>
        <?php echo $this->Form->input("division",array("div"=>false,"label"=>false,"options"=>$this->Register->getDivisions(),"empty"=>"Select Division"));?>
    </span>
</p>

<!-- Height -->
<p class="alt">
    <label>Height:</label>
    <span>
        <?php echo $this->Form->input("height",array("div"=>false,"label"=>false,"options"=>$this->Register->getHeights(),"empty"=>"Select Height"));?>
    </span>
</p>

<!-- Weight -->
<p class="alt">
    <label>Weight:</label>
    <span>
        <?php echo $this->Form->input("weight_min",array("div"=>false,"label"=>false,"options"=>$this->Register->getWeights(),"empty"=>"Select Min Weight"));?>
    </span>
    
    <span>
        <?php echo $this->Form->input("weight_max",array("div"=>false,"label"=>false,"options"=>$this->Register->getWeights(),"empty"=>"Select Max Weight"));?>
    </span>
</p>

<!-- Positions -->
<p class="alt">
    <label>Sport Position:</label>
    <span>
        <?php echo $this->Form->input("primary_position",array("div"=>false,"label"=>false,"options"=>$this->Register->getPositions(),"empty"=>"Select Primary Position"));?>
    </span>
    
    <span>
        <?php echo $this->Form->input("secondary_position",array("div"=>false,"label"=>false,"options"=>$this->Register->getPositions(),"empty"=>"Select Secondary Position"));?>
    </span>
</p>