<div class="cantener">
  <div class="register-main">
  	  <h1>All Athlete List</h1>
  	  	
      <div class="registerPage">
       
      <?php echo $this->Form->create("Athlete",array("url"=>array("controller"=>"Athlete","action"=>"index"),"type"=>"get"));?>  
	      <p>
			 <label>Filter By Division:</label>
			 <span><?php echo $this->Form->input("division",array("div"=>false,"label"=>false,"selected"=>@$division,"empty"=>"Select One","options"=>$this->Register->getDivisions(),"onchange"=>"this.form.submit();"));?></span>
	      </p>		 
	
		  <?php if(count(@$athletes) > 0):?>
	         <table cellspacing="2" cellpadding="5" bordercolor="#808080" border="0" width="100%" class="tablePadd" style="border-collapse: collapse;">
	         	  <tr>
	                  <td align="center" class="normalblack_12" width="10%">&nbsp;<strong></strong></td>
	                  <td align="center" class="normalblack_12" width="35%">&nbsp;<strong>Name</strong></td>
	                  <td align="center" class="normalblack_12" width="20%">&nbsp;<strong>Sport</strong></td>
	                  <td align="center" class="normalblack_12" width="15%">
	                  	  <?php 
								echo $this->Paginator->sort('height', 'Height',array("title"=>__("Sort",true)));
								if(isset($this->params['named']['sort']) && $this->params['named']['sort'] == "height"){
									echo "&nbsp;&nbsp;".$this->Html->image(strtoupper($this->params['named']['direction']).'.gif',array('alt'=>"" ,'border'=>0));
								}
						  ?>
	                  </td>
	                  <td class="normalblack_12" width="15%" align="center"><strong>View Profile</strong></td>
	              </tr>
	                    
	              <?php foreach ($athletes as $athlete): ?>
	              	 <tr>
	                      <td align="center" class="normalblack_12">
	                      		<a href="<?php echo $this->Html->url(array("controller"=>"Profile","athleteProfile",$athlete['Athlete']['id']));?>" title="<?php echo html_entity_decode($athlete['Athlete']['firstname']); ?>">
					                 <?php echo $this->Html->image("athlete/".$athlete['Athlete']['image'],array("width"=>"60px","title"=>$athlete['Athlete']['firstname']));?>
					            </a>
					      </td>
	                      <td align="center" class="normalblack_12"><?php echo $athlete['Athlete']['firstname']." ".$athlete['Athlete']['lastname']?></td>
	                      <td align="center" class="normalblack_12"><?php echo $athlete['Sport']['name']; ?></td>
	                      <td align="center" class="normalblack_12"><?php echo $athlete['Athlete']['height'];?></td>
	                     
	                      <td class="normalblack_12" align="center">
                      		 <a href="<?php echo $this->Html->url(array("controller"=>"Profile","action"=>"athleteProfile",$athlete['Athlete']['id']));?>" title="<?php echo html_entity_decode($athlete['Athlete']['firstname']); ?>">
                      			<?php echo $this->Html->image("view.gif");?>
                      		 </a>
	                      </td>
	                 </tr>
		          <?php endforeach; ?>
		     </table>
		     
		     <div style="clear:both;"></div>
		     
		     <?php echo $this->Element('pagination');?>
		     
	     <?php endif;?> 	
	  <?php echo $this->Form->end();?>     
   </div>	   
  </div>
</div>    		     