<div>
    <label>Sport Position:</label>
    <span>
        <?php echo $this->Form->input("primary_position",array("div"=>false,"label"=>false,"options"=>$options,"empty"=>"Select Primary Position"));?>
    </span>
    
    <span>
        <?php echo $this->Form->input("secondary_position",array("div"=>false,"label"=>false,"options"=>$options,"empty"=>"Select Secondary Position"));?>
    </span>
</div>