<div class="cantener">
  <div class="register-main">
	  <div class="registerPage">
		  <h1>View Game Log</h1>
		  
		  <?php if($athleteStats):?>
				  <?php foreach($athleteStats as $athleteStat):?>
				  		<h4><?php echo $athleteStat['Event']['event_name'];?></h4>
				  		
				  		<?php foreach($athleteStat['stats'] as $stats):?>
				  			<p><b><?php echo $stats['AthleteStat']['label_name']. " :</b> ". $stats['AthleteStat']['value'];?></p>
				  		<?php endforeach;?>
				  		
				  		<br /><br />
				  <?php endforeach;?>
		 <?php else:?>
		 
		 	<div class='thankyoumessage'>No Records Available</div><br><br>
		 
		 <?php endif;?>				  
	  </div>
   </div>
</div>   