<table cellSpacing=0 cellPadding=0 width="100%" border=0>
	<tr>
		<td height=120><?php echo $this->element('admin_header');?></td>
	</tr>
	<tr>
		<td></td>
	</tr>
	<tr>
		<td align="center">
			<div class='error'>
				<?php if (isset($msg)) echo $msg; ?> <?php if(isset($error['email'])) echo $error['email']; ?>
			</div>
		</td>
	</tr>
	<tr>
		<td class="heading">
		<table cellSpacing=0 cellPadding=0 width=716 align=center border=0>
			<tr>
				<td align="center">
				<table width="400" border="0" cellpadding="1" cellspacing="0"
					bgcolor="#4A74A5">
					<?php echo $this->Form->create();?>					
					<tr>
						<td>
						<table width="100%" border="0" cellpadding="0" cellspacing="0"
							bgcolor="#FFFFFF">
							<tr>
								<td>
								<table width="100%" border="0" cellpadding="0" cellspacing="2"
									bgcolor="#FFFFFF">
									<tr align="center" valign="middle">
										<td colspan="2" class="normalblack_12"><br>
										<strong>Forgot Password</strong></td>
									</tr>
									<tr align="center" valign="middle">
										<td colspan="2" class="normalblack_12">&nbsp;</td>
									</tr>
									<tr>
										<td align="right" class="normalgrey_12">Enter Your Email :</td>
										<td><input type="text" name="email" id="email"
											class="long_inputbox" size="35" required=true></td>
									</tr>
									<tr>
										<td>&nbsp;</td>
										<td align="left" height="30"><input type="submit"
											name="submit" id="submit" class="button" value="Submit"></td>
									</tr>
									<tr>
										<td>&nbsp;</td>
										<td align="left" height="30" class="normalblack_12"></td>
									</tr>
								</table>
								</td>
							</tr>
						</table>
						</td>
					</tr>
					<?php echo $this->Form->end();?>
				</table>
				</td>
			</tr>
		</table>
		</td>
	</tr>
	<tr>
		<td height=27 class="normalgrey_12">&nbsp;</td>
	</tr>
	<?php echo $this->element('admin_footer');?>
</table>
