
<table cellSpacing=0 cellPadding=0 width="100%" border=0>

	<tr>

		<td height=120></td>

	</tr>

	<tr>

		<td></td>

	</tr>

	<tr>

		<td class="heading">

		<table cellSpacing=0 cellPadding=0 width=716 align=center border=0>

			<tr>

				<td align="center">

				<table width="400" border="0" cellpadding="1" cellspacing="0"
					bgcolor="#4A74A5">

					<form name="adminForm" action="" method="POST"
						onsubmit="return validate(document.adminForm);">

					<tr>

						<td>

						<table width="100%" border="0" cellpadding="0" cellspacing="0"
							bgcolor="#FFFFFF">

							<tr>

								<td>

								<table width="100%" border="0" cellpadding="0" cellspacing="2"
									bgcolor="#FFFFFF">

									<tr align="center" valign="middle">

										<td colspan="2" class="normalblack_12"><br>

										<strong>Administrator Login</strong></td>

									</tr>
									<?
						            if(isset($errorMsg) && $errorMsg!="")						
						            {						
						                echo "<tr align='center' valign='middle'><td colspan='2' class='normalblack_12'>&nbsp;</td></tr><tr align='center' valign='middle'><td colspan='2' class='normalblack_12'><font color=red>$errorMsg</font></td></tr>";						
						            }						
						            ?> 


									<tr align="center" valign="middle">
										<td colspan="2" class="normalblack_12">&nbsp;</td>

									</tr>

									<tr>

										<td align="right" class="normalgrey_12">Username :</td>

										<td><input name="username" type="text" maxlength="100"
											class="normalgrey_12" value=""></td>

									</tr>

									<tr>

										<td align="right" class="normalgrey_12">Password :</td>

										<td><input name="password" type="password" maxlength="50"
											class="normalgrey_12" value=""></td>

									</tr>

									<tr>

										<td>&nbsp;</td>

										<td align="left" height="30"><input name="btnSubmit"
											type="submit" class="normalblack_12" value="Submit"></td>

									</tr>

									<tr>

										<td>&nbsp;</td>

										
										
										<td align="left" height="30" class="normalblack_12">
											<?php echo $this->Html->link('Forgot Password', array('controller' => 'admin', 'action' => 'forgot_password'))?>
										</td>

									</tr>



								</table>

								</td>

							</tr>

						</table>

						</td>

					</tr>

					</form>

				</table>

				</td>

			</tr>

		</table>

		</td>

	</tr>

	<tr>

		<td height=27 class="normalgrey_12">&nbsp;</td>

	</tr>

</table>
